// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shared_d_fota_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FotaStatus_State int32

const (
	FotaStatus_IDLE        FotaStatus_State = 0
	FotaStatus_DOWNLOADING FotaStatus_State = 1
	FotaStatus_VERIFYING   FotaStatus_State = 2
	FotaStatus_APPLYING    FotaStatus_State = 3
	FotaStatus_SUCCESS     FotaStatus_State = 4
	FotaStatus_FAILED      FotaStatus_State = 5
)

// Enum value maps for FotaStatus_State.
var (
	FotaStatus_State_name = map[int32]string{
		0: "IDLE",
		1: "DOWNLOADING",
		2: "VERIFYING",
		3: "APPLYING",
		4: "SUCCESS",
		5: "FAILED",
	}
	FotaStatus_State_value = map[string]int32{
		"IDLE":        0,
		"DOWNLOADING": 1,
		"VERIFYING":   2,
		"APPLYING":    3,
		"SUCCESS":     4,
		"FAILED":      5,
	}
)

func (x FotaStatus_State) Enum() *FotaStatus_State {
	p := new(FotaStatus_State)
	*p = x
	return p
}

func (x FotaStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FotaStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_d_fota_v1_proto_enumTypes[0].Descriptor()
}

func (FotaStatus_State) Type() protoreflect.EnumType {
	return &file_shared_d_fota_v1_proto_enumTypes[0]
}

func (x FotaStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FotaStatus_State.Descriptor instead.
func (FotaStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_shared_d_fota_v1_proto_rawDescGZIP(), []int{0, 0}
}

type FotaStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           FotaStatus_State       `protobuf:"varint,1,opt,name=state,proto3,enum=device.FotaStatus_State" json:"state,omitempty"`
	ProgressPercent uint32                 `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Detail          string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	CurrentVersion  string                 `protobuf:"bytes,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	TargetVersion   string                 `protobuf:"bytes,5,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	CommandId       string                 `protobuf:"bytes,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ProtoVersion    ProtoVersion           `protobuf:"varint,100,opt,name=proto_version,json=protoVersion,proto3,enum=device.ProtoVersion" json:"proto_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FotaStatus) Reset() {
	*x = FotaStatus{}
	mi := &file_shared_d_fota_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FotaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FotaStatus) ProtoMessage() {}

func (x *FotaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_fota_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FotaStatus.ProtoReflect.Descriptor instead.
func (*FotaStatus) Descriptor() ([]byte, []int) {
	return file_shared_d_fota_v1_proto_rawDescGZIP(), []int{0}
}

func (x *FotaStatus) GetState() FotaStatus_State {
	if x != nil {
		return x.State
	}
	return FotaStatus_IDLE
}

func (x *FotaStatus) GetProgressPercent() uint32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *FotaStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *FotaStatus) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *FotaStatus) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *FotaStatus) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *FotaStatus) GetProtoVersion() ProtoVersion {
	if x != nil {
		return x.ProtoVersion
	}
	return ProtoVersion_PROTO_VERSION_UNSPECIFIED
}

var File_shared_d_fota_v1_proto protoreflect.FileDescriptor

const file_shared_d_fota_v1_proto_rawDesc = "" +
	"\n" +
	"\x16shared_d_fota_v1.proto\x12\x06device\x1a\x18shared_d_common_v1.proto\"\x83\x03\n" +
	"\n" +
	"FotaStatus\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.device.FotaStatus.StateR\x05state\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\rR\x0fprogressPercent\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12'\n" +
	"\x0fcurrent_version\x18\x04 \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0etarget_version\x18\x05 \x01(\tR\rtargetVersion\x12\x1d\n" +
	"\n" +
	"command_id\x18\x06 \x01(\tR\tcommandId\x129\n" +
	"\rproto_version\x18d \x01(\x0e2\x14.device.ProtoVersionR\fprotoVersion\"X\n" +
	"\x05State\x12\b\n" +
	"\x04IDLE\x10\x00\x12\x0f\n" +
	"\vDOWNLOADING\x10\x01\x12\r\n" +
	"\tVERIFYING\x10\x02\x12\f\n" +
	"\bAPPLYING\x10\x03\x12\v\n" +
	"\aSUCCESS\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05BBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_shared_d_fota_v1_proto_rawDescOnce sync.Once
	file_shared_d_fota_v1_proto_rawDescData []byte
)

func file_shared_d_fota_v1_proto_rawDescGZIP() []byte {
	file_shared_d_fota_v1_proto_rawDescOnce.Do(func() {
		file_shared_d_fota_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_d_fota_v1_proto_rawDesc), len(file_shared_d_fota_v1_proto_rawDesc)))
	})
	return file_shared_d_fota_v1_proto_rawDescData
}

var file_shared_d_fota_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_d_fota_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_d_fota_v1_proto_goTypes = []any{
	(FotaStatus_State)(0), // 0: device.FotaStatus.State
	(*FotaStatus)(nil),    // 1: device.FotaStatus
	(ProtoVersion)(0),     // 2: device.ProtoVersion
}
var file_shared_d_fota_v1_proto_depIdxs = []int32{
	0, // 0: device.FotaStatus.state:type_name -> device.FotaStatus.State
	2, // 1: device.FotaStatus.proto_version:type_name -> device.ProtoVersion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_d_fota_v1_proto_init() }
func file_shared_d_fota_v1_proto_init() {
	if File_shared_d_fota_v1_proto != nil {
		return
	}
	file_shared_d_common_v1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_d_fota_v1_proto_rawDesc), len(file_shared_d_fota_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_d_fota_v1_proto_goTypes,
		DependencyIndexes: file_shared_d_fota_v1_proto_depIdxs,
		EnumInfos:         file_shared_d_fota_v1_proto_enumTypes,
		MessageInfos:      file_shared_d_fota_v1_proto_msgTypes,
	}.Build()
	File_shared_d_fota_v1_proto = out.File
	file_shared_d_fota_v1_proto_goTypes = nil
	file_shared_d_fota_v1_proto_depIdxs = nil
}
