// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shared_d_identity_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceIdentity struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceId  string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Imei      string                 `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Serial    string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	CpuUid    string                 `protobuf:"bytes,4,opt,name=cpu_uid,json=cpuUid,proto3" json:"cpu_uid,omitempty"`
	Model     string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	FwVersion string                 `protobuf:"bytes,6,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	// Additive schema version for hello root (MQTT ingest/telemetry/hello).
	ProtoVersion  ProtoVersion `protobuf:"varint,100,opt,name=proto_version,json=protoVersion,proto3,enum=device.ProtoVersion" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIdentity) Reset() {
	*x = DeviceIdentity{}
	mi := &file_shared_d_identity_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIdentity) ProtoMessage() {}

func (x *DeviceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_identity_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIdentity.ProtoReflect.Descriptor instead.
func (*DeviceIdentity) Descriptor() ([]byte, []int) {
	return file_shared_d_identity_v1_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceIdentity) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceIdentity) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceIdentity) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceIdentity) GetCpuUid() string {
	if x != nil {
		return x.CpuUid
	}
	return ""
}

func (x *DeviceIdentity) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceIdentity) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *DeviceIdentity) GetProtoVersion() ProtoVersion {
	if x != nil {
		return x.ProtoVersion
	}
	return ProtoVersion_PROTO_VERSION_UNSPECIFIED
}

var File_shared_d_identity_v1_proto protoreflect.FileDescriptor

const file_shared_d_identity_v1_proto_rawDesc = "" +
	"\n" +
	"\x1ashared_d_identity_v1.proto\x12\x06device\x1a\x18shared_d_common_v1.proto\"\xe2\x01\n" +
	"\x0eDeviceIdentity\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04imei\x18\x02 \x01(\tR\x04imei\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x17\n" +
	"\acpu_uid\x18\x04 \x01(\tR\x06cpuUid\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x06 \x01(\tR\tfwVersion\x129\n" +
	"\rproto_version\x18d \x01(\x0e2\x14.device.ProtoVersionR\fprotoVersionBBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_shared_d_identity_v1_proto_rawDescOnce sync.Once
	file_shared_d_identity_v1_proto_rawDescData []byte
)

func file_shared_d_identity_v1_proto_rawDescGZIP() []byte {
	file_shared_d_identity_v1_proto_rawDescOnce.Do(func() {
		file_shared_d_identity_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_d_identity_v1_proto_rawDesc), len(file_shared_d_identity_v1_proto_rawDesc)))
	})
	return file_shared_d_identity_v1_proto_rawDescData
}

var file_shared_d_identity_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_d_identity_v1_proto_goTypes = []any{
	(*DeviceIdentity)(nil), // 0: device.DeviceIdentity
	(ProtoVersion)(0),      // 1: device.ProtoVersion
}
var file_shared_d_identity_v1_proto_depIdxs = []int32{
	1, // 0: device.DeviceIdentity.proto_version:type_name -> device.ProtoVersion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_d_identity_v1_proto_init() }
func file_shared_d_identity_v1_proto_init() {
	if File_shared_d_identity_v1_proto != nil {
		return
	}
	file_shared_d_common_v1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_d_identity_v1_proto_rawDesc), len(file_shared_d_identity_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_d_identity_v1_proto_goTypes,
		DependencyIndexes: file_shared_d_identity_v1_proto_depIdxs,
		MessageInfos:      file_shared_d_identity_v1_proto_msgTypes,
	}.Build()
	File_shared_d_identity_v1_proto = out.File
	file_shared_d_identity_v1_proto_goTypes = nil
	file_shared_d_identity_v1_proto_depIdxs = nil
}
