// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shared_d_common_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bump ProtoVersion when the on-wire contract for a root changes in a way
// consumers must notice (removed/renumbered fields, Envelope removed, etc.).
// Additive optional fields may keep the same version if backends are
// forward-compatible. Firmware always sets the current value on encode.
type ProtoVersion int32

const (
	ProtoVersion_PROTO_VERSION_UNSPECIFIED ProtoVersion = 0
	ProtoVersion_PROTO_VERSION_1           ProtoVersion = 1 // DeviceTelemetry roots, no Envelope
)

// Enum value maps for ProtoVersion.
var (
	ProtoVersion_name = map[int32]string{
		0: "PROTO_VERSION_UNSPECIFIED",
		1: "PROTO_VERSION_1",
	}
	ProtoVersion_value = map[string]int32{
		"PROTO_VERSION_UNSPECIFIED": 0,
		"PROTO_VERSION_1":           1,
	}
)

func (x ProtoVersion) Enum() *ProtoVersion {
	p := new(ProtoVersion)
	*p = x
	return p
}

func (x ProtoVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_d_common_v1_proto_enumTypes[0].Descriptor()
}

func (ProtoVersion) Type() protoreflect.EnumType {
	return &file_shared_d_common_v1_proto_enumTypes[0]
}

func (x ProtoVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoVersion.Descriptor instead.
func (ProtoVersion) EnumDescriptor() ([]byte, []int) {
	return file_shared_d_common_v1_proto_rawDescGZIP(), []int{0}
}

type CommandHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CreatedAt     uint32                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	ExpireAt      uint32                 `protobuf:"varint,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`    // unix seconds, 0 = never
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandHeader) Reset() {
	*x = CommandHeader{}
	mi := &file_shared_d_common_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandHeader) ProtoMessage() {}

func (x *CommandHeader) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_common_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandHeader.ProtoReflect.Descriptor instead.
func (*CommandHeader) Descriptor() ([]byte, []int) {
	return file_shared_d_common_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CommandHeader) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandHeader) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommandHeader) GetExpireAt() uint32 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

var File_shared_d_common_v1_proto protoreflect.FileDescriptor

const file_shared_d_common_v1_proto_rawDesc = "" +
	"\n" +
	"\x18shared_d_common_v1.proto\x12\x06device\"j\n" +
	"\rCommandHeader\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\rR\tcreatedAt\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\rR\bexpireAt*B\n" +
	"\fProtoVersion\x12\x1d\n" +
	"\x19PROTO_VERSION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROTO_VERSION_1\x10\x01BBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_shared_d_common_v1_proto_rawDescOnce sync.Once
	file_shared_d_common_v1_proto_rawDescData []byte
)

func file_shared_d_common_v1_proto_rawDescGZIP() []byte {
	file_shared_d_common_v1_proto_rawDescOnce.Do(func() {
		file_shared_d_common_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_d_common_v1_proto_rawDesc), len(file_shared_d_common_v1_proto_rawDesc)))
	})
	return file_shared_d_common_v1_proto_rawDescData
}

var file_shared_d_common_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_d_common_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_d_common_v1_proto_goTypes = []any{
	(ProtoVersion)(0),     // 0: device.ProtoVersion
	(*CommandHeader)(nil), // 1: device.CommandHeader
}
var file_shared_d_common_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_d_common_v1_proto_init() }
func file_shared_d_common_v1_proto_init() {
	if File_shared_d_common_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_d_common_v1_proto_rawDesc), len(file_shared_d_common_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_d_common_v1_proto_goTypes,
		DependencyIndexes: file_shared_d_common_v1_proto_depIdxs,
		EnumInfos:         file_shared_d_common_v1_proto_enumTypes,
		MessageInfos:      file_shared_d_common_v1_proto_msgTypes,
	}.Build()
	File_shared_d_common_v1_proto = out.File
	file_shared_d_common_v1_proto_goTypes = nil
	file_shared_d_common_v1_proto_depIdxs = nil
}
