// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shared_device_metric_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageKind int32

const (
	MessageKind_KIND_UNSPECIFIED  MessageKind = 0
	MessageKind_TELEMETRY_GPS     MessageKind = 1
	MessageKind_DEVICE_IDENTITY   MessageKind = 2
	MessageKind_FOTA_STATUS       MessageKind = 3
	MessageKind_COMMAND_ACK       MessageKind = 4 // CommandResponse on wire
	MessageKind_TELEMETRY_VEHICLE MessageKind = 5 // VehicleStatus on ingest/telemetry/vehicle
	MessageKind_CONFIG            MessageKind = 10
	MessageKind_COMMAND           MessageKind = 11
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0:  "KIND_UNSPECIFIED",
		1:  "TELEMETRY_GPS",
		2:  "DEVICE_IDENTITY",
		3:  "FOTA_STATUS",
		4:  "COMMAND_ACK",
		5:  "TELEMETRY_VEHICLE",
		10: "CONFIG",
		11: "COMMAND",
	}
	MessageKind_value = map[string]int32{
		"KIND_UNSPECIFIED":  0,
		"TELEMETRY_GPS":     1,
		"DEVICE_IDENTITY":   2,
		"FOTA_STATUS":       3,
		"COMMAND_ACK":       4,
		"TELEMETRY_VEHICLE": 5,
		"CONFIG":            10,
		"COMMAND":           11,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_device_metric_v1_proto_enumTypes[0].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_shared_device_metric_v1_proto_enumTypes[0]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{0}
}

type CommandStatus int32

const (
	CommandStatus_CMD_UNSPECIFIED CommandStatus = 0
	CommandStatus_CMD_ACCEPTED    CommandStatus = 1 // long job queued (FOTA)
	CommandStatus_CMD_OK          CommandStatus = 2
	CommandStatus_CMD_FAILED      CommandStatus = 3
	CommandStatus_CMD_UNSUPPORTED CommandStatus = 4
	CommandStatus_CMD_EXPIRED     CommandStatus = 5
	CommandStatus_CMD_BUSY        CommandStatus = 6
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "CMD_UNSPECIFIED",
		1: "CMD_ACCEPTED",
		2: "CMD_OK",
		3: "CMD_FAILED",
		4: "CMD_UNSUPPORTED",
		5: "CMD_EXPIRED",
		6: "CMD_BUSY",
	}
	CommandStatus_value = map[string]int32{
		"CMD_UNSPECIFIED": 0,
		"CMD_ACCEPTED":    1,
		"CMD_OK":          2,
		"CMD_FAILED":      3,
		"CMD_UNSUPPORTED": 4,
		"CMD_EXPIRED":     5,
		"CMD_BUSY":        6,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_device_metric_v1_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_shared_device_metric_v1_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{1}
}

type CommandType int32

const (
	CommandType_CMD_TYPE_UNSPECIFIED CommandType = 0
	CommandType_CMD_ECHO             CommandType = 1
	CommandType_CMD_REBOOT           CommandType = 2
	CommandType_CMD_FOTA             CommandType = 3
	CommandType_CMD_GET_CONFIG       CommandType = 4
	CommandType_CMD_RELAY            CommandType = 5
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "CMD_TYPE_UNSPECIFIED",
		1: "CMD_ECHO",
		2: "CMD_REBOOT",
		3: "CMD_FOTA",
		4: "CMD_GET_CONFIG",
		5: "CMD_RELAY",
	}
	CommandType_value = map[string]int32{
		"CMD_TYPE_UNSPECIFIED": 0,
		"CMD_ECHO":             1,
		"CMD_REBOOT":           2,
		"CMD_FOTA":             3,
		"CMD_GET_CONFIG":       4,
		"CMD_RELAY":            5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_device_metric_v1_proto_enumTypes[2].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_shared_device_metric_v1_proto_enumTypes[2]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{2}
}

type FotaStatus_State int32

const (
	FotaStatus_IDLE        FotaStatus_State = 0
	FotaStatus_DOWNLOADING FotaStatus_State = 1
	FotaStatus_VERIFYING   FotaStatus_State = 2
	FotaStatus_APPLYING    FotaStatus_State = 3
	FotaStatus_SUCCESS     FotaStatus_State = 4
	FotaStatus_FAILED      FotaStatus_State = 5
)

// Enum value maps for FotaStatus_State.
var (
	FotaStatus_State_name = map[int32]string{
		0: "IDLE",
		1: "DOWNLOADING",
		2: "VERIFYING",
		3: "APPLYING",
		4: "SUCCESS",
		5: "FAILED",
	}
	FotaStatus_State_value = map[string]int32{
		"IDLE":        0,
		"DOWNLOADING": 1,
		"VERIFYING":   2,
		"APPLYING":    3,
		"SUCCESS":     4,
		"FAILED":      5,
	}
)

func (x FotaStatus_State) Enum() *FotaStatus_State {
	p := new(FotaStatus_State)
	*p = x
	return p
}

func (x FotaStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FotaStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_device_metric_v1_proto_enumTypes[3].Descriptor()
}

func (FotaStatus_State) Type() protoreflect.EnumType {
	return &file_shared_device_metric_v1_proto_enumTypes[3]
}

func (x FotaStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FotaStatus_State.Descriptor instead.
func (FotaStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{20, 0}
}

type GpsSatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prn           uint32                 `protobuf:"varint,1,opt,name=prn,proto3" json:"prn,omitempty"`
	Elev          int32                  `protobuf:"zigzag32,2,opt,name=elev,proto3" json:"elev,omitempty"`
	Azim          uint32                 `protobuf:"varint,3,opt,name=azim,proto3" json:"azim,omitempty"`
	Snr           uint32                 `protobuf:"varint,4,opt,name=snr,proto3" json:"snr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsSatInfo) Reset() {
	*x = GpsSatInfo{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsSatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsSatInfo) ProtoMessage() {}

func (x *GpsSatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsSatInfo.ProtoReflect.Descriptor instead.
func (*GpsSatInfo) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GpsSatInfo) GetPrn() uint32 {
	if x != nil {
		return x.Prn
	}
	return 0
}

func (x *GpsSatInfo) GetElev() int32 {
	if x != nil {
		return x.Elev
	}
	return 0
}

func (x *GpsSatInfo) GetAzim() uint32 {
	if x != nil {
		return x.Azim
	}
	return 0
}

func (x *GpsSatInfo) GetSnr() uint32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

type GpsTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float32                `protobuf:"fixed32,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Spd           float32                `protobuf:"fixed32,4,opt,name=spd,proto3" json:"spd,omitempty"`
	Hdop          float32                `protobuf:"fixed32,5,opt,name=hdop,proto3" json:"hdop,omitempty"`
	Valid         bool                   `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	Satellites    uint32                 `protobuf:"varint,7,opt,name=satellites,proto3" json:"satellites,omitempty"` // GGA tracked count (legacy)
	Pdop          float32                `protobuf:"fixed32,8,opt,name=pdop,proto3" json:"pdop,omitempty"`
	AvgCnr        uint32                 `protobuf:"varint,9,opt,name=avg_cnr,json=avgCnr,proto3" json:"avg_cnr,omitempty"`
	Quality       uint32                 `protobuf:"varint,10,opt,name=quality,proto3" json:"quality,omitempty"`
	Navmode       uint32                 `protobuf:"varint,11,opt,name=navmode,proto3" json:"navmode,omitempty"`
	Heading       float32                `protobuf:"fixed32,12,opt,name=heading,proto3" json:"heading,omitempty"`                          // RMC course over ground, degrees
	SatsInView    uint32                 `protobuf:"varint,13,opt,name=sats_in_view,json=satsInView,proto3" json:"sats_in_view,omitempty"` // GSV structured count
	SatsUsed      uint32                 `protobuf:"varint,14,opt,name=sats_used,json=satsUsed,proto3" json:"sats_used,omitempty"`         // GSA used-PRN count
	UsedPrns      []uint32               `protobuf:"varint,15,rep,packed,name=used_prns,json=usedPrns,proto3" json:"used_prns,omitempty"`
	Sats          []*GpsSatInfo          `protobuf:"bytes,16,rep,name=sats,proto3" json:"sats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsTelemetry) Reset() {
	*x = GpsTelemetry{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsTelemetry) ProtoMessage() {}

func (x *GpsTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsTelemetry.ProtoReflect.Descriptor instead.
func (*GpsTelemetry) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GpsTelemetry) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GpsTelemetry) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GpsTelemetry) GetAlt() float32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *GpsTelemetry) GetSpd() float32 {
	if x != nil {
		return x.Spd
	}
	return 0
}

func (x *GpsTelemetry) GetHdop() float32 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *GpsTelemetry) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GpsTelemetry) GetSatellites() uint32 {
	if x != nil {
		return x.Satellites
	}
	return 0
}

func (x *GpsTelemetry) GetPdop() float32 {
	if x != nil {
		return x.Pdop
	}
	return 0
}

func (x *GpsTelemetry) GetAvgCnr() uint32 {
	if x != nil {
		return x.AvgCnr
	}
	return 0
}

func (x *GpsTelemetry) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *GpsTelemetry) GetNavmode() uint32 {
	if x != nil {
		return x.Navmode
	}
	return 0
}

func (x *GpsTelemetry) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *GpsTelemetry) GetSatsInView() uint32 {
	if x != nil {
		return x.SatsInView
	}
	return 0
}

func (x *GpsTelemetry) GetSatsUsed() uint32 {
	if x != nil {
		return x.SatsUsed
	}
	return 0
}

func (x *GpsTelemetry) GetUsedPrns() []uint32 {
	if x != nil {
		return x.UsedPrns
	}
	return nil
}

func (x *GpsTelemetry) GetSats() []*GpsSatInfo {
	if x != nil {
		return x.Sats
	}
	return nil
}

// Vehicle I/O on ingest/telemetry/vehicle (separate from GPS).
// last_shock_at is sticky unix seconds (0 = never); notify when it increases.
// Device always sets presence (nanopb OPTIONAL) so false/0 still appear on wire.
type VehicleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccActive     *bool                  `protobuf:"varint,1,opt,name=acc_active,json=accActive,proto3,oneof" json:"acc_active,omitempty"`    // ACC=1 active
	DoorActive    *bool                  `protobuf:"varint,2,opt,name=door_active,json=doorActive,proto3,oneof" json:"door_active,omitempty"` // door signal active (active-low pin)
	ShockLevel    *bool                  `protobuf:"varint,3,opt,name=shock_level,json=shockLevel,proto3,oneof" json:"shock_level,omitempty"` // current shock pin level
	RelayOn       *bool                  `protobuf:"varint,4,opt,name=relay_on,json=relayOn,proto3,oneof" json:"relay_on,omitempty"`
	BatMv         *uint32                `protobuf:"varint,5,opt,name=bat_mv,json=batMv,proto3,oneof" json:"bat_mv,omitempty"`
	LastShockAt   *uint32                `protobuf:"varint,6,opt,name=last_shock_at,json=lastShockAt,proto3,oneof" json:"last_shock_at,omitempty"`
	ReportedAt    *uint32                `protobuf:"varint,7,opt,name=reported_at,json=reportedAt,proto3,oneof" json:"reported_at,omitempty"` // unix sec of this sample; always set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleStatus) Reset() {
	*x = VehicleStatus{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatus) ProtoMessage() {}

func (x *VehicleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleStatus.ProtoReflect.Descriptor instead.
func (*VehicleStatus) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleStatus) GetAccActive() bool {
	if x != nil && x.AccActive != nil {
		return *x.AccActive
	}
	return false
}

func (x *VehicleStatus) GetDoorActive() bool {
	if x != nil && x.DoorActive != nil {
		return *x.DoorActive
	}
	return false
}

func (x *VehicleStatus) GetShockLevel() bool {
	if x != nil && x.ShockLevel != nil {
		return *x.ShockLevel
	}
	return false
}

func (x *VehicleStatus) GetRelayOn() bool {
	if x != nil && x.RelayOn != nil {
		return *x.RelayOn
	}
	return false
}

func (x *VehicleStatus) GetBatMv() uint32 {
	if x != nil && x.BatMv != nil {
		return *x.BatMv
	}
	return 0
}

func (x *VehicleStatus) GetLastShockAt() uint32 {
	if x != nil && x.LastShockAt != nil {
		return *x.LastShockAt
	}
	return 0
}

func (x *VehicleStatus) GetReportedAt() uint32 {
	if x != nil && x.ReportedAt != nil {
		return *x.ReportedAt
	}
	return 0
}

type DeviceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Imei          string                 `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	CpuUid        string                 `protobuf:"bytes,4,opt,name=cpu_uid,json=cpuUid,proto3" json:"cpu_uid,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	FwVersion     string                 `protobuf:"bytes,6,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIdentity) Reset() {
	*x = DeviceIdentity{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIdentity) ProtoMessage() {}

func (x *DeviceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIdentity.ProtoReflect.Descriptor instead.
func (*DeviceIdentity) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceIdentity) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceIdentity) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceIdentity) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceIdentity) GetCpuUid() string {
	if x != nil {
		return x.CpuUid
	}
	return ""
}

func (x *DeviceIdentity) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceIdentity) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

type CommandHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CreatedAt     uint32                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	ExpireAt      uint32                 `protobuf:"varint,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`    // unix seconds, 0 = never
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandHeader) Reset() {
	*x = CommandHeader{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandHeader) ProtoMessage() {}

func (x *CommandHeader) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandHeader.ProtoReflect.Descriptor instead.
func (*CommandHeader) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{4}
}

func (x *CommandHeader) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandHeader) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommandHeader) GetExpireAt() uint32 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type EchoParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoParams) Reset() {
	*x = EchoParams{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoParams) ProtoMessage() {}

func (x *EchoParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoParams.ProtoReflect.Descriptor instead.
func (*EchoParams) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{5}
}

func (x *EchoParams) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RebootParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMs       uint32                 `protobuf:"varint,1,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootParams) Reset() {
	*x = RebootParams{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootParams) ProtoMessage() {}

func (x *RebootParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootParams.ProtoReflect.Descriptor instead.
func (*RebootParams) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{6}
}

func (x *RebootParams) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type FotaParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageUrl    string                 `protobuf:"bytes,1,opt,name=package_url,json=packageUrl,proto3" json:"package_url,omitempty"`
	TargetVersion string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"` // exactly 32 bytes; required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FotaParams) Reset() {
	*x = FotaParams{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FotaParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FotaParams) ProtoMessage() {}

func (x *FotaParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FotaParams.ProtoReflect.Descriptor instead.
func (*FotaParams) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{7}
}

func (x *FotaParams) GetPackageUrl() string {
	if x != nil {
		return x.PackageUrl
	}
	return ""
}

func (x *FotaParams) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *FotaParams) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *FotaParams) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// Which blocks to return. All false => return every known block.
type GetConfigParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       bool                   `protobuf:"varint,1,opt,name=network,proto3" json:"network,omitempty"`
	Sms           bool                   `protobuf:"varint,2,opt,name=sms,proto3" json:"sms,omitempty"`
	Gps           bool                   `protobuf:"varint,3,opt,name=gps,proto3" json:"gps,omitempty"`
	Logging       bool                   `protobuf:"varint,4,opt,name=logging,proto3" json:"logging,omitempty"`
	Vehicle       bool                   `protobuf:"varint,5,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigParams) Reset() {
	*x = GetConfigParams{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigParams) ProtoMessage() {}

func (x *GetConfigParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigParams.ProtoReflect.Descriptor instead.
func (*GetConfigParams) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetConfigParams) GetNetwork() bool {
	if x != nil {
		return x.Network
	}
	return false
}

func (x *GetConfigParams) GetSms() bool {
	if x != nil {
		return x.Sms
	}
	return false
}

func (x *GetConfigParams) GetGps() bool {
	if x != nil {
		return x.Gps
	}
	return false
}

func (x *GetConfigParams) GetLogging() bool {
	if x != nil {
		return x.Logging
	}
	return false
}

func (x *GetConfigParams) GetVehicle() bool {
	if x != nil {
		return x.Vehicle
	}
	return false
}

type RelayParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	On            bool                   `protobuf:"varint,1,opt,name=on,proto3" json:"on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayParams) Reset() {
	*x = RelayParams{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayParams) ProtoMessage() {}

func (x *RelayParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayParams.ProtoReflect.Descriptor instead.
func (*RelayParams) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{9}
}

func (x *RelayParams) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

type DeviceCommand struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *CommandHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type   CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=device_metric_v1.CommandType" json:"type,omitempty"`
	// Serialized EchoParams | RebootParams | FotaParams | GetConfigParams
	Params        []byte `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCommand) Reset() {
	*x = DeviceCommand{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommand) ProtoMessage() {}

func (x *DeviceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommand.ProtoReflect.Descriptor instead.
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{10}
}

func (x *DeviceCommand) GetHeader() *CommandHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeviceCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_CMD_TYPE_UNSPECIFIED
}

func (x *DeviceCommand) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type GpsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUnfixed   bool                   `protobuf:"varint,1,opt,name=post_unfixed,json=postUnfixed,proto3" json:"post_unfixed,omitempty"`
	FieldMask     uint32                 `protobuf:"varint,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsConfig) Reset() {
	*x = GpsConfig{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsConfig) ProtoMessage() {}

func (x *GpsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsConfig.ProtoReflect.Descriptor instead.
func (*GpsConfig) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{11}
}

func (x *GpsConfig) GetPostUnfixed() bool {
	if x != nil {
		return x.PostUnfixed
	}
	return false
}

func (x *GpsConfig) GetFieldMask() uint32 {
	if x != nil {
		return x.FieldMask
	}
	return 0
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apn           string                 `protobuf:"bytes,1,opt,name=apn,proto3" json:"apn,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pass          string                 `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkConfig) GetApn() string {
	if x != nil {
		return x.Apn
	}
	return ""
}

func (x *NetworkConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *NetworkConfig) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type SmsRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"` // E.164, e.g. "+989123456789"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsRecipient) Reset() {
	*x = SmsRecipient{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsRecipient) ProtoMessage() {}

func (x *SmsRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsRecipient.ProtoReflect.Descriptor instead.
func (*SmsRecipient) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{13}
}

func (x *SmsRecipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SmsRecipient) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

// Shared templates + per-event enables. Replaces legacy SmsConfig on the wire
// (same DeviceConfiguration.sms / DeviceConfigurationUpdate.sms field numbers).
type SmsNotificationConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recipients      []*SmsRecipient        `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"` // max 5 (nanopb STATIC)
	Enabled         bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`      // master switch
	EnableShock     bool                   `protobuf:"varint,3,opt,name=enable_shock,json=enableShock,proto3" json:"enable_shock,omitempty"`
	EnableAccOn     bool                   `protobuf:"varint,4,opt,name=enable_acc_on,json=enableAccOn,proto3" json:"enable_acc_on,omitempty"`
	EnableAccOff    bool                   `protobuf:"varint,5,opt,name=enable_acc_off,json=enableAccOff,proto3" json:"enable_acc_off,omitempty"`
	EnableDoorOpen  bool                   `protobuf:"varint,6,opt,name=enable_door_open,json=enableDoorOpen,proto3" json:"enable_door_open,omitempty"`
	EnableDoorClose bool                   `protobuf:"varint,7,opt,name=enable_door_close,json=enableDoorClose,proto3" json:"enable_door_close,omitempty"`
	MsgShock        string                 `protobuf:"bytes,8,opt,name=msg_shock,json=msgShock,proto3" json:"msg_shock,omitempty"`
	MsgAccOn        string                 `protobuf:"bytes,9,opt,name=msg_acc_on,json=msgAccOn,proto3" json:"msg_acc_on,omitempty"`
	MsgAccOff       string                 `protobuf:"bytes,10,opt,name=msg_acc_off,json=msgAccOff,proto3" json:"msg_acc_off,omitempty"`
	MsgDoorOpen     string                 `protobuf:"bytes,11,opt,name=msg_door_open,json=msgDoorOpen,proto3" json:"msg_door_open,omitempty"`
	MsgDoorClose    string                 `protobuf:"bytes,12,opt,name=msg_door_close,json=msgDoorClose,proto3" json:"msg_door_close,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SmsNotificationConfig) Reset() {
	*x = SmsNotificationConfig{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationConfig) ProtoMessage() {}

func (x *SmsNotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationConfig.ProtoReflect.Descriptor instead.
func (*SmsNotificationConfig) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{14}
}

func (x *SmsNotificationConfig) GetRecipients() []*SmsRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SmsNotificationConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableShock() bool {
	if x != nil {
		return x.EnableShock
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableAccOn() bool {
	if x != nil {
		return x.EnableAccOn
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableAccOff() bool {
	if x != nil {
		return x.EnableAccOff
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableDoorOpen() bool {
	if x != nil {
		return x.EnableDoorOpen
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableDoorClose() bool {
	if x != nil {
		return x.EnableDoorClose
	}
	return false
}

func (x *SmsNotificationConfig) GetMsgShock() string {
	if x != nil {
		return x.MsgShock
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgAccOn() string {
	if x != nil {
		return x.MsgAccOn
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgAccOff() string {
	if x != nil {
		return x.MsgAccOff
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgDoorOpen() string {
	if x != nil {
		return x.MsgDoorOpen
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgDoorClose() string {
	if x != nil {
		return x.MsgDoorClose
	}
	return ""
}

type LoggingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingConfig) Reset() {
	*x = LoggingConfig{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingConfig) ProtoMessage() {}

func (x *LoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingConfig.ProtoReflect.Descriptor instead.
func (*LoggingConfig) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{15}
}

func (x *LoggingConfig) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type VehicleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostPeriodMs  uint32                 `protobuf:"varint,1,opt,name=post_period_ms,json=postPeriodMs,proto3" json:"post_period_ms,omitempty"` // vehicle status uplink interval (default 1000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleConfig) Reset() {
	*x = VehicleConfig{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleConfig) ProtoMessage() {}

func (x *VehicleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleConfig.ProtoReflect.Descriptor instead.
func (*VehicleConfig) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{16}
}

func (x *VehicleConfig) GetPostPeriodMs() uint32 {
	if x != nil {
		return x.PostPeriodMs
	}
	return 0
}

// Full/partial snapshot of current settings (read path).
type DeviceConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *NetworkConfig         `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Sms           *SmsNotificationConfig `protobuf:"bytes,2,opt,name=sms,proto3" json:"sms,omitempty"`
	Gps           *GpsConfig             `protobuf:"bytes,3,opt,name=gps,proto3" json:"gps,omitempty"`
	Logging       *LoggingConfig         `protobuf:"bytes,4,opt,name=logging,proto3" json:"logging,omitempty"`
	Vehicle       *VehicleConfig         `protobuf:"bytes,6,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfiguration) Reset() {
	*x = DeviceConfiguration{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfiguration) ProtoMessage() {}

func (x *DeviceConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfiguration.ProtoReflect.Descriptor instead.
func (*DeviceConfiguration) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{17}
}

func (x *DeviceConfiguration) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *DeviceConfiguration) GetSms() *SmsNotificationConfig {
	if x != nil {
		return x.Sms
	}
	return nil
}

func (x *DeviceConfiguration) GetGps() *GpsConfig {
	if x != nil {
		return x.Gps
	}
	return nil
}

func (x *DeviceConfiguration) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *DeviceConfiguration) GetVehicle() *VehicleConfig {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

// Patch settings (write path). Same blocks; omit = leave unchanged.
type DeviceConfigurationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CommandHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Network       *NetworkConfig         `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Sms           *SmsNotificationConfig `protobuf:"bytes,3,opt,name=sms,proto3" json:"sms,omitempty"`
	Gps           *GpsConfig             `protobuf:"bytes,4,opt,name=gps,proto3" json:"gps,omitempty"`
	Logging       *LoggingConfig         `protobuf:"bytes,5,opt,name=logging,proto3" json:"logging,omitempty"`
	Vehicle       *VehicleConfig         `protobuf:"bytes,6,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigurationUpdate) Reset() {
	*x = DeviceConfigurationUpdate{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigurationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigurationUpdate) ProtoMessage() {}

func (x *DeviceConfigurationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigurationUpdate.ProtoReflect.Descriptor instead.
func (*DeviceConfigurationUpdate) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{18}
}

func (x *DeviceConfigurationUpdate) GetHeader() *CommandHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetSms() *SmsNotificationConfig {
	if x != nil {
		return x.Sms
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetGps() *GpsConfig {
	if x != nil {
		return x.Gps
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetVehicle() *VehicleConfig {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type CommandResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Header    *CommandHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status    CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=device_metric_v1.CommandStatus" json:"status,omitempty"`
	ErrorCode uint32                 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CommandResponse_Config
	Result        isCommandResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{19}
}

func (x *CommandResponse) GetHeader() *CommandHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CommandResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_CMD_UNSPECIFIED
}

func (x *CommandResponse) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetResult() isCommandResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResponse) GetConfig() *DeviceConfiguration {
	if x != nil {
		if x, ok := x.Result.(*CommandResponse_Config); ok {
			return x.Config
		}
	}
	return nil
}

type isCommandResponse_Result interface {
	isCommandResponse_Result()
}

type CommandResponse_Config struct {
	Config *DeviceConfiguration `protobuf:"bytes,10,opt,name=config,proto3,oneof"`
}

func (*CommandResponse_Config) isCommandResponse_Result() {}

type FotaStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           FotaStatus_State       `protobuf:"varint,1,opt,name=state,proto3,enum=device_metric_v1.FotaStatus_State" json:"state,omitempty"`
	ProgressPercent uint32                 `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Detail          string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	CurrentVersion  string                 `protobuf:"bytes,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	TargetVersion   string                 `protobuf:"bytes,5,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	CommandId       string                 `protobuf:"bytes,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FotaStatus) Reset() {
	*x = FotaStatus{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FotaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FotaStatus) ProtoMessage() {}

func (x *FotaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FotaStatus.ProtoReflect.Descriptor instead.
func (*FotaStatus) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{20}
}

func (x *FotaStatus) GetState() FotaStatus_State {
	if x != nil {
		return x.State
	}
	return FotaStatus_IDLE
}

func (x *FotaStatus) GetProgressPercent() uint32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *FotaStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *FotaStatus) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *FotaStatus) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *FotaStatus) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp uint32                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Seq       uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Kind      MessageKind            `protobuf:"varint,3,opt,name=kind,proto3,enum=device_metric_v1.MessageKind" json:"kind,omitempty"`
	Identity  *DeviceIdentity        `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	// Serialized inner message selected by kind (GpsTelemetry, DeviceCommand, …).
	Body          []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_shared_device_metric_v1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_shared_device_metric_v1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_shared_device_metric_v1_proto_rawDescGZIP(), []int{21}
}

func (x *Envelope) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_KIND_UNSPECIFIED
}

func (x *Envelope) GetIdentity() *DeviceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Envelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_shared_device_metric_v1_proto protoreflect.FileDescriptor

const file_shared_device_metric_v1_proto_rawDesc = "" +
	"\n" +
	"\x1dshared_device_metric_v1.proto\x12\x10device_metric_v1\"X\n" +
	"\n" +
	"GpsSatInfo\x12\x10\n" +
	"\x03prn\x18\x01 \x01(\rR\x03prn\x12\x12\n" +
	"\x04elev\x18\x02 \x01(\x11R\x04elev\x12\x12\n" +
	"\x04azim\x18\x03 \x01(\rR\x04azim\x12\x10\n" +
	"\x03snr\x18\x04 \x01(\rR\x03snr\"\xa9\x03\n" +
	"\fGpsTelemetry\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x02R\x03alt\x12\x10\n" +
	"\x03spd\x18\x04 \x01(\x02R\x03spd\x12\x12\n" +
	"\x04hdop\x18\x05 \x01(\x02R\x04hdop\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\bR\x05valid\x12\x1e\n" +
	"\n" +
	"satellites\x18\a \x01(\rR\n" +
	"satellites\x12\x12\n" +
	"\x04pdop\x18\b \x01(\x02R\x04pdop\x12\x17\n" +
	"\aavg_cnr\x18\t \x01(\rR\x06avgCnr\x12\x18\n" +
	"\aquality\x18\n" +
	" \x01(\rR\aquality\x12\x18\n" +
	"\anavmode\x18\v \x01(\rR\anavmode\x12\x18\n" +
	"\aheading\x18\f \x01(\x02R\aheading\x12 \n" +
	"\fsats_in_view\x18\r \x01(\rR\n" +
	"satsInView\x12\x1b\n" +
	"\tsats_used\x18\x0e \x01(\rR\bsatsUsed\x12\x1b\n" +
	"\tused_prns\x18\x0f \x03(\rR\busedPrns\x120\n" +
	"\x04sats\x18\x10 \x03(\v2\x1c.device_metric_v1.GpsSatInfoR\x04sats\"\xf3\x02\n" +
	"\rVehicleStatus\x12\"\n" +
	"\n" +
	"acc_active\x18\x01 \x01(\bH\x00R\taccActive\x88\x01\x01\x12$\n" +
	"\vdoor_active\x18\x02 \x01(\bH\x01R\n" +
	"doorActive\x88\x01\x01\x12$\n" +
	"\vshock_level\x18\x03 \x01(\bH\x02R\n" +
	"shockLevel\x88\x01\x01\x12\x1e\n" +
	"\brelay_on\x18\x04 \x01(\bH\x03R\arelayOn\x88\x01\x01\x12\x1a\n" +
	"\x06bat_mv\x18\x05 \x01(\rH\x04R\x05batMv\x88\x01\x01\x12'\n" +
	"\rlast_shock_at\x18\x06 \x01(\rH\x05R\vlastShockAt\x88\x01\x01\x12$\n" +
	"\vreported_at\x18\a \x01(\rH\x06R\n" +
	"reportedAt\x88\x01\x01B\r\n" +
	"\v_acc_activeB\x0e\n" +
	"\f_door_activeB\x0e\n" +
	"\f_shock_levelB\v\n" +
	"\t_relay_onB\t\n" +
	"\a_bat_mvB\x10\n" +
	"\x0e_last_shock_atB\x0e\n" +
	"\f_reported_at\"\xa7\x01\n" +
	"\x0eDeviceIdentity\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04imei\x18\x02 \x01(\tR\x04imei\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x17\n" +
	"\acpu_uid\x18\x04 \x01(\tR\x06cpuUid\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x06 \x01(\tR\tfwVersion\"j\n" +
	"\rCommandHeader\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\rR\tcreatedAt\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\rR\bexpireAt\"&\n" +
	"\n" +
	"EchoParams\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\fRebootParams\x12\x19\n" +
	"\bdelay_ms\x18\x01 \x01(\rR\adelayMs\"\x82\x01\n" +
	"\n" +
	"FotaParams\x12\x1f\n" +
	"\vpackage_url\x18\x01 \x01(\tR\n" +
	"packageUrl\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\"\x83\x01\n" +
	"\x0fGetConfigParams\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\bR\anetwork\x12\x10\n" +
	"\x03sms\x18\x02 \x01(\bR\x03sms\x12\x10\n" +
	"\x03gps\x18\x03 \x01(\bR\x03gps\x12\x18\n" +
	"\alogging\x18\x04 \x01(\bR\alogging\x12\x18\n" +
	"\avehicle\x18\x05 \x01(\bR\avehicle\"\x1d\n" +
	"\vRelayParams\x12\x0e\n" +
	"\x02on\x18\x01 \x01(\bR\x02on\"\x93\x01\n" +
	"\rDeviceCommand\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.device_metric_v1.CommandHeaderR\x06header\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.device_metric_v1.CommandTypeR\x04type\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\"M\n" +
	"\tGpsConfig\x12!\n" +
	"\fpost_unfixed\x18\x01 \x01(\bR\vpostUnfixed\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\rR\tfieldMask\"I\n" +
	"\rNetworkConfig\x12\x10\n" +
	"\x03apn\x18\x01 \x01(\tR\x03apn\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04pass\x18\x03 \x01(\tR\x04pass\":\n" +
	"\fSmsRecipient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"\xd9\x03\n" +
	"\x15SmsNotificationConfig\x12>\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x1e.device_metric_v1.SmsRecipientR\n" +
	"recipients\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12!\n" +
	"\fenable_shock\x18\x03 \x01(\bR\venableShock\x12\"\n" +
	"\renable_acc_on\x18\x04 \x01(\bR\venableAccOn\x12$\n" +
	"\x0eenable_acc_off\x18\x05 \x01(\bR\fenableAccOff\x12(\n" +
	"\x10enable_door_open\x18\x06 \x01(\bR\x0eenableDoorOpen\x12*\n" +
	"\x11enable_door_close\x18\a \x01(\bR\x0fenableDoorClose\x12\x1b\n" +
	"\tmsg_shock\x18\b \x01(\tR\bmsgShock\x12\x1c\n" +
	"\n" +
	"msg_acc_on\x18\t \x01(\tR\bmsgAccOn\x12\x1e\n" +
	"\vmsg_acc_off\x18\n" +
	" \x01(\tR\tmsgAccOff\x12\"\n" +
	"\rmsg_door_open\x18\v \x01(\tR\vmsgDoorOpen\x12$\n" +
	"\x0emsg_door_close\x18\f \x01(\tR\fmsgDoorClose\"%\n" +
	"\rLoggingConfig\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\"5\n" +
	"\rVehicleConfig\x12$\n" +
	"\x0epost_period_ms\x18\x01 \x01(\rR\fpostPeriodMs\"\xb0\x02\n" +
	"\x13DeviceConfiguration\x129\n" +
	"\anetwork\x18\x01 \x01(\v2\x1f.device_metric_v1.NetworkConfigR\anetwork\x129\n" +
	"\x03sms\x18\x02 \x01(\v2'.device_metric_v1.SmsNotificationConfigR\x03sms\x12-\n" +
	"\x03gps\x18\x03 \x01(\v2\x1b.device_metric_v1.GpsConfigR\x03gps\x129\n" +
	"\alogging\x18\x04 \x01(\v2\x1f.device_metric_v1.LoggingConfigR\alogging\x129\n" +
	"\avehicle\x18\x06 \x01(\v2\x1f.device_metric_v1.VehicleConfigR\avehicle\"\xef\x02\n" +
	"\x19DeviceConfigurationUpdate\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.device_metric_v1.CommandHeaderR\x06header\x129\n" +
	"\anetwork\x18\x02 \x01(\v2\x1f.device_metric_v1.NetworkConfigR\anetwork\x129\n" +
	"\x03sms\x18\x03 \x01(\v2'.device_metric_v1.SmsNotificationConfigR\x03sms\x12-\n" +
	"\x03gps\x18\x04 \x01(\v2\x1b.device_metric_v1.GpsConfigR\x03gps\x129\n" +
	"\alogging\x18\x05 \x01(\v2\x1f.device_metric_v1.LoggingConfigR\alogging\x129\n" +
	"\avehicle\x18\x06 \x01(\v2\x1f.device_metric_v1.VehicleConfigR\avehicle\"\x87\x02\n" +
	"\x0fCommandResponse\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.device_metric_v1.CommandHeaderR\x06header\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.device_metric_v1.CommandStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\rR\terrorCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12?\n" +
	"\x06config\x18\n" +
	" \x01(\v2%.device_metric_v1.DeviceConfigurationH\x00R\x06configB\b\n" +
	"\x06result\"\xd2\x02\n" +
	"\n" +
	"FotaStatus\x128\n" +
	"\x05state\x18\x01 \x01(\x0e2\".device_metric_v1.FotaStatus.StateR\x05state\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\rR\x0fprogressPercent\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12'\n" +
	"\x0fcurrent_version\x18\x04 \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0etarget_version\x18\x05 \x01(\tR\rtargetVersion\x12\x1d\n" +
	"\n" +
	"command_id\x18\x06 \x01(\tR\tcommandId\"X\n" +
	"\x05State\x12\b\n" +
	"\x04IDLE\x10\x00\x12\x0f\n" +
	"\vDOWNLOADING\x10\x01\x12\r\n" +
	"\tVERIFYING\x10\x02\x12\f\n" +
	"\bAPPLYING\x10\x03\x12\v\n" +
	"\aSUCCESS\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\"\xbf\x01\n" +
	"\bEnvelope\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\rR\ttimestamp\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x121\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1d.device_metric_v1.MessageKindR\x04kind\x12<\n" +
	"\bidentity\x18\x04 \x01(\v2 .device_metric_v1.DeviceIdentityR\bidentity\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body*\x9d\x01\n" +
	"\vMessageKind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTELEMETRY_GPS\x10\x01\x12\x13\n" +
	"\x0fDEVICE_IDENTITY\x10\x02\x12\x0f\n" +
	"\vFOTA_STATUS\x10\x03\x12\x0f\n" +
	"\vCOMMAND_ACK\x10\x04\x12\x15\n" +
	"\x11TELEMETRY_VEHICLE\x10\x05\x12\n" +
	"\n" +
	"\x06CONFIG\x10\n" +
	"\x12\v\n" +
	"\aCOMMAND\x10\v*\x86\x01\n" +
	"\rCommandStatus\x12\x13\n" +
	"\x0fCMD_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCMD_ACCEPTED\x10\x01\x12\n" +
	"\n" +
	"\x06CMD_OK\x10\x02\x12\x0e\n" +
	"\n" +
	"CMD_FAILED\x10\x03\x12\x13\n" +
	"\x0fCMD_UNSUPPORTED\x10\x04\x12\x0f\n" +
	"\vCMD_EXPIRED\x10\x05\x12\f\n" +
	"\bCMD_BUSY\x10\x06*v\n" +
	"\vCommandType\x12\x18\n" +
	"\x14CMD_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCMD_ECHO\x10\x01\x12\x0e\n" +
	"\n" +
	"CMD_REBOOT\x10\x02\x12\f\n" +
	"\bCMD_FOTA\x10\x03\x12\x12\n" +
	"\x0eCMD_GET_CONFIG\x10\x04\x12\r\n" +
	"\tCMD_RELAY\x10\x05BBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_shared_device_metric_v1_proto_rawDescOnce sync.Once
	file_shared_device_metric_v1_proto_rawDescData []byte
)

func file_shared_device_metric_v1_proto_rawDescGZIP() []byte {
	file_shared_device_metric_v1_proto_rawDescOnce.Do(func() {
		file_shared_device_metric_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_device_metric_v1_proto_rawDesc), len(file_shared_device_metric_v1_proto_rawDesc)))
	})
	return file_shared_device_metric_v1_proto_rawDescData
}

var file_shared_device_metric_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_shared_device_metric_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_shared_device_metric_v1_proto_goTypes = []any{
	(MessageKind)(0),                  // 0: device_metric_v1.MessageKind
	(CommandStatus)(0),                // 1: device_metric_v1.CommandStatus
	(CommandType)(0),                  // 2: device_metric_v1.CommandType
	(FotaStatus_State)(0),             // 3: device_metric_v1.FotaStatus.State
	(*GpsSatInfo)(nil),                // 4: device_metric_v1.GpsSatInfo
	(*GpsTelemetry)(nil),              // 5: device_metric_v1.GpsTelemetry
	(*VehicleStatus)(nil),             // 6: device_metric_v1.VehicleStatus
	(*DeviceIdentity)(nil),            // 7: device_metric_v1.DeviceIdentity
	(*CommandHeader)(nil),             // 8: device_metric_v1.CommandHeader
	(*EchoParams)(nil),                // 9: device_metric_v1.EchoParams
	(*RebootParams)(nil),              // 10: device_metric_v1.RebootParams
	(*FotaParams)(nil),                // 11: device_metric_v1.FotaParams
	(*GetConfigParams)(nil),           // 12: device_metric_v1.GetConfigParams
	(*RelayParams)(nil),               // 13: device_metric_v1.RelayParams
	(*DeviceCommand)(nil),             // 14: device_metric_v1.DeviceCommand
	(*GpsConfig)(nil),                 // 15: device_metric_v1.GpsConfig
	(*NetworkConfig)(nil),             // 16: device_metric_v1.NetworkConfig
	(*SmsRecipient)(nil),              // 17: device_metric_v1.SmsRecipient
	(*SmsNotificationConfig)(nil),     // 18: device_metric_v1.SmsNotificationConfig
	(*LoggingConfig)(nil),             // 19: device_metric_v1.LoggingConfig
	(*VehicleConfig)(nil),             // 20: device_metric_v1.VehicleConfig
	(*DeviceConfiguration)(nil),       // 21: device_metric_v1.DeviceConfiguration
	(*DeviceConfigurationUpdate)(nil), // 22: device_metric_v1.DeviceConfigurationUpdate
	(*CommandResponse)(nil),           // 23: device_metric_v1.CommandResponse
	(*FotaStatus)(nil),                // 24: device_metric_v1.FotaStatus
	(*Envelope)(nil),                  // 25: device_metric_v1.Envelope
}
var file_shared_device_metric_v1_proto_depIdxs = []int32{
	4,  // 0: device_metric_v1.GpsTelemetry.sats:type_name -> device_metric_v1.GpsSatInfo
	8,  // 1: device_metric_v1.DeviceCommand.header:type_name -> device_metric_v1.CommandHeader
	2,  // 2: device_metric_v1.DeviceCommand.type:type_name -> device_metric_v1.CommandType
	17, // 3: device_metric_v1.SmsNotificationConfig.recipients:type_name -> device_metric_v1.SmsRecipient
	16, // 4: device_metric_v1.DeviceConfiguration.network:type_name -> device_metric_v1.NetworkConfig
	18, // 5: device_metric_v1.DeviceConfiguration.sms:type_name -> device_metric_v1.SmsNotificationConfig
	15, // 6: device_metric_v1.DeviceConfiguration.gps:type_name -> device_metric_v1.GpsConfig
	19, // 7: device_metric_v1.DeviceConfiguration.logging:type_name -> device_metric_v1.LoggingConfig
	20, // 8: device_metric_v1.DeviceConfiguration.vehicle:type_name -> device_metric_v1.VehicleConfig
	8,  // 9: device_metric_v1.DeviceConfigurationUpdate.header:type_name -> device_metric_v1.CommandHeader
	16, // 10: device_metric_v1.DeviceConfigurationUpdate.network:type_name -> device_metric_v1.NetworkConfig
	18, // 11: device_metric_v1.DeviceConfigurationUpdate.sms:type_name -> device_metric_v1.SmsNotificationConfig
	15, // 12: device_metric_v1.DeviceConfigurationUpdate.gps:type_name -> device_metric_v1.GpsConfig
	19, // 13: device_metric_v1.DeviceConfigurationUpdate.logging:type_name -> device_metric_v1.LoggingConfig
	20, // 14: device_metric_v1.DeviceConfigurationUpdate.vehicle:type_name -> device_metric_v1.VehicleConfig
	8,  // 15: device_metric_v1.CommandResponse.header:type_name -> device_metric_v1.CommandHeader
	1,  // 16: device_metric_v1.CommandResponse.status:type_name -> device_metric_v1.CommandStatus
	21, // 17: device_metric_v1.CommandResponse.config:type_name -> device_metric_v1.DeviceConfiguration
	3,  // 18: device_metric_v1.FotaStatus.state:type_name -> device_metric_v1.FotaStatus.State
	0,  // 19: device_metric_v1.Envelope.kind:type_name -> device_metric_v1.MessageKind
	7,  // 20: device_metric_v1.Envelope.identity:type_name -> device_metric_v1.DeviceIdentity
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_shared_device_metric_v1_proto_init() }
func file_shared_device_metric_v1_proto_init() {
	if File_shared_device_metric_v1_proto != nil {
		return
	}
	file_shared_device_metric_v1_proto_msgTypes[2].OneofWrappers = []any{}
	file_shared_device_metric_v1_proto_msgTypes[19].OneofWrappers = []any{
		(*CommandResponse_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_device_metric_v1_proto_rawDesc), len(file_shared_device_metric_v1_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_device_metric_v1_proto_goTypes,
		DependencyIndexes: file_shared_device_metric_v1_proto_depIdxs,
		EnumInfos:         file_shared_device_metric_v1_proto_enumTypes,
		MessageInfos:      file_shared_device_metric_v1_proto_msgTypes,
	}.Build()
	File_shared_device_metric_v1_proto = out.File
	file_shared_device_metric_v1_proto_goTypes = nil
	file_shared_device_metric_v1_proto_depIdxs = nil
}
