<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.CommandResponse</code>
 */
class CommandResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandStatus status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint32 error_code = 3;</code>
     */
    protected $error_code = 0;
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    protected $message = '';
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device_metric_v1\CommandHeader $header
     *     @type int $status
     *     @type int $error_code
     *     @type string $message
     *     @type \Device_metric_v1\DeviceConfiguration $config
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     * @return \Device_metric_v1\CommandHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     * @param \Device_metric_v1\CommandHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\CommandHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Device_metric_v1\CommandStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 error_code = 3;</code>
     * @return int
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>uint32 error_code = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.DeviceConfiguration config = 10;</code>
     * @return \Device_metric_v1\DeviceConfiguration|null
     */
    public function getConfig()
    {
        return $this->readOneof(10);
    }

    public function hasConfig()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.DeviceConfiguration config = 10;</code>
     * @param \Device_metric_v1\DeviceConfiguration $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\DeviceConfiguration::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

