<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.CommandHeader</code>
 */
class CommandHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     */
    protected $command_id = '';
    /**
     * unix seconds
     *
     * Generated from protobuf field <code>uint32 created_at = 2;</code>
     */
    protected $created_at = 0;
    /**
     * unix seconds, 0 = never
     *
     * Generated from protobuf field <code>uint32 expire_at = 3;</code>
     */
    protected $expire_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $command_id
     *     @type int $created_at
     *           unix seconds
     *     @type int $expire_at
     *           unix seconds, 0 = never
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     * @return string
     */
    public function getCommandId()
    {
        return $this->command_id;
    }

    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCommandId($var)
    {
        GPBUtil::checkString($var, True);
        $this->command_id = $var;

        return $this;
    }

    /**
     * unix seconds
     *
     * Generated from protobuf field <code>uint32 created_at = 2;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * unix seconds
     *
     * Generated from protobuf field <code>uint32 created_at = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * unix seconds, 0 = never
     *
     * Generated from protobuf field <code>uint32 expire_at = 3;</code>
     * @return int
     */
    public function getExpireAt()
    {
        return $this->expire_at;
    }

    /**
     * unix seconds, 0 = never
     *
     * Generated from protobuf field <code>uint32 expire_at = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setExpireAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->expire_at = $var;

        return $this;
    }

}

