<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.DeviceIdentity</code>
 */
class DeviceIdentity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>string imei = 2;</code>
     */
    protected $imei = '';
    /**
     * Generated from protobuf field <code>string serial = 3;</code>
     */
    protected $serial = '';
    /**
     * Generated from protobuf field <code>string cpu_uid = 4;</code>
     */
    protected $cpu_uid = '';
    /**
     * Generated from protobuf field <code>string model = 5;</code>
     */
    protected $model = '';
    /**
     * Generated from protobuf field <code>string fw_version = 6;</code>
     */
    protected $fw_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type string $imei
     *     @type string $serial
     *     @type string $cpu_uid
     *     @type string $model
     *     @type string $fw_version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imei = 2;</code>
     * @return string
     */
    public function getImei()
    {
        return $this->imei;
    }

    /**
     * Generated from protobuf field <code>string imei = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setImei($var)
    {
        GPBUtil::checkString($var, True);
        $this->imei = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serial = 3;</code>
     * @return string
     */
    public function getSerial()
    {
        return $this->serial;
    }

    /**
     * Generated from protobuf field <code>string serial = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSerial($var)
    {
        GPBUtil::checkString($var, True);
        $this->serial = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cpu_uid = 4;</code>
     * @return string
     */
    public function getCpuUid()
    {
        return $this->cpu_uid;
    }

    /**
     * Generated from protobuf field <code>string cpu_uid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCpuUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->cpu_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model = 5;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>string model = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fw_version = 6;</code>
     * @return string
     */
    public function getFwVersion()
    {
        return $this->fw_version;
    }

    /**
     * Generated from protobuf field <code>string fw_version = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFwVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->fw_version = $var;

        return $this;
    }

}

