<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Patch settings (write path). Same blocks; omit = leave unchanged.
 *
 * Generated from protobuf message <code>device_metric_v1.DeviceConfigurationUpdate</code>
 */
class DeviceConfigurationUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.NetworkConfig network = 2;</code>
     */
    protected $network = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.SmsConfig sms = 3;</code>
     */
    protected $sms = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.GpsConfig gps = 4;</code>
     */
    protected $gps = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.LoggingConfig logging = 5;</code>
     */
    protected $logging = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device_metric_v1\CommandHeader $header
     *     @type \Device_metric_v1\NetworkConfig $network
     *     @type \Device_metric_v1\SmsConfig $sms
     *     @type \Device_metric_v1\GpsConfig $gps
     *     @type \Device_metric_v1\LoggingConfig $logging
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     * @return \Device_metric_v1\CommandHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     * @param \Device_metric_v1\CommandHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\CommandHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.NetworkConfig network = 2;</code>
     * @return \Device_metric_v1\NetworkConfig|null
     */
    public function getNetwork()
    {
        return $this->network;
    }

    public function hasNetwork()
    {
        return isset($this->network);
    }

    public function clearNetwork()
    {
        unset($this->network);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.NetworkConfig network = 2;</code>
     * @param \Device_metric_v1\NetworkConfig $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\NetworkConfig::class);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.SmsConfig sms = 3;</code>
     * @return \Device_metric_v1\SmsConfig|null
     */
    public function getSms()
    {
        return $this->sms;
    }

    public function hasSms()
    {
        return isset($this->sms);
    }

    public function clearSms()
    {
        unset($this->sms);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.SmsConfig sms = 3;</code>
     * @param \Device_metric_v1\SmsConfig $var
     * @return $this
     */
    public function setSms($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\SmsConfig::class);
        $this->sms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.GpsConfig gps = 4;</code>
     * @return \Device_metric_v1\GpsConfig|null
     */
    public function getGps()
    {
        return $this->gps;
    }

    public function hasGps()
    {
        return isset($this->gps);
    }

    public function clearGps()
    {
        unset($this->gps);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.GpsConfig gps = 4;</code>
     * @param \Device_metric_v1\GpsConfig $var
     * @return $this
     */
    public function setGps($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\GpsConfig::class);
        $this->gps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.LoggingConfig logging = 5;</code>
     * @return \Device_metric_v1\LoggingConfig|null
     */
    public function getLogging()
    {
        return $this->logging;
    }

    public function hasLogging()
    {
        return isset($this->logging);
    }

    public function clearLogging()
    {
        unset($this->logging);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.LoggingConfig logging = 5;</code>
     * @param \Device_metric_v1\LoggingConfig $var
     * @return $this
     */
    public function setLogging($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\LoggingConfig::class);
        $this->logging = $var;

        return $this;
    }

}

