<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Full/partial snapshot of current settings (read path).
 *
 * Generated from protobuf message <code>device_metric_v1.DeviceConfiguration</code>
 */
class DeviceConfiguration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device_metric_v1.NetworkConfig network = 1;</code>
     */
    protected $network = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.SmsNotificationConfig sms = 2;</code>
     */
    protected $sms = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.GpsConfig gps = 3;</code>
     */
    protected $gps = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.LoggingConfig logging = 4;</code>
     */
    protected $logging = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.VehicleConfig vehicle = 6;</code>
     */
    protected $vehicle = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device_metric_v1\NetworkConfig $network
     *     @type \Device_metric_v1\SmsNotificationConfig $sms
     *     @type \Device_metric_v1\GpsConfig $gps
     *     @type \Device_metric_v1\LoggingConfig $logging
     *     @type \Device_metric_v1\VehicleConfig $vehicle
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.NetworkConfig network = 1;</code>
     * @return \Device_metric_v1\NetworkConfig|null
     */
    public function getNetwork()
    {
        return $this->network;
    }

    public function hasNetwork()
    {
        return isset($this->network);
    }

    public function clearNetwork()
    {
        unset($this->network);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.NetworkConfig network = 1;</code>
     * @param \Device_metric_v1\NetworkConfig $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\NetworkConfig::class);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.SmsNotificationConfig sms = 2;</code>
     * @return \Device_metric_v1\SmsNotificationConfig|null
     */
    public function getSms()
    {
        return $this->sms;
    }

    public function hasSms()
    {
        return isset($this->sms);
    }

    public function clearSms()
    {
        unset($this->sms);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.SmsNotificationConfig sms = 2;</code>
     * @param \Device_metric_v1\SmsNotificationConfig $var
     * @return $this
     */
    public function setSms($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\SmsNotificationConfig::class);
        $this->sms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.GpsConfig gps = 3;</code>
     * @return \Device_metric_v1\GpsConfig|null
     */
    public function getGps()
    {
        return $this->gps;
    }

    public function hasGps()
    {
        return isset($this->gps);
    }

    public function clearGps()
    {
        unset($this->gps);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.GpsConfig gps = 3;</code>
     * @param \Device_metric_v1\GpsConfig $var
     * @return $this
     */
    public function setGps($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\GpsConfig::class);
        $this->gps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.LoggingConfig logging = 4;</code>
     * @return \Device_metric_v1\LoggingConfig|null
     */
    public function getLogging()
    {
        return $this->logging;
    }

    public function hasLogging()
    {
        return isset($this->logging);
    }

    public function clearLogging()
    {
        unset($this->logging);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.LoggingConfig logging = 4;</code>
     * @param \Device_metric_v1\LoggingConfig $var
     * @return $this
     */
    public function setLogging($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\LoggingConfig::class);
        $this->logging = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.VehicleConfig vehicle = 6;</code>
     * @return \Device_metric_v1\VehicleConfig|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.VehicleConfig vehicle = 6;</code>
     * @param \Device_metric_v1\VehicleConfig $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\VehicleConfig::class);
        $this->vehicle = $var;

        return $this;
    }

}

