<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.DeviceCommand</code>
 */
class DeviceCommand extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandType type = 2;</code>
     */
    protected $type = 0;
    /**
     * Serialized EchoParams | RebootParams | FotaParams | GetConfigParams | EngineParams
     *
     * Generated from protobuf field <code>bytes params = 3;</code>
     */
    protected $params = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device_metric_v1\CommandHeader $header
     *     @type int $type
     *     @type string $params
     *           Serialized EchoParams | RebootParams | FotaParams | GetConfigParams | EngineParams
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     * @return \Device_metric_v1\CommandHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandHeader header = 1;</code>
     * @param \Device_metric_v1\CommandHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\CommandHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.CommandType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Device_metric_v1\CommandType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Serialized EchoParams | RebootParams | FotaParams | GetConfigParams | EngineParams
     *
     * Generated from protobuf field <code>bytes params = 3;</code>
     * @return string
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Serialized EchoParams | RebootParams | FotaParams | GetConfigParams | EngineParams
     *
     * Generated from protobuf field <code>bytes params = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, False);
        $this->params = $var;

        return $this;
    }

}

