<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.Envelope</code>
 */
class Envelope extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>uint32 seq = 2;</code>
     */
    protected $seq = 0;
    /**
     * Generated from protobuf field <code>.device_metric_v1.MessageKind kind = 3;</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>.device_metric_v1.DeviceIdentity identity = 4;</code>
     */
    protected $identity = null;
    /**
     * Serialized inner message selected by kind (GpsTelemetry, DeviceCommand, …).
     *
     * Generated from protobuf field <code>bytes body = 5;</code>
     */
    protected $body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $timestamp
     *     @type int $seq
     *     @type int $kind
     *     @type \Device_metric_v1\DeviceIdentity $identity
     *     @type string $body
     *           Serialized inner message selected by kind (GpsTelemetry, DeviceCommand, …).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 timestamp = 1;</code>
     * @return int
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint32 timestamp = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 seq = 2;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Generated from protobuf field <code>uint32 seq = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.MessageKind kind = 3;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.MessageKind kind = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Device_metric_v1\MessageKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.DeviceIdentity identity = 4;</code>
     * @return \Device_metric_v1\DeviceIdentity|null
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    public function hasIdentity()
    {
        return isset($this->identity);
    }

    public function clearIdentity()
    {
        unset($this->identity);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.DeviceIdentity identity = 4;</code>
     * @param \Device_metric_v1\DeviceIdentity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Device_metric_v1\DeviceIdentity::class);
        $this->identity = $var;

        return $this;
    }

    /**
     * Serialized inner message selected by kind (GpsTelemetry, DeviceCommand, …).
     *
     * Generated from protobuf field <code>bytes body = 5;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Serialized inner message selected by kind (GpsTelemetry, DeviceCommand, …).
     *
     * Generated from protobuf field <code>bytes body = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

}

