<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

if (false) {
    /**
     * This class is deprecated. Use Device_metric_v1\FotaStatus\State instead.
     * @deprecated
     */
    class FotaStatus_State {}
}
class_exists(FotaStatus\State::class);
@trigger_error('Device_metric_v1\FotaStatus_State is deprecated and will be removed in the next major release. Use Device_metric_v1\FotaStatus\State instead', E_USER_DEPRECATED);

