<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.FotaStatus</code>
 */
class FotaStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device_metric_v1.FotaStatus.State state = 1;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>uint32 progress_percent = 2;</code>
     */
    protected $progress_percent = 0;
    /**
     * Generated from protobuf field <code>string detail = 3;</code>
     */
    protected $detail = '';
    /**
     * Generated from protobuf field <code>string current_version = 4;</code>
     */
    protected $current_version = '';
    /**
     * Generated from protobuf field <code>string target_version = 5;</code>
     */
    protected $target_version = '';
    /**
     * Generated from protobuf field <code>string command_id = 6;</code>
     */
    protected $command_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *     @type int $progress_percent
     *     @type string $detail
     *     @type string $current_version
     *     @type string $target_version
     *     @type string $command_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.FotaStatus.State state = 1;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.device_metric_v1.FotaStatus.State state = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Device_metric_v1\FotaStatus\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 progress_percent = 2;</code>
     * @return int
     */
    public function getProgressPercent()
    {
        return $this->progress_percent;
    }

    /**
     * Generated from protobuf field <code>uint32 progress_percent = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProgressPercent($var)
    {
        GPBUtil::checkUint32($var);
        $this->progress_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string detail = 3;</code>
     * @return string
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     * Generated from protobuf field <code>string detail = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->detail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string current_version = 4;</code>
     * @return string
     */
    public function getCurrentVersion()
    {
        return $this->current_version;
    }

    /**
     * Generated from protobuf field <code>string current_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrentVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->current_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_version = 5;</code>
     * @return string
     */
    public function getTargetVersion()
    {
        return $this->target_version;
    }

    /**
     * Generated from protobuf field <code>string target_version = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string command_id = 6;</code>
     * @return string
     */
    public function getCommandId()
    {
        return $this->command_id;
    }

    /**
     * Generated from protobuf field <code>string command_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCommandId($var)
    {
        GPBUtil::checkString($var, True);
        $this->command_id = $var;

        return $this;
    }

}

