<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Which blocks to return. All false => return every known block.
 *
 * Generated from protobuf message <code>device_metric_v1.GetConfigParams</code>
 */
class GetConfigParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool network = 1;</code>
     */
    protected $network = false;
    /**
     * Generated from protobuf field <code>bool sms = 2;</code>
     */
    protected $sms = false;
    /**
     * Generated from protobuf field <code>bool gps = 3;</code>
     */
    protected $gps = false;
    /**
     * Generated from protobuf field <code>bool logging = 4;</code>
     */
    protected $logging = false;
    /**
     * Generated from protobuf field <code>bool vehicle = 5;</code>
     */
    protected $vehicle = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $network
     *     @type bool $sms
     *     @type bool $gps
     *     @type bool $logging
     *     @type bool $vehicle
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool network = 1;</code>
     * @return bool
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>bool network = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkBool($var);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool sms = 2;</code>
     * @return bool
     */
    public function getSms()
    {
        return $this->sms;
    }

    /**
     * Generated from protobuf field <code>bool sms = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSms($var)
    {
        GPBUtil::checkBool($var);
        $this->sms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool gps = 3;</code>
     * @return bool
     */
    public function getGps()
    {
        return $this->gps;
    }

    /**
     * Generated from protobuf field <code>bool gps = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setGps($var)
    {
        GPBUtil::checkBool($var);
        $this->gps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool logging = 4;</code>
     * @return bool
     */
    public function getLogging()
    {
        return $this->logging;
    }

    /**
     * Generated from protobuf field <code>bool logging = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setLogging($var)
    {
        GPBUtil::checkBool($var);
        $this->logging = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool vehicle = 5;</code>
     * @return bool
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    /**
     * Generated from protobuf field <code>bool vehicle = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkBool($var);
        $this->vehicle = $var;

        return $this;
    }

}

