<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.GpsConfig</code>
 */
class GpsConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool post_unfixed = 1;</code>
     */
    protected $post_unfixed = false;
    /**
     * Generated from protobuf field <code>uint32 field_mask = 2;</code>
     */
    protected $field_mask = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $post_unfixed
     *     @type int $field_mask
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool post_unfixed = 1;</code>
     * @return bool
     */
    public function getPostUnfixed()
    {
        return $this->post_unfixed;
    }

    /**
     * Generated from protobuf field <code>bool post_unfixed = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setPostUnfixed($var)
    {
        GPBUtil::checkBool($var);
        $this->post_unfixed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 field_mask = 2;</code>
     * @return int
     */
    public function getFieldMask()
    {
        return $this->field_mask;
    }

    /**
     * Generated from protobuf field <code>uint32 field_mask = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldMask($var)
    {
        GPBUtil::checkUint32($var);
        $this->field_mask = $var;

        return $this;
    }

}

