<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.GpsTelemetry</code>
 */
class GpsTelemetry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double lat = 1;</code>
     */
    protected $lat = 0.0;
    /**
     * Generated from protobuf field <code>double lon = 2;</code>
     */
    protected $lon = 0.0;
    /**
     * Generated from protobuf field <code>float alt = 3;</code>
     */
    protected $alt = 0.0;
    /**
     * Generated from protobuf field <code>float spd = 4;</code>
     */
    protected $spd = 0.0;
    /**
     * Generated from protobuf field <code>float hdop = 5;</code>
     */
    protected $hdop = 0.0;
    /**
     * Generated from protobuf field <code>bool valid = 6;</code>
     */
    protected $valid = false;
    /**
     * GGA tracked count (legacy)
     *
     * Generated from protobuf field <code>uint32 satellites = 7;</code>
     */
    protected $satellites = 0;
    /**
     * Generated from protobuf field <code>float pdop = 8;</code>
     */
    protected $pdop = 0.0;
    /**
     * Generated from protobuf field <code>uint32 avg_cnr = 9;</code>
     */
    protected $avg_cnr = 0;
    /**
     * Generated from protobuf field <code>uint32 quality = 10;</code>
     */
    protected $quality = 0;
    /**
     * Generated from protobuf field <code>uint32 navmode = 11;</code>
     */
    protected $navmode = 0;
    /**
     * RMC course over ground, degrees
     *
     * Generated from protobuf field <code>float heading = 12;</code>
     */
    protected $heading = 0.0;
    /**
     * GSV structured count
     *
     * Generated from protobuf field <code>uint32 sats_in_view = 13;</code>
     */
    protected $sats_in_view = 0;
    /**
     * GSA used-PRN count
     *
     * Generated from protobuf field <code>uint32 sats_used = 14;</code>
     */
    protected $sats_used = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 used_prns = 15;</code>
     */
    private $used_prns;
    /**
     * Generated from protobuf field <code>repeated .device_metric_v1.GpsSatInfo sats = 16;</code>
     */
    private $sats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $lat
     *     @type float $lon
     *     @type float $alt
     *     @type float $spd
     *     @type float $hdop
     *     @type bool $valid
     *     @type int $satellites
     *           GGA tracked count (legacy)
     *     @type float $pdop
     *     @type int $avg_cnr
     *     @type int $quality
     *     @type int $navmode
     *     @type float $heading
     *           RMC course over ground, degrees
     *     @type int $sats_in_view
     *           GSV structured count
     *     @type int $sats_used
     *           GSA used-PRN count
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $used_prns
     *     @type array<\Device_metric_v1\GpsSatInfo>|\Google\Protobuf\Internal\RepeatedField $sats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double lat = 1;</code>
     * @return float
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * Generated from protobuf field <code>double lat = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkDouble($var);
        $this->lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double lon = 2;</code>
     * @return float
     */
    public function getLon()
    {
        return $this->lon;
    }

    /**
     * Generated from protobuf field <code>double lon = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLon($var)
    {
        GPBUtil::checkDouble($var);
        $this->lon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float alt = 3;</code>
     * @return float
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
     * Generated from protobuf field <code>float alt = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAlt($var)
    {
        GPBUtil::checkFloat($var);
        $this->alt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float spd = 4;</code>
     * @return float
     */
    public function getSpd()
    {
        return $this->spd;
    }

    /**
     * Generated from protobuf field <code>float spd = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setSpd($var)
    {
        GPBUtil::checkFloat($var);
        $this->spd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float hdop = 5;</code>
     * @return float
     */
    public function getHdop()
    {
        return $this->hdop;
    }

    /**
     * Generated from protobuf field <code>float hdop = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setHdop($var)
    {
        GPBUtil::checkFloat($var);
        $this->hdop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool valid = 6;</code>
     * @return bool
     */
    public function getValid()
    {
        return $this->valid;
    }

    /**
     * Generated from protobuf field <code>bool valid = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setValid($var)
    {
        GPBUtil::checkBool($var);
        $this->valid = $var;

        return $this;
    }

    /**
     * GGA tracked count (legacy)
     *
     * Generated from protobuf field <code>uint32 satellites = 7;</code>
     * @return int
     */
    public function getSatellites()
    {
        return $this->satellites;
    }

    /**
     * GGA tracked count (legacy)
     *
     * Generated from protobuf field <code>uint32 satellites = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSatellites($var)
    {
        GPBUtil::checkUint32($var);
        $this->satellites = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float pdop = 8;</code>
     * @return float
     */
    public function getPdop()
    {
        return $this->pdop;
    }

    /**
     * Generated from protobuf field <code>float pdop = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setPdop($var)
    {
        GPBUtil::checkFloat($var);
        $this->pdop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 avg_cnr = 9;</code>
     * @return int
     */
    public function getAvgCnr()
    {
        return $this->avg_cnr;
    }

    /**
     * Generated from protobuf field <code>uint32 avg_cnr = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setAvgCnr($var)
    {
        GPBUtil::checkUint32($var);
        $this->avg_cnr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 quality = 10;</code>
     * @return int
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * Generated from protobuf field <code>uint32 quality = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setQuality($var)
    {
        GPBUtil::checkUint32($var);
        $this->quality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 navmode = 11;</code>
     * @return int
     */
    public function getNavmode()
    {
        return $this->navmode;
    }

    /**
     * Generated from protobuf field <code>uint32 navmode = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setNavmode($var)
    {
        GPBUtil::checkUint32($var);
        $this->navmode = $var;

        return $this;
    }

    /**
     * RMC course over ground, degrees
     *
     * Generated from protobuf field <code>float heading = 12;</code>
     * @return float
     */
    public function getHeading()
    {
        return $this->heading;
    }

    /**
     * RMC course over ground, degrees
     *
     * Generated from protobuf field <code>float heading = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setHeading($var)
    {
        GPBUtil::checkFloat($var);
        $this->heading = $var;

        return $this;
    }

    /**
     * GSV structured count
     *
     * Generated from protobuf field <code>uint32 sats_in_view = 13;</code>
     * @return int
     */
    public function getSatsInView()
    {
        return $this->sats_in_view;
    }

    /**
     * GSV structured count
     *
     * Generated from protobuf field <code>uint32 sats_in_view = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setSatsInView($var)
    {
        GPBUtil::checkUint32($var);
        $this->sats_in_view = $var;

        return $this;
    }

    /**
     * GSA used-PRN count
     *
     * Generated from protobuf field <code>uint32 sats_used = 14;</code>
     * @return int
     */
    public function getSatsUsed()
    {
        return $this->sats_used;
    }

    /**
     * GSA used-PRN count
     *
     * Generated from protobuf field <code>uint32 sats_used = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setSatsUsed($var)
    {
        GPBUtil::checkUint32($var);
        $this->sats_used = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 used_prns = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsedPrns()
    {
        return $this->used_prns;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 used_prns = 15;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsedPrns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->used_prns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .device_metric_v1.GpsSatInfo sats = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSats()
    {
        return $this->sats;
    }

    /**
     * Generated from protobuf field <code>repeated .device_metric_v1.GpsSatInfo sats = 16;</code>
     * @param array<\Device_metric_v1\GpsSatInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Device_metric_v1\GpsSatInfo::class);
        $this->sats = $arr;

        return $this;
    }

}

