<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use UnexpectedValueException;

/**
 * Protobuf type <code>device_metric_v1.MessageKind</code>
 */
class MessageKind
{
    /**
     * Generated from protobuf enum <code>KIND_UNSPECIFIED = 0;</code>
     */
    const KIND_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>TELEMETRY_GPS = 1;</code>
     */
    const TELEMETRY_GPS = 1;
    /**
     * Generated from protobuf enum <code>DEVICE_IDENTITY = 2;</code>
     */
    const DEVICE_IDENTITY = 2;
    /**
     * Generated from protobuf enum <code>FOTA_STATUS = 3;</code>
     */
    const FOTA_STATUS = 3;
    /**
     * CommandResponse on wire
     *
     * Generated from protobuf enum <code>COMMAND_ACK = 4;</code>
     */
    const COMMAND_ACK = 4;
    /**
     * Generated from protobuf enum <code>CONFIG = 10;</code>
     */
    const CONFIG = 10;
    /**
     * Generated from protobuf enum <code>COMMAND = 11;</code>
     */
    const COMMAND = 11;

    private static $valueToName = [
        self::KIND_UNSPECIFIED => 'KIND_UNSPECIFIED',
        self::TELEMETRY_GPS => 'TELEMETRY_GPS',
        self::DEVICE_IDENTITY => 'DEVICE_IDENTITY',
        self::FOTA_STATUS => 'FOTA_STATUS',
        self::COMMAND_ACK => 'COMMAND_ACK',
        self::CONFIG => 'CONFIG',
        self::COMMAND => 'COMMAND',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

