<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.RelayParams</code>
 */
class RelayParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool on = 1;</code>
     */
    protected $on = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $on
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool on = 1;</code>
     * @return bool
     */
    public function getOn()
    {
        return $this->on;
    }

    /**
     * Generated from protobuf field <code>bool on = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOn($var)
    {
        GPBUtil::checkBool($var);
        $this->on = $var;

        return $this;
    }

}

