<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Vehicle I/O on ingest/telemetry/vehicle (separate from GPS).
 * last_shock_at is sticky unix seconds (0 = never); notify when it increases.
 * Device always sets presence (nanopb OPTIONAL) so false/0 still appear on wire.
 *
 * Generated from protobuf message <code>device_metric_v1.VehicleStatus</code>
 */
class VehicleStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * ACC=1 active
     *
     * Generated from protobuf field <code>optional bool acc_active = 1;</code>
     */
    protected $acc_active = null;
    /**
     * door signal active (active-low pin)
     *
     * Generated from protobuf field <code>optional bool door_active = 2;</code>
     */
    protected $door_active = null;
    /**
     * current shock pin level
     *
     * Generated from protobuf field <code>optional bool shock_level = 3;</code>
     */
    protected $shock_level = null;
    /**
     * Generated from protobuf field <code>optional bool relay_on = 4;</code>
     */
    protected $relay_on = null;
    /**
     * Generated from protobuf field <code>optional uint32 bat_mv = 5;</code>
     */
    protected $bat_mv = null;
    /**
     * Generated from protobuf field <code>optional uint32 last_shock_at = 6;</code>
     */
    protected $last_shock_at = null;
    /**
     * unix sec of this sample; always set
     *
     * Generated from protobuf field <code>optional uint32 reported_at = 7;</code>
     */
    protected $reported_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $acc_active
     *           ACC=1 active
     *     @type bool $door_active
     *           door signal active (active-low pin)
     *     @type bool $shock_level
     *           current shock pin level
     *     @type bool $relay_on
     *     @type int $bat_mv
     *     @type int $last_shock_at
     *     @type int $reported_at
     *           unix sec of this sample; always set
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * ACC=1 active
     *
     * Generated from protobuf field <code>optional bool acc_active = 1;</code>
     * @return bool
     */
    public function getAccActive()
    {
        return isset($this->acc_active) ? $this->acc_active : false;
    }

    public function hasAccActive()
    {
        return isset($this->acc_active);
    }

    public function clearAccActive()
    {
        unset($this->acc_active);
    }

    /**
     * ACC=1 active
     *
     * Generated from protobuf field <code>optional bool acc_active = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAccActive($var)
    {
        GPBUtil::checkBool($var);
        $this->acc_active = $var;

        return $this;
    }

    /**
     * door signal active (active-low pin)
     *
     * Generated from protobuf field <code>optional bool door_active = 2;</code>
     * @return bool
     */
    public function getDoorActive()
    {
        return isset($this->door_active) ? $this->door_active : false;
    }

    public function hasDoorActive()
    {
        return isset($this->door_active);
    }

    public function clearDoorActive()
    {
        unset($this->door_active);
    }

    /**
     * door signal active (active-low pin)
     *
     * Generated from protobuf field <code>optional bool door_active = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDoorActive($var)
    {
        GPBUtil::checkBool($var);
        $this->door_active = $var;

        return $this;
    }

    /**
     * current shock pin level
     *
     * Generated from protobuf field <code>optional bool shock_level = 3;</code>
     * @return bool
     */
    public function getShockLevel()
    {
        return isset($this->shock_level) ? $this->shock_level : false;
    }

    public function hasShockLevel()
    {
        return isset($this->shock_level);
    }

    public function clearShockLevel()
    {
        unset($this->shock_level);
    }

    /**
     * current shock pin level
     *
     * Generated from protobuf field <code>optional bool shock_level = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setShockLevel($var)
    {
        GPBUtil::checkBool($var);
        $this->shock_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool relay_on = 4;</code>
     * @return bool
     */
    public function getRelayOn()
    {
        return isset($this->relay_on) ? $this->relay_on : false;
    }

    public function hasRelayOn()
    {
        return isset($this->relay_on);
    }

    public function clearRelayOn()
    {
        unset($this->relay_on);
    }

    /**
     * Generated from protobuf field <code>optional bool relay_on = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRelayOn($var)
    {
        GPBUtil::checkBool($var);
        $this->relay_on = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 bat_mv = 5;</code>
     * @return int
     */
    public function getBatMv()
    {
        return isset($this->bat_mv) ? $this->bat_mv : 0;
    }

    public function hasBatMv()
    {
        return isset($this->bat_mv);
    }

    public function clearBatMv()
    {
        unset($this->bat_mv);
    }

    /**
     * Generated from protobuf field <code>optional uint32 bat_mv = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBatMv($var)
    {
        GPBUtil::checkUint32($var);
        $this->bat_mv = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_shock_at = 6;</code>
     * @return int
     */
    public function getLastShockAt()
    {
        return isset($this->last_shock_at) ? $this->last_shock_at : 0;
    }

    public function hasLastShockAt()
    {
        return isset($this->last_shock_at);
    }

    public function clearLastShockAt()
    {
        unset($this->last_shock_at);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_shock_at = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLastShockAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_shock_at = $var;

        return $this;
    }

    /**
     * unix sec of this sample; always set
     *
     * Generated from protobuf field <code>optional uint32 reported_at = 7;</code>
     * @return int
     */
    public function getReportedAt()
    {
        return isset($this->reported_at) ? $this->reported_at : 0;
    }

    public function hasReportedAt()
    {
        return isset($this->reported_at);
    }

    public function clearReportedAt()
    {
        unset($this->reported_at);
    }

    /**
     * unix sec of this sample; always set
     *
     * Generated from protobuf field <code>optional uint32 reported_at = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setReportedAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->reported_at = $var;

        return $this;
    }

}

