<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_device_metric_v1.proto

namespace Device_metric_v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device_metric_v1.VehicleConfig</code>
 */
class VehicleConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * vehicle status uplink interval (default 1000)
     *
     * Generated from protobuf field <code>uint32 post_period_ms = 1;</code>
     */
    protected $post_period_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $post_period_ms
     *           vehicle status uplink interval (default 1000)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDeviceMetricV1::initOnce();
        parent::__construct($data);
    }

    /**
     * vehicle status uplink interval (default 1000)
     *
     * Generated from protobuf field <code>uint32 post_period_ms = 1;</code>
     * @return int
     */
    public function getPostPeriodMs()
    {
        return $this->post_period_ms;
    }

    /**
     * vehicle status uplink interval (default 1000)
     *
     * Generated from protobuf field <code>uint32 post_period_ms = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPostPeriodMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->post_period_ms = $var;

        return $this;
    }

}

