<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_fota_v1.proto

namespace Device\FotaStatus;

use UnexpectedValueException;

/**
 * Protobuf type <code>device.FotaStatus.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>IDLE = 0;</code>
     */
    const IDLE = 0;
    /**
     * Generated from protobuf enum <code>DOWNLOADING = 1;</code>
     */
    const DOWNLOADING = 1;
    /**
     * Generated from protobuf enum <code>VERIFYING = 2;</code>
     */
    const VERIFYING = 2;
    /**
     * Generated from protobuf enum <code>APPLYING = 3;</code>
     */
    const APPLYING = 3;
    /**
     * Generated from protobuf enum <code>SUCCESS = 4;</code>
     */
    const SUCCESS = 4;
    /**
     * Generated from protobuf enum <code>FAILED = 5;</code>
     */
    const FAILED = 5;

    private static $valueToName = [
        self::IDLE => 'IDLE',
        self::DOWNLOADING => 'DOWNLOADING',
        self::VERIFYING => 'VERIFYING',
        self::APPLYING => 'APPLYING',
        self::SUCCESS => 'SUCCESS',
        self::FAILED => 'FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(State::class, \Device\FotaStatus_State::class);

