// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shared_d_config_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apn           string                 `protobuf:"bytes,1,opt,name=apn,proto3" json:"apn,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pass          string                 `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_shared_d_config_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_config_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_shared_d_config_v1_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkConfig) GetApn() string {
	if x != nil {
		return x.Apn
	}
	return ""
}

func (x *NetworkConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *NetworkConfig) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type SmsRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"` // E.164, e.g. "+989123456789"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsRecipient) Reset() {
	*x = SmsRecipient{}
	mi := &file_shared_d_config_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsRecipient) ProtoMessage() {}

func (x *SmsRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_config_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsRecipient.ProtoReflect.Descriptor instead.
func (*SmsRecipient) Descriptor() ([]byte, []int) {
	return file_shared_d_config_v1_proto_rawDescGZIP(), []int{1}
}

func (x *SmsRecipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SmsRecipient) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type SmsNotificationConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recipients      []*SmsRecipient        `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"` // max 5 (nanopb STATIC)
	Enabled         bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`      // master switch
	EnableShock     bool                   `protobuf:"varint,3,opt,name=enable_shock,json=enableShock,proto3" json:"enable_shock,omitempty"`
	EnableAccOn     bool                   `protobuf:"varint,4,opt,name=enable_acc_on,json=enableAccOn,proto3" json:"enable_acc_on,omitempty"`
	EnableAccOff    bool                   `protobuf:"varint,5,opt,name=enable_acc_off,json=enableAccOff,proto3" json:"enable_acc_off,omitempty"`
	EnableDoorOpen  bool                   `protobuf:"varint,6,opt,name=enable_door_open,json=enableDoorOpen,proto3" json:"enable_door_open,omitempty"`
	EnableDoorClose bool                   `protobuf:"varint,7,opt,name=enable_door_close,json=enableDoorClose,proto3" json:"enable_door_close,omitempty"`
	MsgShock        string                 `protobuf:"bytes,8,opt,name=msg_shock,json=msgShock,proto3" json:"msg_shock,omitempty"`
	MsgAccOn        string                 `protobuf:"bytes,9,opt,name=msg_acc_on,json=msgAccOn,proto3" json:"msg_acc_on,omitempty"`
	MsgAccOff       string                 `protobuf:"bytes,10,opt,name=msg_acc_off,json=msgAccOff,proto3" json:"msg_acc_off,omitempty"`
	MsgDoorOpen     string                 `protobuf:"bytes,11,opt,name=msg_door_open,json=msgDoorOpen,proto3" json:"msg_door_open,omitempty"`
	MsgDoorClose    string                 `protobuf:"bytes,12,opt,name=msg_door_close,json=msgDoorClose,proto3" json:"msg_door_close,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SmsNotificationConfig) Reset() {
	*x = SmsNotificationConfig{}
	mi := &file_shared_d_config_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationConfig) ProtoMessage() {}

func (x *SmsNotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_config_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationConfig.ProtoReflect.Descriptor instead.
func (*SmsNotificationConfig) Descriptor() ([]byte, []int) {
	return file_shared_d_config_v1_proto_rawDescGZIP(), []int{2}
}

func (x *SmsNotificationConfig) GetRecipients() []*SmsRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SmsNotificationConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableShock() bool {
	if x != nil {
		return x.EnableShock
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableAccOn() bool {
	if x != nil {
		return x.EnableAccOn
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableAccOff() bool {
	if x != nil {
		return x.EnableAccOff
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableDoorOpen() bool {
	if x != nil {
		return x.EnableDoorOpen
	}
	return false
}

func (x *SmsNotificationConfig) GetEnableDoorClose() bool {
	if x != nil {
		return x.EnableDoorClose
	}
	return false
}

func (x *SmsNotificationConfig) GetMsgShock() string {
	if x != nil {
		return x.MsgShock
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgAccOn() string {
	if x != nil {
		return x.MsgAccOn
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgAccOff() string {
	if x != nil {
		return x.MsgAccOff
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgDoorOpen() string {
	if x != nil {
		return x.MsgDoorOpen
	}
	return ""
}

func (x *SmsNotificationConfig) GetMsgDoorClose() string {
	if x != nil {
		return x.MsgDoorClose
	}
	return ""
}

type LoggingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingConfig) Reset() {
	*x = LoggingConfig{}
	mi := &file_shared_d_config_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingConfig) ProtoMessage() {}

func (x *LoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_config_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingConfig.ProtoReflect.Descriptor instead.
func (*LoggingConfig) Descriptor() ([]byte, []int) {
	return file_shared_d_config_v1_proto_rawDescGZIP(), []int{3}
}

func (x *LoggingConfig) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Full/partial snapshot of current settings (read path).
type DeviceConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *NetworkConfig         `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Sms           *SmsNotificationConfig `protobuf:"bytes,2,opt,name=sms,proto3" json:"sms,omitempty"`
	Gps           *GpsConfig             `protobuf:"bytes,3,opt,name=gps,proto3" json:"gps,omitempty"`
	Logging       *LoggingConfig         `protobuf:"bytes,4,opt,name=logging,proto3" json:"logging,omitempty"`
	Telemetry     *TelemetryConfig       `protobuf:"bytes,5,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Vehicle       *VehicleConfig         `protobuf:"bytes,6,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfiguration) Reset() {
	*x = DeviceConfiguration{}
	mi := &file_shared_d_config_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfiguration) ProtoMessage() {}

func (x *DeviceConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_config_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfiguration.ProtoReflect.Descriptor instead.
func (*DeviceConfiguration) Descriptor() ([]byte, []int) {
	return file_shared_d_config_v1_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceConfiguration) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *DeviceConfiguration) GetSms() *SmsNotificationConfig {
	if x != nil {
		return x.Sms
	}
	return nil
}

func (x *DeviceConfiguration) GetGps() *GpsConfig {
	if x != nil {
		return x.Gps
	}
	return nil
}

func (x *DeviceConfiguration) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *DeviceConfiguration) GetTelemetry() *TelemetryConfig {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *DeviceConfiguration) GetVehicle() *VehicleConfig {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

// Patch settings (write path). Same blocks; omit = leave unchanged.
// MQTT root for device/{id}/config
type DeviceConfigurationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CommandHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Network       *NetworkConfig         `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Sms           *SmsNotificationConfig `protobuf:"bytes,3,opt,name=sms,proto3" json:"sms,omitempty"`
	Gps           *GpsConfig             `protobuf:"bytes,4,opt,name=gps,proto3" json:"gps,omitempty"`
	Logging       *LoggingConfig         `protobuf:"bytes,5,opt,name=logging,proto3" json:"logging,omitempty"`
	Vehicle       *VehicleConfig         `protobuf:"bytes,6,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Telemetry     *TelemetryConfig       `protobuf:"bytes,7,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	ProtoVersion  ProtoVersion           `protobuf:"varint,100,opt,name=proto_version,json=protoVersion,proto3,enum=device.ProtoVersion" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigurationUpdate) Reset() {
	*x = DeviceConfigurationUpdate{}
	mi := &file_shared_d_config_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigurationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigurationUpdate) ProtoMessage() {}

func (x *DeviceConfigurationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_config_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigurationUpdate.ProtoReflect.Descriptor instead.
func (*DeviceConfigurationUpdate) Descriptor() ([]byte, []int) {
	return file_shared_d_config_v1_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceConfigurationUpdate) GetHeader() *CommandHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetSms() *SmsNotificationConfig {
	if x != nil {
		return x.Sms
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetGps() *GpsConfig {
	if x != nil {
		return x.Gps
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetVehicle() *VehicleConfig {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetTelemetry() *TelemetryConfig {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *DeviceConfigurationUpdate) GetProtoVersion() ProtoVersion {
	if x != nil {
		return x.ProtoVersion
	}
	return ProtoVersion_PROTO_VERSION_UNSPECIFIED
}

var File_shared_d_config_v1_proto protoreflect.FileDescriptor

const file_shared_d_config_v1_proto_rawDesc = "" +
	"\n" +
	"\x18shared_d_config_v1.proto\x12\x06device\x1a\x18shared_d_common_v1.proto\x1a\x0ed_gps_v1.proto\x1a\x12d_vehicle_v1.proto\x1a\x14d_telemetry_v1.proto\"I\n" +
	"\rNetworkConfig\x12\x10\n" +
	"\x03apn\x18\x01 \x01(\tR\x03apn\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04pass\x18\x03 \x01(\tR\x04pass\":\n" +
	"\fSmsRecipient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"\xcf\x03\n" +
	"\x15SmsNotificationConfig\x124\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x14.device.SmsRecipientR\n" +
	"recipients\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12!\n" +
	"\fenable_shock\x18\x03 \x01(\bR\venableShock\x12\"\n" +
	"\renable_acc_on\x18\x04 \x01(\bR\venableAccOn\x12$\n" +
	"\x0eenable_acc_off\x18\x05 \x01(\bR\fenableAccOff\x12(\n" +
	"\x10enable_door_open\x18\x06 \x01(\bR\x0eenableDoorOpen\x12*\n" +
	"\x11enable_door_close\x18\a \x01(\bR\x0fenableDoorClose\x12\x1b\n" +
	"\tmsg_shock\x18\b \x01(\tR\bmsgShock\x12\x1c\n" +
	"\n" +
	"msg_acc_on\x18\t \x01(\tR\bmsgAccOn\x12\x1e\n" +
	"\vmsg_acc_off\x18\n" +
	" \x01(\tR\tmsgAccOff\x12\"\n" +
	"\rmsg_door_open\x18\v \x01(\tR\vmsgDoorOpen\x12$\n" +
	"\x0emsg_door_close\x18\f \x01(\tR\fmsgDoorClose\"%\n" +
	"\rLoggingConfig\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\"\xb5\x02\n" +
	"\x13DeviceConfiguration\x12/\n" +
	"\anetwork\x18\x01 \x01(\v2\x15.device.NetworkConfigR\anetwork\x12/\n" +
	"\x03sms\x18\x02 \x01(\v2\x1d.device.SmsNotificationConfigR\x03sms\x12#\n" +
	"\x03gps\x18\x03 \x01(\v2\x11.device.GpsConfigR\x03gps\x12/\n" +
	"\alogging\x18\x04 \x01(\v2\x15.device.LoggingConfigR\alogging\x125\n" +
	"\ttelemetry\x18\x05 \x01(\v2\x17.device.TelemetryConfigR\ttelemetry\x12/\n" +
	"\avehicle\x18\x06 \x01(\v2\x15.device.VehicleConfigR\avehicle\"\xa5\x03\n" +
	"\x19DeviceConfigurationUpdate\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.device.CommandHeaderR\x06header\x12/\n" +
	"\anetwork\x18\x02 \x01(\v2\x15.device.NetworkConfigR\anetwork\x12/\n" +
	"\x03sms\x18\x03 \x01(\v2\x1d.device.SmsNotificationConfigR\x03sms\x12#\n" +
	"\x03gps\x18\x04 \x01(\v2\x11.device.GpsConfigR\x03gps\x12/\n" +
	"\alogging\x18\x05 \x01(\v2\x15.device.LoggingConfigR\alogging\x12/\n" +
	"\avehicle\x18\x06 \x01(\v2\x15.device.VehicleConfigR\avehicle\x125\n" +
	"\ttelemetry\x18\a \x01(\v2\x17.device.TelemetryConfigR\ttelemetry\x129\n" +
	"\rproto_version\x18d \x01(\x0e2\x14.device.ProtoVersionR\fprotoVersionBBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_shared_d_config_v1_proto_rawDescOnce sync.Once
	file_shared_d_config_v1_proto_rawDescData []byte
)

func file_shared_d_config_v1_proto_rawDescGZIP() []byte {
	file_shared_d_config_v1_proto_rawDescOnce.Do(func() {
		file_shared_d_config_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_d_config_v1_proto_rawDesc), len(file_shared_d_config_v1_proto_rawDesc)))
	})
	return file_shared_d_config_v1_proto_rawDescData
}

var file_shared_d_config_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_d_config_v1_proto_goTypes = []any{
	(*NetworkConfig)(nil),             // 0: device.NetworkConfig
	(*SmsRecipient)(nil),              // 1: device.SmsRecipient
	(*SmsNotificationConfig)(nil),     // 2: device.SmsNotificationConfig
	(*LoggingConfig)(nil),             // 3: device.LoggingConfig
	(*DeviceConfiguration)(nil),       // 4: device.DeviceConfiguration
	(*DeviceConfigurationUpdate)(nil), // 5: device.DeviceConfigurationUpdate
	(*GpsConfig)(nil),                 // 6: device.GpsConfig
	(*TelemetryConfig)(nil),           // 7: device.TelemetryConfig
	(*VehicleConfig)(nil),             // 8: device.VehicleConfig
	(*CommandHeader)(nil),             // 9: device.CommandHeader
	(ProtoVersion)(0),                 // 10: device.ProtoVersion
}
var file_shared_d_config_v1_proto_depIdxs = []int32{
	1,  // 0: device.SmsNotificationConfig.recipients:type_name -> device.SmsRecipient
	0,  // 1: device.DeviceConfiguration.network:type_name -> device.NetworkConfig
	2,  // 2: device.DeviceConfiguration.sms:type_name -> device.SmsNotificationConfig
	6,  // 3: device.DeviceConfiguration.gps:type_name -> device.GpsConfig
	3,  // 4: device.DeviceConfiguration.logging:type_name -> device.LoggingConfig
	7,  // 5: device.DeviceConfiguration.telemetry:type_name -> device.TelemetryConfig
	8,  // 6: device.DeviceConfiguration.vehicle:type_name -> device.VehicleConfig
	9,  // 7: device.DeviceConfigurationUpdate.header:type_name -> device.CommandHeader
	0,  // 8: device.DeviceConfigurationUpdate.network:type_name -> device.NetworkConfig
	2,  // 9: device.DeviceConfigurationUpdate.sms:type_name -> device.SmsNotificationConfig
	6,  // 10: device.DeviceConfigurationUpdate.gps:type_name -> device.GpsConfig
	3,  // 11: device.DeviceConfigurationUpdate.logging:type_name -> device.LoggingConfig
	8,  // 12: device.DeviceConfigurationUpdate.vehicle:type_name -> device.VehicleConfig
	7,  // 13: device.DeviceConfigurationUpdate.telemetry:type_name -> device.TelemetryConfig
	10, // 14: device.DeviceConfigurationUpdate.proto_version:type_name -> device.ProtoVersion
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_shared_d_config_v1_proto_init() }
func file_shared_d_config_v1_proto_init() {
	if File_shared_d_config_v1_proto != nil {
		return
	}
	file_shared_d_common_v1_proto_init()
	file_d_gps_v1_proto_init()
	file_d_vehicle_v1_proto_init()
	file_d_telemetry_v1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_d_config_v1_proto_rawDesc), len(file_shared_d_config_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_d_config_v1_proto_goTypes,
		DependencyIndexes: file_shared_d_config_v1_proto_depIdxs,
		MessageInfos:      file_shared_d_config_v1_proto_msgTypes,
	}.Build()
	File_shared_d_config_v1_proto = out.File
	file_shared_d_config_v1_proto_goTypes = nil
	file_shared_d_config_v1_proto_depIdxs = nil
}
