// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: d_gps_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GpsSatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prn           uint32                 `protobuf:"varint,1,opt,name=prn,proto3" json:"prn,omitempty"`
	Elev          int32                  `protobuf:"zigzag32,2,opt,name=elev,proto3" json:"elev,omitempty"`
	Azim          uint32                 `protobuf:"varint,3,opt,name=azim,proto3" json:"azim,omitempty"`
	Snr           uint32                 `protobuf:"varint,4,opt,name=snr,proto3" json:"snr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsSatInfo) Reset() {
	*x = GpsSatInfo{}
	mi := &file_d_gps_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsSatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsSatInfo) ProtoMessage() {}

func (x *GpsSatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_d_gps_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsSatInfo.ProtoReflect.Descriptor instead.
func (*GpsSatInfo) Descriptor() ([]byte, []int) {
	return file_d_gps_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GpsSatInfo) GetPrn() uint32 {
	if x != nil {
		return x.Prn
	}
	return 0
}

func (x *GpsSatInfo) GetElev() int32 {
	if x != nil {
		return x.Elev
	}
	return 0
}

func (x *GpsSatInfo) GetAzim() uint32 {
	if x != nil {
		return x.Azim
	}
	return 0
}

func (x *GpsSatInfo) GetSnr() uint32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

type GpsTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float32                `protobuf:"fixed32,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Spd           float32                `protobuf:"fixed32,4,opt,name=spd,proto3" json:"spd,omitempty"`
	Hdop          float32                `protobuf:"fixed32,5,opt,name=hdop,proto3" json:"hdop,omitempty"`
	Valid         bool                   `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	Satellites    uint32                 `protobuf:"varint,7,opt,name=satellites,proto3" json:"satellites,omitempty"` // GGA tracked count (legacy)
	Pdop          float32                `protobuf:"fixed32,8,opt,name=pdop,proto3" json:"pdop,omitempty"`
	AvgCnr        uint32                 `protobuf:"varint,9,opt,name=avg_cnr,json=avgCnr,proto3" json:"avg_cnr,omitempty"`
	Quality       uint32                 `protobuf:"varint,10,opt,name=quality,proto3" json:"quality,omitempty"`
	Navmode       uint32                 `protobuf:"varint,11,opt,name=navmode,proto3" json:"navmode,omitempty"`
	Heading       float32                `protobuf:"fixed32,12,opt,name=heading,proto3" json:"heading,omitempty"`                          // RMC course over ground, degrees
	SatsInView    uint32                 `protobuf:"varint,13,opt,name=sats_in_view,json=satsInView,proto3" json:"sats_in_view,omitempty"` // GSV structured count
	SatsUsed      uint32                 `protobuf:"varint,14,opt,name=sats_used,json=satsUsed,proto3" json:"sats_used,omitempty"`         // GSA used-PRN count
	UsedPrns      []uint32               `protobuf:"varint,15,rep,packed,name=used_prns,json=usedPrns,proto3" json:"used_prns,omitempty"`
	Sats          []*GpsSatInfo          `protobuf:"bytes,16,rep,name=sats,proto3" json:"sats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsTelemetry) Reset() {
	*x = GpsTelemetry{}
	mi := &file_d_gps_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsTelemetry) ProtoMessage() {}

func (x *GpsTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_d_gps_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsTelemetry.ProtoReflect.Descriptor instead.
func (*GpsTelemetry) Descriptor() ([]byte, []int) {
	return file_d_gps_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GpsTelemetry) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GpsTelemetry) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GpsTelemetry) GetAlt() float32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *GpsTelemetry) GetSpd() float32 {
	if x != nil {
		return x.Spd
	}
	return 0
}

func (x *GpsTelemetry) GetHdop() float32 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *GpsTelemetry) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GpsTelemetry) GetSatellites() uint32 {
	if x != nil {
		return x.Satellites
	}
	return 0
}

func (x *GpsTelemetry) GetPdop() float32 {
	if x != nil {
		return x.Pdop
	}
	return 0
}

func (x *GpsTelemetry) GetAvgCnr() uint32 {
	if x != nil {
		return x.AvgCnr
	}
	return 0
}

func (x *GpsTelemetry) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *GpsTelemetry) GetNavmode() uint32 {
	if x != nil {
		return x.Navmode
	}
	return 0
}

func (x *GpsTelemetry) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *GpsTelemetry) GetSatsInView() uint32 {
	if x != nil {
		return x.SatsInView
	}
	return 0
}

func (x *GpsTelemetry) GetSatsUsed() uint32 {
	if x != nil {
		return x.SatsUsed
	}
	return 0
}

func (x *GpsTelemetry) GetUsedPrns() []uint32 {
	if x != nil {
		return x.UsedPrns
	}
	return nil
}

func (x *GpsTelemetry) GetSats() []*GpsSatInfo {
	if x != nil {
		return x.Sats
	}
	return nil
}

type GpsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUnfixed   bool                   `protobuf:"varint,1,opt,name=post_unfixed,json=postUnfixed,proto3" json:"post_unfixed,omitempty"`
	FieldMask     uint32                 `protobuf:"varint,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // APP_GPS_FIELD_* bits
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsConfig) Reset() {
	*x = GpsConfig{}
	mi := &file_d_gps_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsConfig) ProtoMessage() {}

func (x *GpsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_d_gps_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsConfig.ProtoReflect.Descriptor instead.
func (*GpsConfig) Descriptor() ([]byte, []int) {
	return file_d_gps_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GpsConfig) GetPostUnfixed() bool {
	if x != nil {
		return x.PostUnfixed
	}
	return false
}

func (x *GpsConfig) GetFieldMask() uint32 {
	if x != nil {
		return x.FieldMask
	}
	return 0
}

var File_d_gps_v1_proto protoreflect.FileDescriptor

const file_d_gps_v1_proto_rawDesc = "" +
	"\n" +
	"\x0ed_gps_v1.proto\x12\x06device\"X\n" +
	"\n" +
	"GpsSatInfo\x12\x10\n" +
	"\x03prn\x18\x01 \x01(\rR\x03prn\x12\x12\n" +
	"\x04elev\x18\x02 \x01(\x11R\x04elev\x12\x12\n" +
	"\x04azim\x18\x03 \x01(\rR\x04azim\x12\x10\n" +
	"\x03snr\x18\x04 \x01(\rR\x03snr\"\x9f\x03\n" +
	"\fGpsTelemetry\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x02R\x03alt\x12\x10\n" +
	"\x03spd\x18\x04 \x01(\x02R\x03spd\x12\x12\n" +
	"\x04hdop\x18\x05 \x01(\x02R\x04hdop\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\bR\x05valid\x12\x1e\n" +
	"\n" +
	"satellites\x18\a \x01(\rR\n" +
	"satellites\x12\x12\n" +
	"\x04pdop\x18\b \x01(\x02R\x04pdop\x12\x17\n" +
	"\aavg_cnr\x18\t \x01(\rR\x06avgCnr\x12\x18\n" +
	"\aquality\x18\n" +
	" \x01(\rR\aquality\x12\x18\n" +
	"\anavmode\x18\v \x01(\rR\anavmode\x12\x18\n" +
	"\aheading\x18\f \x01(\x02R\aheading\x12 \n" +
	"\fsats_in_view\x18\r \x01(\rR\n" +
	"satsInView\x12\x1b\n" +
	"\tsats_used\x18\x0e \x01(\rR\bsatsUsed\x12\x1b\n" +
	"\tused_prns\x18\x0f \x03(\rR\busedPrns\x12&\n" +
	"\x04sats\x18\x10 \x03(\v2\x12.device.GpsSatInfoR\x04sats\"M\n" +
	"\tGpsConfig\x12!\n" +
	"\fpost_unfixed\x18\x01 \x01(\bR\vpostUnfixed\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\rR\tfieldMaskBBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_d_gps_v1_proto_rawDescOnce sync.Once
	file_d_gps_v1_proto_rawDescData []byte
)

func file_d_gps_v1_proto_rawDescGZIP() []byte {
	file_d_gps_v1_proto_rawDescOnce.Do(func() {
		file_d_gps_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_d_gps_v1_proto_rawDesc), len(file_d_gps_v1_proto_rawDesc)))
	})
	return file_d_gps_v1_proto_rawDescData
}

var file_d_gps_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_d_gps_v1_proto_goTypes = []any{
	(*GpsSatInfo)(nil),   // 0: device.GpsSatInfo
	(*GpsTelemetry)(nil), // 1: device.GpsTelemetry
	(*GpsConfig)(nil),    // 2: device.GpsConfig
}
var file_d_gps_v1_proto_depIdxs = []int32{
	0, // 0: device.GpsTelemetry.sats:type_name -> device.GpsSatInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_d_gps_v1_proto_init() }
func file_d_gps_v1_proto_init() {
	if File_d_gps_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_d_gps_v1_proto_rawDesc), len(file_d_gps_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_d_gps_v1_proto_goTypes,
		DependencyIndexes: file_d_gps_v1_proto_depIdxs,
		MessageInfos:      file_d_gps_v1_proto_msgTypes,
	}.Build()
	File_d_gps_v1_proto = out.File
	file_d_gps_v1_proto_goTypes = nil
	file_d_gps_v1_proto_depIdxs = nil
}
