// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: metric_state_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageKind int32

const (
	MessageKind_KIND_UNSPECIFIED MessageKind = 0
	MessageKind_TELEMETRY_GPS    MessageKind = 1
	MessageKind_DEVICE_IDENTITY  MessageKind = 2
	MessageKind_FOTA_STATUS      MessageKind = 3
	MessageKind_COMMAND_ACK      MessageKind = 4
	MessageKind_CONFIG           MessageKind = 10
	MessageKind_COMMAND          MessageKind = 11
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0:  "KIND_UNSPECIFIED",
		1:  "TELEMETRY_GPS",
		2:  "DEVICE_IDENTITY",
		3:  "FOTA_STATUS",
		4:  "COMMAND_ACK",
		10: "CONFIG",
		11: "COMMAND",
	}
	MessageKind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"TELEMETRY_GPS":    1,
		"DEVICE_IDENTITY":  2,
		"FOTA_STATUS":      3,
		"COMMAND_ACK":      4,
		"CONFIG":           10,
		"COMMAND":          11,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_metric_state_v1_proto_enumTypes[0].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_metric_state_v1_proto_enumTypes[0]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{0}
}

type DeviceCommand_Type int32

const (
	DeviceCommand_UNSPECIFIED DeviceCommand_Type = 0
	DeviceCommand_REBOOT      DeviceCommand_Type = 1
	DeviceCommand_SEND_SMS    DeviceCommand_Type = 2
)

// Enum value maps for DeviceCommand_Type.
var (
	DeviceCommand_Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "REBOOT",
		2: "SEND_SMS",
	}
	DeviceCommand_Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"REBOOT":      1,
		"SEND_SMS":    2,
	}
)

func (x DeviceCommand_Type) Enum() *DeviceCommand_Type {
	p := new(DeviceCommand_Type)
	*p = x
	return p
}

func (x DeviceCommand_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCommand_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_metric_state_v1_proto_enumTypes[1].Descriptor()
}

func (DeviceCommand_Type) Type() protoreflect.EnumType {
	return &file_metric_state_v1_proto_enumTypes[1]
}

func (x DeviceCommand_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCommand_Type.Descriptor instead.
func (DeviceCommand_Type) EnumDescriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{5, 0}
}

type FotaStatus_State int32

const (
	FotaStatus_IDLE        FotaStatus_State = 0
	FotaStatus_DOWNLOADING FotaStatus_State = 1
	FotaStatus_VERIFYING   FotaStatus_State = 2
	FotaStatus_APPLYING    FotaStatus_State = 3
	FotaStatus_SUCCESS     FotaStatus_State = 4
	FotaStatus_FAILED      FotaStatus_State = 5
)

// Enum value maps for FotaStatus_State.
var (
	FotaStatus_State_name = map[int32]string{
		0: "IDLE",
		1: "DOWNLOADING",
		2: "VERIFYING",
		3: "APPLYING",
		4: "SUCCESS",
		5: "FAILED",
	}
	FotaStatus_State_value = map[string]int32{
		"IDLE":        0,
		"DOWNLOADING": 1,
		"VERIFYING":   2,
		"APPLYING":    3,
		"SUCCESS":     4,
		"FAILED":      5,
	}
)

func (x FotaStatus_State) Enum() *FotaStatus_State {
	p := new(FotaStatus_State)
	*p = x
	return p
}

func (x FotaStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FotaStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_metric_state_v1_proto_enumTypes[2].Descriptor()
}

func (FotaStatus_State) Type() protoreflect.EnumType {
	return &file_metric_state_v1_proto_enumTypes[2]
}

func (x FotaStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FotaStatus_State.Descriptor instead.
func (FotaStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{6, 0}
}

type GpsSatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prn           uint32                 `protobuf:"varint,1,opt,name=prn,proto3" json:"prn,omitempty"`
	Elev          int32                  `protobuf:"zigzag32,2,opt,name=elev,proto3" json:"elev,omitempty"`
	Azim          uint32                 `protobuf:"varint,3,opt,name=azim,proto3" json:"azim,omitempty"`
	Snr           uint32                 `protobuf:"varint,4,opt,name=snr,proto3" json:"snr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsSatInfo) Reset() {
	*x = GpsSatInfo{}
	mi := &file_metric_state_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsSatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsSatInfo) ProtoMessage() {}

func (x *GpsSatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsSatInfo.ProtoReflect.Descriptor instead.
func (*GpsSatInfo) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GpsSatInfo) GetPrn() uint32 {
	if x != nil {
		return x.Prn
	}
	return 0
}

func (x *GpsSatInfo) GetElev() int32 {
	if x != nil {
		return x.Elev
	}
	return 0
}

func (x *GpsSatInfo) GetAzim() uint32 {
	if x != nil {
		return x.Azim
	}
	return 0
}

func (x *GpsSatInfo) GetSnr() uint32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

type GpsTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float32                `protobuf:"fixed32,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Spd           float32                `protobuf:"fixed32,4,opt,name=spd,proto3" json:"spd,omitempty"`
	Hdop          float32                `protobuf:"fixed32,5,opt,name=hdop,proto3" json:"hdop,omitempty"`
	Valid         bool                   `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	Satellites    uint32                 `protobuf:"varint,7,opt,name=satellites,proto3" json:"satellites,omitempty"` // GGA tracked count (legacy)
	Pdop          float32                `protobuf:"fixed32,8,opt,name=pdop,proto3" json:"pdop,omitempty"`
	AvgCnr        uint32                 `protobuf:"varint,9,opt,name=avg_cnr,json=avgCnr,proto3" json:"avg_cnr,omitempty"`
	Quality       uint32                 `protobuf:"varint,10,opt,name=quality,proto3" json:"quality,omitempty"`
	Navmode       uint32                 `protobuf:"varint,11,opt,name=navmode,proto3" json:"navmode,omitempty"`
	Heading       float32                `protobuf:"fixed32,12,opt,name=heading,proto3" json:"heading,omitempty"`                          // RMC course over ground, degrees
	SatsInView    uint32                 `protobuf:"varint,13,opt,name=sats_in_view,json=satsInView,proto3" json:"sats_in_view,omitempty"` // GSV structured count
	SatsUsed      uint32                 `protobuf:"varint,14,opt,name=sats_used,json=satsUsed,proto3" json:"sats_used,omitempty"`         // GSA used-PRN count
	UsedPrns      []uint32               `protobuf:"varint,15,rep,packed,name=used_prns,json=usedPrns,proto3" json:"used_prns,omitempty"`
	Sats          []*GpsSatInfo          `protobuf:"bytes,16,rep,name=sats,proto3" json:"sats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsTelemetry) Reset() {
	*x = GpsTelemetry{}
	mi := &file_metric_state_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsTelemetry) ProtoMessage() {}

func (x *GpsTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsTelemetry.ProtoReflect.Descriptor instead.
func (*GpsTelemetry) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GpsTelemetry) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GpsTelemetry) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GpsTelemetry) GetAlt() float32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *GpsTelemetry) GetSpd() float32 {
	if x != nil {
		return x.Spd
	}
	return 0
}

func (x *GpsTelemetry) GetHdop() float32 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *GpsTelemetry) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GpsTelemetry) GetSatellites() uint32 {
	if x != nil {
		return x.Satellites
	}
	return 0
}

func (x *GpsTelemetry) GetPdop() float32 {
	if x != nil {
		return x.Pdop
	}
	return 0
}

func (x *GpsTelemetry) GetAvgCnr() uint32 {
	if x != nil {
		return x.AvgCnr
	}
	return 0
}

func (x *GpsTelemetry) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *GpsTelemetry) GetNavmode() uint32 {
	if x != nil {
		return x.Navmode
	}
	return 0
}

func (x *GpsTelemetry) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *GpsTelemetry) GetSatsInView() uint32 {
	if x != nil {
		return x.SatsInView
	}
	return 0
}

func (x *GpsTelemetry) GetSatsUsed() uint32 {
	if x != nil {
		return x.SatsUsed
	}
	return 0
}

func (x *GpsTelemetry) GetUsedPrns() []uint32 {
	if x != nil {
		return x.UsedPrns
	}
	return nil
}

func (x *GpsTelemetry) GetSats() []*GpsSatInfo {
	if x != nil {
		return x.Sats
	}
	return nil
}

type DeviceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Imei          string                 `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	CpuUid        string                 `protobuf:"bytes,4,opt,name=cpu_uid,json=cpuUid,proto3" json:"cpu_uid,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	FwVersion     string                 `protobuf:"bytes,6,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIdentity) Reset() {
	*x = DeviceIdentity{}
	mi := &file_metric_state_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIdentity) ProtoMessage() {}

func (x *DeviceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIdentity.ProtoReflect.Descriptor instead.
func (*DeviceIdentity) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceIdentity) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceIdentity) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceIdentity) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceIdentity) GetCpuUid() string {
	if x != nil {
		return x.CpuUid
	}
	return ""
}

func (x *DeviceIdentity) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceIdentity) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

type FotaConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageUrl    string                 `protobuf:"bytes,1,opt,name=package_url,json=packageUrl,proto3" json:"package_url,omitempty"`
	TargetVersion string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FotaConfig) Reset() {
	*x = FotaConfig{}
	mi := &file_metric_state_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FotaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FotaConfig) ProtoMessage() {}

func (x *FotaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FotaConfig.ProtoReflect.Descriptor instead.
func (*FotaConfig) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{3}
}

func (x *FotaConfig) GetPackageUrl() string {
	if x != nil {
		return x.PackageUrl
	}
	return ""
}

func (x *FotaConfig) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *FotaConfig) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeviceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*DeviceConfig_Fota
	Body          isDeviceConfig_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfig) Reset() {
	*x = DeviceConfig{}
	mi := &file_metric_state_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfig) ProtoMessage() {}

func (x *DeviceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfig.ProtoReflect.Descriptor instead.
func (*DeviceConfig) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceConfig) GetBody() isDeviceConfig_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DeviceConfig) GetFota() *FotaConfig {
	if x != nil {
		if x, ok := x.Body.(*DeviceConfig_Fota); ok {
			return x.Fota
		}
	}
	return nil
}

type isDeviceConfig_Body interface {
	isDeviceConfig_Body()
}

type DeviceConfig_Fota struct {
	Fota *FotaConfig `protobuf:"bytes,1,opt,name=fota,proto3,oneof"`
}

func (*DeviceConfig_Fota) isDeviceConfig_Body() {}

type DeviceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          DeviceCommand_Type     `protobuf:"varint,2,opt,name=type,proto3,enum=metric_state_v1.DeviceCommand_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCommand) Reset() {
	*x = DeviceCommand{}
	mi := &file_metric_state_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommand) ProtoMessage() {}

func (x *DeviceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommand.ProtoReflect.Descriptor instead.
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DeviceCommand) GetType() DeviceCommand_Type {
	if x != nil {
		return x.Type
	}
	return DeviceCommand_UNSPECIFIED
}

type FotaStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           FotaStatus_State       `protobuf:"varint,1,opt,name=state,proto3,enum=metric_state_v1.FotaStatus_State" json:"state,omitempty"`
	ProgressPercent uint32                 `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Detail          string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	CurrentVersion  string                 `protobuf:"bytes,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	TargetVersion   string                 `protobuf:"bytes,5,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FotaStatus) Reset() {
	*x = FotaStatus{}
	mi := &file_metric_state_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FotaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FotaStatus) ProtoMessage() {}

func (x *FotaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FotaStatus.ProtoReflect.Descriptor instead.
func (*FotaStatus) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{6}
}

func (x *FotaStatus) GetState() FotaStatus_State {
	if x != nil {
		return x.State
	}
	return FotaStatus_IDLE
}

func (x *FotaStatus) GetProgressPercent() uint32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *FotaStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *FotaStatus) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *FotaStatus) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorCode     uint32                 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_metric_state_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{7}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandAck) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CommandAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp uint32                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Seq       uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Kind      MessageKind            `protobuf:"varint,3,opt,name=kind,proto3,enum=metric_state_v1.MessageKind" json:"kind,omitempty"`
	Identity  *DeviceIdentity        `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Gps
	//	*Envelope_Hello
	//	*Envelope_FotaStatus
	//	*Envelope_CommandAck
	//	*Envelope_Config
	//	*Envelope_Command
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_metric_state_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_metric_state_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_metric_state_v1_proto_rawDescGZIP(), []int{8}
}

func (x *Envelope) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_KIND_UNSPECIFIED
}

func (x *Envelope) GetIdentity() *DeviceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetGps() *GpsTelemetry {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Gps); ok {
			return x.Gps
		}
	}
	return nil
}

func (x *Envelope) GetHello() *DeviceIdentity {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetFotaStatus() *FotaStatus {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FotaStatus); ok {
			return x.FotaStatus
		}
	}
	return nil
}

func (x *Envelope) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *Envelope) GetConfig() *DeviceConfig {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *Envelope) GetCommand() *DeviceCommand {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Gps struct {
	Gps *GpsTelemetry `protobuf:"bytes,10,opt,name=gps,proto3,oneof"`
}

type Envelope_Hello struct {
	Hello *DeviceIdentity `protobuf:"bytes,11,opt,name=hello,proto3,oneof"`
}

type Envelope_FotaStatus struct {
	FotaStatus *FotaStatus `protobuf:"bytes,12,opt,name=fota_status,json=fotaStatus,proto3,oneof"`
}

type Envelope_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,13,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type Envelope_Config struct {
	Config *DeviceConfig `protobuf:"bytes,20,opt,name=config,proto3,oneof"`
}

type Envelope_Command struct {
	Command *DeviceCommand `protobuf:"bytes,21,opt,name=command,proto3,oneof"`
}

func (*Envelope_Gps) isEnvelope_Payload() {}

func (*Envelope_Hello) isEnvelope_Payload() {}

func (*Envelope_FotaStatus) isEnvelope_Payload() {}

func (*Envelope_CommandAck) isEnvelope_Payload() {}

func (*Envelope_Config) isEnvelope_Payload() {}

func (*Envelope_Command) isEnvelope_Payload() {}

var File_metric_state_v1_proto protoreflect.FileDescriptor

const file_metric_state_v1_proto_rawDesc = "" +
	"\n" +
	"\x15metric_state_v1.proto\x12\x0fmetric_state_v1\"X\n" +
	"\n" +
	"GpsSatInfo\x12\x10\n" +
	"\x03prn\x18\x01 \x01(\rR\x03prn\x12\x12\n" +
	"\x04elev\x18\x02 \x01(\x11R\x04elev\x12\x12\n" +
	"\x04azim\x18\x03 \x01(\rR\x04azim\x12\x10\n" +
	"\x03snr\x18\x04 \x01(\rR\x03snr\"\xa8\x03\n" +
	"\fGpsTelemetry\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x02R\x03alt\x12\x10\n" +
	"\x03spd\x18\x04 \x01(\x02R\x03spd\x12\x12\n" +
	"\x04hdop\x18\x05 \x01(\x02R\x04hdop\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\bR\x05valid\x12\x1e\n" +
	"\n" +
	"satellites\x18\a \x01(\rR\n" +
	"satellites\x12\x12\n" +
	"\x04pdop\x18\b \x01(\x02R\x04pdop\x12\x17\n" +
	"\aavg_cnr\x18\t \x01(\rR\x06avgCnr\x12\x18\n" +
	"\aquality\x18\n" +
	" \x01(\rR\aquality\x12\x18\n" +
	"\anavmode\x18\v \x01(\rR\anavmode\x12\x18\n" +
	"\aheading\x18\f \x01(\x02R\aheading\x12 \n" +
	"\fsats_in_view\x18\r \x01(\rR\n" +
	"satsInView\x12\x1b\n" +
	"\tsats_used\x18\x0e \x01(\rR\bsatsUsed\x12\x1b\n" +
	"\tused_prns\x18\x0f \x03(\rR\busedPrns\x12/\n" +
	"\x04sats\x18\x10 \x03(\v2\x1b.metric_state_v1.GpsSatInfoR\x04sats\"\xa7\x01\n" +
	"\x0eDeviceIdentity\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04imei\x18\x02 \x01(\tR\x04imei\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x17\n" +
	"\acpu_uid\x18\x04 \x01(\tR\x06cpuUid\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x06 \x01(\tR\tfwVersion\"j\n" +
	"\n" +
	"FotaConfig\x12\x1f\n" +
	"\vpackage_url\x18\x01 \x01(\tR\n" +
	"packageUrl\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"I\n" +
	"\fDeviceConfig\x121\n" +
	"\x04fota\x18\x01 \x01(\v2\x1b.metric_state_v1.FotaConfigH\x00R\x04fotaB\x06\n" +
	"\x04body\"\x9a\x01\n" +
	"\rDeviceCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.metric_state_v1.DeviceCommand.TypeR\x04type\"1\n" +
	"\x04Type\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06REBOOT\x10\x01\x12\f\n" +
	"\bSEND_SMS\x10\x02\"\xb2\x02\n" +
	"\n" +
	"FotaStatus\x127\n" +
	"\x05state\x18\x01 \x01(\x0e2!.metric_state_v1.FotaStatus.StateR\x05state\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\rR\x0fprogressPercent\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12'\n" +
	"\x0fcurrent_version\x18\x04 \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0etarget_version\x18\x05 \x01(\tR\rtargetVersion\"X\n" +
	"\x05State\x12\b\n" +
	"\x04IDLE\x10\x00\x12\x0f\n" +
	"\vDOWNLOADING\x10\x01\x12\r\n" +
	"\tVERIFYING\x10\x02\x12\f\n" +
	"\bAPPLYING\x10\x03\x12\v\n" +
	"\aSUCCESS\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\"r\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\rR\terrorCode\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\x95\x04\n" +
	"\bEnvelope\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\rR\ttimestamp\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.metric_state_v1.MessageKindR\x04kind\x12;\n" +
	"\bidentity\x18\x04 \x01(\v2\x1f.metric_state_v1.DeviceIdentityR\bidentity\x121\n" +
	"\x03gps\x18\n" +
	" \x01(\v2\x1d.metric_state_v1.GpsTelemetryH\x00R\x03gps\x127\n" +
	"\x05hello\x18\v \x01(\v2\x1f.metric_state_v1.DeviceIdentityH\x00R\x05hello\x12>\n" +
	"\vfota_status\x18\f \x01(\v2\x1b.metric_state_v1.FotaStatusH\x00R\n" +
	"fotaStatus\x12>\n" +
	"\vcommand_ack\x18\r \x01(\v2\x1b.metric_state_v1.CommandAckH\x00R\n" +
	"commandAck\x127\n" +
	"\x06config\x18\x14 \x01(\v2\x1d.metric_state_v1.DeviceConfigH\x00R\x06config\x12:\n" +
	"\acommand\x18\x15 \x01(\v2\x1e.metric_state_v1.DeviceCommandH\x00R\acommandB\t\n" +
	"\apayload*\x86\x01\n" +
	"\vMessageKind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTELEMETRY_GPS\x10\x01\x12\x13\n" +
	"\x0fDEVICE_IDENTITY\x10\x02\x12\x0f\n" +
	"\vFOTA_STATUS\x10\x03\x12\x0f\n" +
	"\vCOMMAND_ACK\x10\x04\x12\n" +
	"\n" +
	"\x06CONFIG\x10\n" +
	"\x12\v\n" +
	"\aCOMMAND\x10\vBBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_metric_state_v1_proto_rawDescOnce sync.Once
	file_metric_state_v1_proto_rawDescData []byte
)

func file_metric_state_v1_proto_rawDescGZIP() []byte {
	file_metric_state_v1_proto_rawDescOnce.Do(func() {
		file_metric_state_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_state_v1_proto_rawDesc), len(file_metric_state_v1_proto_rawDesc)))
	})
	return file_metric_state_v1_proto_rawDescData
}

var file_metric_state_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_metric_state_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_metric_state_v1_proto_goTypes = []any{
	(MessageKind)(0),        // 0: metric_state_v1.MessageKind
	(DeviceCommand_Type)(0), // 1: metric_state_v1.DeviceCommand.Type
	(FotaStatus_State)(0),   // 2: metric_state_v1.FotaStatus.State
	(*GpsSatInfo)(nil),      // 3: metric_state_v1.GpsSatInfo
	(*GpsTelemetry)(nil),    // 4: metric_state_v1.GpsTelemetry
	(*DeviceIdentity)(nil),  // 5: metric_state_v1.DeviceIdentity
	(*FotaConfig)(nil),      // 6: metric_state_v1.FotaConfig
	(*DeviceConfig)(nil),    // 7: metric_state_v1.DeviceConfig
	(*DeviceCommand)(nil),   // 8: metric_state_v1.DeviceCommand
	(*FotaStatus)(nil),      // 9: metric_state_v1.FotaStatus
	(*CommandAck)(nil),      // 10: metric_state_v1.CommandAck
	(*Envelope)(nil),        // 11: metric_state_v1.Envelope
}
var file_metric_state_v1_proto_depIdxs = []int32{
	3,  // 0: metric_state_v1.GpsTelemetry.sats:type_name -> metric_state_v1.GpsSatInfo
	6,  // 1: metric_state_v1.DeviceConfig.fota:type_name -> metric_state_v1.FotaConfig
	1,  // 2: metric_state_v1.DeviceCommand.type:type_name -> metric_state_v1.DeviceCommand.Type
	2,  // 3: metric_state_v1.FotaStatus.state:type_name -> metric_state_v1.FotaStatus.State
	0,  // 4: metric_state_v1.Envelope.kind:type_name -> metric_state_v1.MessageKind
	5,  // 5: metric_state_v1.Envelope.identity:type_name -> metric_state_v1.DeviceIdentity
	4,  // 6: metric_state_v1.Envelope.gps:type_name -> metric_state_v1.GpsTelemetry
	5,  // 7: metric_state_v1.Envelope.hello:type_name -> metric_state_v1.DeviceIdentity
	9,  // 8: metric_state_v1.Envelope.fota_status:type_name -> metric_state_v1.FotaStatus
	10, // 9: metric_state_v1.Envelope.command_ack:type_name -> metric_state_v1.CommandAck
	7,  // 10: metric_state_v1.Envelope.config:type_name -> metric_state_v1.DeviceConfig
	8,  // 11: metric_state_v1.Envelope.command:type_name -> metric_state_v1.DeviceCommand
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_metric_state_v1_proto_init() }
func file_metric_state_v1_proto_init() {
	if File_metric_state_v1_proto != nil {
		return
	}
	file_metric_state_v1_proto_msgTypes[4].OneofWrappers = []any{
		(*DeviceConfig_Fota)(nil),
	}
	file_metric_state_v1_proto_msgTypes[8].OneofWrappers = []any{
		(*Envelope_Gps)(nil),
		(*Envelope_Hello)(nil),
		(*Envelope_FotaStatus)(nil),
		(*Envelope_CommandAck)(nil),
		(*Envelope_Config)(nil),
		(*Envelope_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_state_v1_proto_rawDesc), len(file_metric_state_v1_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metric_state_v1_proto_goTypes,
		DependencyIndexes: file_metric_state_v1_proto_depIdxs,
		EnumInfos:         file_metric_state_v1_proto_enumTypes,
		MessageInfos:      file_metric_state_v1_proto_msgTypes,
	}.Build()
	File_metric_state_v1_proto = out.File
	file_metric_state_v1_proto_goTypes = nil
	file_metric_state_v1_proto_depIdxs = nil
}
