// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: device.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeviceByIMEIReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceImei    string                 `protobuf:"bytes,1,opt,name=device_imei,json=deviceImei,proto3" json:"device_imei,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByIMEIReq) Reset() {
	*x = GetDeviceByIMEIReq{}
	mi := &file_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByIMEIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByIMEIReq) ProtoMessage() {}

func (x *GetDeviceByIMEIReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByIMEIReq.ProtoReflect.Descriptor instead.
func (*GetDeviceByIMEIReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceByIMEIReq) GetDeviceImei() string {
	if x != nil {
		return x.DeviceImei
	}
	return ""
}

type GetDeviceByIMEIRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Imei          string                 `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	SimNum        string                 `protobuf:"bytes,4,opt,name=sim_num,json=simNum,proto3" json:"sim_num,omitempty"`
	Barcode       string                 `protobuf:"bytes,5,opt,name=barcode,proto3" json:"barcode,omitempty"`
	VehicleId     int64                  `protobuf:"varint,6,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	DeviceModelId int64                  `protobuf:"varint,7,opt,name=device_model_id,json=deviceModelId,proto3" json:"device_model_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ActivatedAt   string                 `protobuf:"bytes,9,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByIMEIRes) Reset() {
	*x = GetDeviceByIMEIRes{}
	mi := &file_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByIMEIRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByIMEIRes) ProtoMessage() {}

func (x *GetDeviceByIMEIRes) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByIMEIRes.ProtoReflect.Descriptor instead.
func (*GetDeviceByIMEIRes) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeviceByIMEIRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDeviceByIMEIRes) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *GetDeviceByIMEIRes) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetDeviceByIMEIRes) GetSimNum() string {
	if x != nil {
		return x.SimNum
	}
	return ""
}

func (x *GetDeviceByIMEIRes) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *GetDeviceByIMEIRes) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *GetDeviceByIMEIRes) GetDeviceModelId() int64 {
	if x != nil {
		return x.DeviceModelId
	}
	return 0
}

func (x *GetDeviceByIMEIRes) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetDeviceByIMEIRes) GetActivatedAt() string {
	if x != nil {
		return x.ActivatedAt
	}
	return ""
}

func (x *GetDeviceByIMEIRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetDeviceByIMEIRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetCommandByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandByIDReq) Reset() {
	*x = GetCommandByIDReq{}
	mi := &file_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandByIDReq) ProtoMessage() {}

func (x *GetCommandByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandByIDReq.ProtoReflect.Descriptor instead.
func (*GetCommandByIDReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommandByIDReq) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type GetCommandByIDRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommandType       int64                  `protobuf:"varint,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Status            int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	DeviceId          int64                  `protobuf:"varint,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	VehicleId         int64                  `protobuf:"varint,5,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Payload           string                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	FailedDescription string                 `protobuf:"bytes,7,opt,name=failed_description,json=failedDescription,proto3" json:"failed_description,omitempty"`
	ExpireAt          string                 `protobuf:"bytes,8,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCommandByIDRes) Reset() {
	*x = GetCommandByIDRes{}
	mi := &file_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandByIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandByIDRes) ProtoMessage() {}

func (x *GetCommandByIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandByIDRes.ProtoReflect.Descriptor instead.
func (*GetCommandByIDRes) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommandByIDRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCommandByIDRes) GetCommandType() int64 {
	if x != nil {
		return x.CommandType
	}
	return 0
}

func (x *GetCommandByIDRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCommandByIDRes) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GetCommandByIDRes) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *GetCommandByIDRes) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GetCommandByIDRes) GetFailedDescription() string {
	if x != nil {
		return x.FailedDescription
	}
	return ""
}

func (x *GetCommandByIDRes) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *GetCommandByIDRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetCommandByIDRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_device_proto protoreflect.FileDescriptor

const file_device_proto_rawDesc = "" +
	"\n" +
	"\fdevice.proto\x12\x06device\"5\n" +
	"\x12GetDeviceByIMEIReq\x12\x1f\n" +
	"\vdevice_imei\x18\x01 \x01(\tR\n" +
	"deviceImei\"\xc2\x02\n" +
	"\x12GetDeviceByIMEIRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04imei\x18\x02 \x01(\tR\x04imei\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x17\n" +
	"\asim_num\x18\x04 \x01(\tR\x06simNum\x12\x18\n" +
	"\abarcode\x18\x05 \x01(\tR\abarcode\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x06 \x01(\x03R\tvehicleId\x12&\n" +
	"\x0fdevice_model_id\x18\a \x01(\x03R\rdeviceModelId\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12!\n" +
	"\factivated_at\x18\t \x01(\tR\vactivatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"2\n" +
	"\x11GetCommandByIDReq\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"\xbe\x02\n" +
	"\x11GetCommandByIDRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\x03R\vcommandType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\x03R\bdeviceId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x05 \x01(\x03R\tvehicleId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayload\x12-\n" +
	"\x12failed_description\x18\a \x01(\tR\x11failedDescription\x12\x1b\n" +
	"\texpire_at\x18\b \x01(\tR\bexpireAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt2\xa1\x01\n" +
	"\rDeviceService\x12H\n" +
	"\fDeviceByIMEI\x12\x1a.device.GetDeviceByIMEIReq\x1a\x1a.device.GetDeviceByIMEIRes\"\x00\x12F\n" +
	"\vCommandByID\x12\x19.device.GetCommandByIDReq\x1a\x1a.device.GetDeviceByIMEIRes\"\x00BBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData []byte
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)))
	})
	return file_device_proto_rawDescData
}

var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_device_proto_goTypes = []any{
	(*GetDeviceByIMEIReq)(nil), // 0: device.GetDeviceByIMEIReq
	(*GetDeviceByIMEIRes)(nil), // 1: device.GetDeviceByIMEIRes
	(*GetCommandByIDReq)(nil),  // 2: device.GetCommandByIDReq
	(*GetCommandByIDRes)(nil),  // 3: device.GetCommandByIDRes
}
var file_device_proto_depIdxs = []int32{
	0, // 0: device.DeviceService.DeviceByIMEI:input_type -> device.GetDeviceByIMEIReq
	2, // 1: device.DeviceService.CommandByID:input_type -> device.GetCommandByIDReq
	1, // 2: device.DeviceService.DeviceByIMEI:output_type -> device.GetDeviceByIMEIRes
	1, // 3: device.DeviceService.CommandByID:output_type -> device.GetDeviceByIMEIRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
