<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_gps_v1.proto

namespace GPBMetadata;

class SharedDGpsV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
shared_d_gps_v1.protodevice"B

GpsSatInfo
prn (
elev (
azim (
snr ("£
GpsTelemetry
lat (
lon (
alt (
spd (
hdop (
valid (

satellites (
pdop (
avg_cnr	 (
quality
 (
navmode (
heading (
sats_in_view (
	sats_used (
	used_prns ( 
sats (2.device.GpsSatInfo"5
	GpsConfig
post_unfixed (

field_mask (BFZDgithub.com/sepehrshrz/vehicle_common.grpc/genproto/d_gps_v1;d_gps_v1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

