<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_identity_v1.proto

namespace GPBMetadata;

class SharedDIdentityV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\SharedDCommonV1::initOnce();
        $pool->internalAddGeneratedFile(
            '
±
shared_d_identity_v1.protodevice"¢
DeviceIdentity
	device_id (	
imei (	
serial (	
cpu_uid (	
model (	

fw_version (	+
proto_versiond (2.device.ProtoVersionB^Z\\github.com/sepehrshrz/vehicle_common.grpc/genproto/shared_d_identity_v1;shared_d_identity_v1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

