<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_config_v1.proto

namespace GPBMetadata;

class SharedDConfigV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\SharedDCommonV1::initOnce();
        \GPBMetadata\DGpsV1::initOnce();
        \GPBMetadata\DVehicleV1::initOnce();
        \GPBMetadata\DTelemetryV1::initOnce();
        $pool->internalAddGeneratedFile(
            '
ì	
shared_d_config_v1.protodeviced_gps_v1.protod_vehicle_v1.protod_telemetry_v1.proto"8
NetworkConfig
apn (	
user (	
pass (	",
SmsRecipient
name (	
number (	"·
SmsNotificationConfig(

recipients (2.device.SmsRecipient
enabled (
enable_shock (
enable_acc_on (
enable_acc_off (
enable_door_open (
enable_door_close (
	msg_shock (	

msg_acc_on	 (	
msg_acc_off
 (	
msg_door_open (	
msg_door_close (	"
LoggingConfig
level ("…
DeviceConfiguration&
network (2.device.NetworkConfig*
sms (2.device.SmsNotificationConfig
gps (2.device.GpsConfig&
logging (2.device.LoggingConfig*
	telemetry (2.device.TelemetryConfig&
vehicle (2.device.VehicleConfig"ß
DeviceConfigurationUpdate%
header (2.device.CommandHeader&
network (2.device.NetworkConfig*
sms (2.device.SmsNotificationConfig
gps (2.device.GpsConfig&
logging (2.device.LoggingConfig&
vehicle (2.device.VehicleConfig*
	telemetry (2.device.TelemetryConfig+
proto_versiond (2.device.ProtoVersionBZZXgithub.com/sepehrshrz/vehicle_common.grpc/genproto/shared_d_config_v1;shared_d_config_v1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

