// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: d_telemetry_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MQTT root for ingest/telemetry/state (no Envelope).
type DeviceTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoVersion  ProtoVersion           `protobuf:"varint,1,opt,name=proto_version,json=protoVersion,proto3,enum=device.ProtoVersion" json:"proto_version,omitempty"`
	Identity      *DeviceIdentity        `protobuf:"bytes,2,opt,name=identity,proto3,oneof" json:"identity,omitempty"`
	Gps           *GpsTelemetry          `protobuf:"bytes,3,opt,name=gps,proto3,oneof" json:"gps,omitempty"`
	Vehicle       *VehicleStatus         `protobuf:"bytes,4,opt,name=vehicle,proto3,oneof" json:"vehicle,omitempty"`
	Timestamp     uint32                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Seq           uint32                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTelemetry) Reset() {
	*x = DeviceTelemetry{}
	mi := &file_d_telemetry_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTelemetry) ProtoMessage() {}

func (x *DeviceTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_d_telemetry_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTelemetry.ProtoReflect.Descriptor instead.
func (*DeviceTelemetry) Descriptor() ([]byte, []int) {
	return file_d_telemetry_v1_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceTelemetry) GetProtoVersion() ProtoVersion {
	if x != nil {
		return x.ProtoVersion
	}
	return ProtoVersion_PROTO_VERSION_UNSPECIFIED
}

func (x *DeviceTelemetry) GetIdentity() *DeviceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *DeviceTelemetry) GetGps() *GpsTelemetry {
	if x != nil {
		return x.Gps
	}
	return nil
}

func (x *DeviceTelemetry) GetVehicle() *VehicleStatus {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *DeviceTelemetry) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeviceTelemetry) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type TelemetryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ignored by firmware: DeviceTelemetry.identity is always sent.
	// Kept for config wire compatibility (do not renumber).
	IncludeIdentity bool `protobuf:"varint,1,opt,name=include_identity,json=includeIdentity,proto3" json:"include_identity,omitempty"`
	IncludeGps      bool `protobuf:"varint,2,opt,name=include_gps,json=includeGps,proto3" json:"include_gps,omitempty"`             // default true
	IncludeVehicle  bool `protobuf:"varint,3,opt,name=include_vehicle,json=includeVehicle,proto3" json:"include_vehicle,omitempty"` // default true
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryConfig) Reset() {
	*x = TelemetryConfig{}
	mi := &file_d_telemetry_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryConfig) ProtoMessage() {}

func (x *TelemetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_d_telemetry_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryConfig.ProtoReflect.Descriptor instead.
func (*TelemetryConfig) Descriptor() ([]byte, []int) {
	return file_d_telemetry_v1_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryConfig) GetIncludeIdentity() bool {
	if x != nil {
		return x.IncludeIdentity
	}
	return false
}

func (x *TelemetryConfig) GetIncludeGps() bool {
	if x != nil {
		return x.IncludeGps
	}
	return false
}

func (x *TelemetryConfig) GetIncludeVehicle() bool {
	if x != nil {
		return x.IncludeVehicle
	}
	return false
}

var File_d_telemetry_v1_proto protoreflect.FileDescriptor

const file_d_telemetry_v1_proto_rawDesc = "" +
	"\n" +
	"\x14d_telemetry_v1.proto\x12\x06device\x1a\x18shared_d_common_v1.proto\x1a\x0ed_gps_v1.proto\x1a\x12d_vehicle_v1.proto\x1a\x1ashared_d_identity_v1.proto\"\xb9\x02\n" +
	"\x0fDeviceTelemetry\x129\n" +
	"\rproto_version\x18\x01 \x01(\x0e2\x14.device.ProtoVersionR\fprotoVersion\x127\n" +
	"\bidentity\x18\x02 \x01(\v2\x16.device.DeviceIdentityH\x00R\bidentity\x88\x01\x01\x12+\n" +
	"\x03gps\x18\x03 \x01(\v2\x14.device.GpsTelemetryH\x01R\x03gps\x88\x01\x01\x124\n" +
	"\avehicle\x18\x04 \x01(\v2\x15.device.VehicleStatusH\x02R\avehicle\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\rR\ttimestamp\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\rR\x03seqB\v\n" +
	"\t_identityB\x06\n" +
	"\x04_gpsB\n" +
	"\n" +
	"\b_vehicle\"\x86\x01\n" +
	"\x0fTelemetryConfig\x12)\n" +
	"\x10include_identity\x18\x01 \x01(\bR\x0fincludeIdentity\x12\x1f\n" +
	"\vinclude_gps\x18\x02 \x01(\bR\n" +
	"includeGps\x12'\n" +
	"\x0finclude_vehicle\x18\x03 \x01(\bR\x0eincludeVehicleBBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_d_telemetry_v1_proto_rawDescOnce sync.Once
	file_d_telemetry_v1_proto_rawDescData []byte
)

func file_d_telemetry_v1_proto_rawDescGZIP() []byte {
	file_d_telemetry_v1_proto_rawDescOnce.Do(func() {
		file_d_telemetry_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_d_telemetry_v1_proto_rawDesc), len(file_d_telemetry_v1_proto_rawDesc)))
	})
	return file_d_telemetry_v1_proto_rawDescData
}

var file_d_telemetry_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_d_telemetry_v1_proto_goTypes = []any{
	(*DeviceTelemetry)(nil), // 0: device.DeviceTelemetry
	(*TelemetryConfig)(nil), // 1: device.TelemetryConfig
	(ProtoVersion)(0),       // 2: device.ProtoVersion
	(*DeviceIdentity)(nil),  // 3: device.DeviceIdentity
	(*GpsTelemetry)(nil),    // 4: device.GpsTelemetry
	(*VehicleStatus)(nil),   // 5: device.VehicleStatus
}
var file_d_telemetry_v1_proto_depIdxs = []int32{
	2, // 0: device.DeviceTelemetry.proto_version:type_name -> device.ProtoVersion
	3, // 1: device.DeviceTelemetry.identity:type_name -> device.DeviceIdentity
	4, // 2: device.DeviceTelemetry.gps:type_name -> device.GpsTelemetry
	5, // 3: device.DeviceTelemetry.vehicle:type_name -> device.VehicleStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_d_telemetry_v1_proto_init() }
func file_d_telemetry_v1_proto_init() {
	if File_d_telemetry_v1_proto != nil {
		return
	}
	file_shared_d_common_v1_proto_init()
	file_d_gps_v1_proto_init()
	file_d_vehicle_v1_proto_init()
	file_shared_d_identity_v1_proto_init()
	file_d_telemetry_v1_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_d_telemetry_v1_proto_rawDesc), len(file_d_telemetry_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_d_telemetry_v1_proto_goTypes,
		DependencyIndexes: file_d_telemetry_v1_proto_depIdxs,
		MessageInfos:      file_d_telemetry_v1_proto_msgTypes,
	}.Build()
	File_d_telemetry_v1_proto = out.File
	file_d_telemetry_v1_proto_goTypes = nil
	file_d_telemetry_v1_proto_depIdxs = nil
}
