// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shared_d_command_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandStatus int32

const (
	CommandStatus_CMD_UNSPECIFIED CommandStatus = 0
	CommandStatus_CMD_ACCEPTED    CommandStatus = 1 // long job queued (FOTA)
	CommandStatus_CMD_OK          CommandStatus = 2
	CommandStatus_CMD_FAILED      CommandStatus = 3
	CommandStatus_CMD_UNSUPPORTED CommandStatus = 4
	CommandStatus_CMD_EXPIRED     CommandStatus = 5
	CommandStatus_CMD_BUSY        CommandStatus = 6
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "CMD_UNSPECIFIED",
		1: "CMD_ACCEPTED",
		2: "CMD_OK",
		3: "CMD_FAILED",
		4: "CMD_UNSUPPORTED",
		5: "CMD_EXPIRED",
		6: "CMD_BUSY",
	}
	CommandStatus_value = map[string]int32{
		"CMD_UNSPECIFIED": 0,
		"CMD_ACCEPTED":    1,
		"CMD_OK":          2,
		"CMD_FAILED":      3,
		"CMD_UNSUPPORTED": 4,
		"CMD_EXPIRED":     5,
		"CMD_BUSY":        6,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_d_command_v1_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_shared_d_command_v1_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_CMD_TYPE_UNSPECIFIED CommandType = 0
	CommandType_CMD_ECHO             CommandType = 1
	CommandType_CMD_REBOOT           CommandType = 2
	CommandType_CMD_FOTA             CommandType = 3
	CommandType_CMD_GET_CONFIG       CommandType = 4
	CommandType_CMD_ENGINE           CommandType = 5 // EngineParams.on: true=engine on, false=engine off
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "CMD_TYPE_UNSPECIFIED",
		1: "CMD_ECHO",
		2: "CMD_REBOOT",
		3: "CMD_FOTA",
		4: "CMD_GET_CONFIG",
		5: "CMD_ENGINE",
	}
	CommandType_value = map[string]int32{
		"CMD_TYPE_UNSPECIFIED": 0,
		"CMD_ECHO":             1,
		"CMD_REBOOT":           2,
		"CMD_FOTA":             3,
		"CMD_GET_CONFIG":       4,
		"CMD_ENGINE":           5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_d_command_v1_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_shared_d_command_v1_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{1}
}

type EchoParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoParams) Reset() {
	*x = EchoParams{}
	mi := &file_shared_d_command_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoParams) ProtoMessage() {}

func (x *EchoParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_command_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoParams.ProtoReflect.Descriptor instead.
func (*EchoParams) Descriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{0}
}

func (x *EchoParams) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RebootParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMs       uint32                 `protobuf:"varint,1,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootParams) Reset() {
	*x = RebootParams{}
	mi := &file_shared_d_command_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootParams) ProtoMessage() {}

func (x *RebootParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_command_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootParams.ProtoReflect.Descriptor instead.
func (*RebootParams) Descriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RebootParams) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type FotaParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageUrl    string                 `protobuf:"bytes,1,opt,name=package_url,json=packageUrl,proto3" json:"package_url,omitempty"`
	TargetVersion string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"` // exactly 32 bytes; required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FotaParams) Reset() {
	*x = FotaParams{}
	mi := &file_shared_d_command_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FotaParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FotaParams) ProtoMessage() {}

func (x *FotaParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_command_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FotaParams.ProtoReflect.Descriptor instead.
func (*FotaParams) Descriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{2}
}

func (x *FotaParams) GetPackageUrl() string {
	if x != nil {
		return x.PackageUrl
	}
	return ""
}

func (x *FotaParams) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *FotaParams) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *FotaParams) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// Which blocks to return. All false => return every known block.
type GetConfigParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       bool                   `protobuf:"varint,1,opt,name=network,proto3" json:"network,omitempty"`
	Sms           bool                   `protobuf:"varint,2,opt,name=sms,proto3" json:"sms,omitempty"`
	Gps           bool                   `protobuf:"varint,3,opt,name=gps,proto3" json:"gps,omitempty"`
	Logging       bool                   `protobuf:"varint,4,opt,name=logging,proto3" json:"logging,omitempty"`
	Vehicle       bool                   `protobuf:"varint,5,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Telemetry     bool                   `protobuf:"varint,6,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigParams) Reset() {
	*x = GetConfigParams{}
	mi := &file_shared_d_command_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigParams) ProtoMessage() {}

func (x *GetConfigParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_command_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigParams.ProtoReflect.Descriptor instead.
func (*GetConfigParams) Descriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigParams) GetNetwork() bool {
	if x != nil {
		return x.Network
	}
	return false
}

func (x *GetConfigParams) GetSms() bool {
	if x != nil {
		return x.Sms
	}
	return false
}

func (x *GetConfigParams) GetGps() bool {
	if x != nil {
		return x.Gps
	}
	return false
}

func (x *GetConfigParams) GetLogging() bool {
	if x != nil {
		return x.Logging
	}
	return false
}

func (x *GetConfigParams) GetVehicle() bool {
	if x != nil {
		return x.Vehicle
	}
	return false
}

func (x *GetConfigParams) GetTelemetry() bool {
	if x != nil {
		return x.Telemetry
	}
	return false
}

type EngineParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	On            bool                   `protobuf:"varint,1,opt,name=on,proto3" json:"on,omitempty"` // true = engine on, false = engine off
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineParams) Reset() {
	*x = EngineParams{}
	mi := &file_shared_d_command_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineParams) ProtoMessage() {}

func (x *EngineParams) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_command_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineParams.ProtoReflect.Descriptor instead.
func (*EngineParams) Descriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{4}
}

func (x *EngineParams) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

// MQTT root for device/{id}/command
type DeviceCommand struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *CommandHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type   CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=device.CommandType" json:"type,omitempty"`
	// Serialized EchoParams | RebootParams | FotaParams | GetConfigParams | EngineParams
	Params        []byte       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	ProtoVersion  ProtoVersion `protobuf:"varint,100,opt,name=proto_version,json=protoVersion,proto3,enum=device.ProtoVersion" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCommand) Reset() {
	*x = DeviceCommand{}
	mi := &file_shared_d_command_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommand) ProtoMessage() {}

func (x *DeviceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_command_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommand.ProtoReflect.Descriptor instead.
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceCommand) GetHeader() *CommandHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeviceCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_CMD_TYPE_UNSPECIFIED
}

func (x *DeviceCommand) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DeviceCommand) GetProtoVersion() ProtoVersion {
	if x != nil {
		return x.ProtoVersion
	}
	return ProtoVersion_PROTO_VERSION_UNSPECIFIED
}

// MQTT root for ingest/telemetry/ack
type CommandResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Header    *CommandHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status    CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=device.CommandStatus" json:"status,omitempty"`
	ErrorCode uint32                 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CommandResponse_Config
	Result        isCommandResponse_Result `protobuf_oneof:"result"`
	ProtoVersion  ProtoVersion             `protobuf:"varint,100,opt,name=proto_version,json=protoVersion,proto3,enum=device.ProtoVersion" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_shared_d_command_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_d_command_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_shared_d_command_v1_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetHeader() *CommandHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CommandResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_CMD_UNSPECIFIED
}

func (x *CommandResponse) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetResult() isCommandResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResponse) GetConfig() *DeviceConfiguration {
	if x != nil {
		if x, ok := x.Result.(*CommandResponse_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *CommandResponse) GetProtoVersion() ProtoVersion {
	if x != nil {
		return x.ProtoVersion
	}
	return ProtoVersion_PROTO_VERSION_UNSPECIFIED
}

type isCommandResponse_Result interface {
	isCommandResponse_Result()
}

type CommandResponse_Config struct {
	Config *DeviceConfiguration `protobuf:"bytes,10,opt,name=config,proto3,oneof"`
}

func (*CommandResponse_Config) isCommandResponse_Result() {}

var File_shared_d_command_v1_proto protoreflect.FileDescriptor

const file_shared_d_command_v1_proto_rawDesc = "" +
	"\n" +
	"\x19shared_d_command_v1.proto\x12\x06device\x1a\x18shared_d_common_v1.proto\x1a\x18shared_d_config_v1.proto\"&\n" +
	"\n" +
	"EchoParams\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\fRebootParams\x12\x19\n" +
	"\bdelay_ms\x18\x01 \x01(\rR\adelayMs\"\x82\x01\n" +
	"\n" +
	"FotaParams\x12\x1f\n" +
	"\vpackage_url\x18\x01 \x01(\tR\n" +
	"packageUrl\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\"\xa1\x01\n" +
	"\x0fGetConfigParams\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\bR\anetwork\x12\x10\n" +
	"\x03sms\x18\x02 \x01(\bR\x03sms\x12\x10\n" +
	"\x03gps\x18\x03 \x01(\bR\x03gps\x12\x18\n" +
	"\alogging\x18\x04 \x01(\bR\alogging\x12\x18\n" +
	"\avehicle\x18\x05 \x01(\bR\avehicle\x12\x1c\n" +
	"\ttelemetry\x18\x06 \x01(\bR\ttelemetry\"\x1e\n" +
	"\fEngineParams\x12\x0e\n" +
	"\x02on\x18\x01 \x01(\bR\x02on\"\xba\x01\n" +
	"\rDeviceCommand\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.device.CommandHeaderR\x06header\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.device.CommandTypeR\x04type\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x129\n" +
	"\rproto_version\x18d \x01(\x0e2\x14.device.ProtoVersionR\fprotoVersion\"\xa4\x02\n" +
	"\x0fCommandResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.device.CommandHeaderR\x06header\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.device.CommandStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\rR\terrorCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x125\n" +
	"\x06config\x18\n" +
	" \x01(\v2\x1b.device.DeviceConfigurationH\x00R\x06config\x129\n" +
	"\rproto_version\x18d \x01(\x0e2\x14.device.ProtoVersionR\fprotoVersionB\b\n" +
	"\x06result*\x86\x01\n" +
	"\rCommandStatus\x12\x13\n" +
	"\x0fCMD_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCMD_ACCEPTED\x10\x01\x12\n" +
	"\n" +
	"\x06CMD_OK\x10\x02\x12\x0e\n" +
	"\n" +
	"CMD_FAILED\x10\x03\x12\x13\n" +
	"\x0fCMD_UNSUPPORTED\x10\x04\x12\x0f\n" +
	"\vCMD_EXPIRED\x10\x05\x12\f\n" +
	"\bCMD_BUSY\x10\x06*w\n" +
	"\vCommandType\x12\x18\n" +
	"\x14CMD_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCMD_ECHO\x10\x01\x12\x0e\n" +
	"\n" +
	"CMD_REBOOT\x10\x02\x12\f\n" +
	"\bCMD_FOTA\x10\x03\x12\x12\n" +
	"\x0eCMD_GET_CONFIG\x10\x04\x12\x0e\n" +
	"\n" +
	"CMD_ENGINE\x10\x05BBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_shared_d_command_v1_proto_rawDescOnce sync.Once
	file_shared_d_command_v1_proto_rawDescData []byte
)

func file_shared_d_command_v1_proto_rawDescGZIP() []byte {
	file_shared_d_command_v1_proto_rawDescOnce.Do(func() {
		file_shared_d_command_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_d_command_v1_proto_rawDesc), len(file_shared_d_command_v1_proto_rawDesc)))
	})
	return file_shared_d_command_v1_proto_rawDescData
}

var file_shared_d_command_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shared_d_command_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shared_d_command_v1_proto_goTypes = []any{
	(CommandStatus)(0),          // 0: device.CommandStatus
	(CommandType)(0),            // 1: device.CommandType
	(*EchoParams)(nil),          // 2: device.EchoParams
	(*RebootParams)(nil),        // 3: device.RebootParams
	(*FotaParams)(nil),          // 4: device.FotaParams
	(*GetConfigParams)(nil),     // 5: device.GetConfigParams
	(*EngineParams)(nil),        // 6: device.EngineParams
	(*DeviceCommand)(nil),       // 7: device.DeviceCommand
	(*CommandResponse)(nil),     // 8: device.CommandResponse
	(*CommandHeader)(nil),       // 9: device.CommandHeader
	(ProtoVersion)(0),           // 10: device.ProtoVersion
	(*DeviceConfiguration)(nil), // 11: device.DeviceConfiguration
}
var file_shared_d_command_v1_proto_depIdxs = []int32{
	9,  // 0: device.DeviceCommand.header:type_name -> device.CommandHeader
	1,  // 1: device.DeviceCommand.type:type_name -> device.CommandType
	10, // 2: device.DeviceCommand.proto_version:type_name -> device.ProtoVersion
	9,  // 3: device.CommandResponse.header:type_name -> device.CommandHeader
	0,  // 4: device.CommandResponse.status:type_name -> device.CommandStatus
	11, // 5: device.CommandResponse.config:type_name -> device.DeviceConfiguration
	10, // 6: device.CommandResponse.proto_version:type_name -> device.ProtoVersion
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shared_d_command_v1_proto_init() }
func file_shared_d_command_v1_proto_init() {
	if File_shared_d_command_v1_proto != nil {
		return
	}
	file_shared_d_common_v1_proto_init()
	file_shared_d_config_v1_proto_init()
	file_shared_d_command_v1_proto_msgTypes[6].OneofWrappers = []any{
		(*CommandResponse_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_d_command_v1_proto_rawDesc), len(file_shared_d_command_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_d_command_v1_proto_goTypes,
		DependencyIndexes: file_shared_d_command_v1_proto_depIdxs,
		EnumInfos:         file_shared_d_command_v1_proto_enumTypes,
		MessageInfos:      file_shared_d_command_v1_proto_msgTypes,
	}.Build()
	File_shared_d_command_v1_proto = out.File
	file_shared_d_command_v1_proto_goTypes = nil
	file_shared_d_command_v1_proto_depIdxs = nil
}
