// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: d_vehicle_v1.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vehicle I/O. last_shock_at is sticky unix seconds (0 = never); notify when it
// increases. Device always sets presence (nanopb OPTIONAL) so false/0 appear
// on the wire whenever the vehicle block is included.
type VehicleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccActive     *bool                  `protobuf:"varint,1,opt,name=acc_active,json=accActive,proto3,oneof" json:"acc_active,omitempty"`    // ACC=1 active
	DoorActive    *bool                  `protobuf:"varint,2,opt,name=door_active,json=doorActive,proto3,oneof" json:"door_active,omitempty"` // door signal active (active-low pin)
	ShockLevel    *bool                  `protobuf:"varint,3,opt,name=shock_level,json=shockLevel,proto3,oneof" json:"shock_level,omitempty"` // current shock pin level
	EngineOn      *bool                  `protobuf:"varint,4,opt,name=engine_on,json=engineOn,proto3,oneof" json:"engine_on,omitempty"`
	BatMv         *uint32                `protobuf:"varint,5,opt,name=bat_mv,json=batMv,proto3,oneof" json:"bat_mv,omitempty"`
	LastShockAt   *uint32                `protobuf:"varint,6,opt,name=last_shock_at,json=lastShockAt,proto3,oneof" json:"last_shock_at,omitempty"`
	ReportedAt    *uint32                `protobuf:"varint,7,opt,name=reported_at,json=reportedAt,proto3,oneof" json:"reported_at,omitempty"` // unix sec of this sample; always set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleStatus) Reset() {
	*x = VehicleStatus{}
	mi := &file_d_vehicle_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatus) ProtoMessage() {}

func (x *VehicleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_d_vehicle_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleStatus.ProtoReflect.Descriptor instead.
func (*VehicleStatus) Descriptor() ([]byte, []int) {
	return file_d_vehicle_v1_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleStatus) GetAccActive() bool {
	if x != nil && x.AccActive != nil {
		return *x.AccActive
	}
	return false
}

func (x *VehicleStatus) GetDoorActive() bool {
	if x != nil && x.DoorActive != nil {
		return *x.DoorActive
	}
	return false
}

func (x *VehicleStatus) GetShockLevel() bool {
	if x != nil && x.ShockLevel != nil {
		return *x.ShockLevel
	}
	return false
}

func (x *VehicleStatus) GetEngineOn() bool {
	if x != nil && x.EngineOn != nil {
		return *x.EngineOn
	}
	return false
}

func (x *VehicleStatus) GetBatMv() uint32 {
	if x != nil && x.BatMv != nil {
		return *x.BatMv
	}
	return 0
}

func (x *VehicleStatus) GetLastShockAt() uint32 {
	if x != nil && x.LastShockAt != nil {
		return *x.LastShockAt
	}
	return 0
}

func (x *VehicleStatus) GetReportedAt() uint32 {
	if x != nil && x.ReportedAt != nil {
		return *x.ReportedAt
	}
	return 0
}

type VehicleConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PostPeriodMs uint32                 `protobuf:"varint,1,opt,name=post_period_ms,json=postPeriodMs,proto3" json:"post_period_ms,omitempty"` // state uplink interval when vehicle-driven (default 1000)
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // human-readable label, e.g. "Truck-12"
	// Ignored by firmware: all VehicleStatus fields are always sent.
	// Kept for config wire compatibility (do not renumber).
	FieldMask     uint32 `protobuf:"varint,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleConfig) Reset() {
	*x = VehicleConfig{}
	mi := &file_d_vehicle_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleConfig) ProtoMessage() {}

func (x *VehicleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_d_vehicle_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleConfig.ProtoReflect.Descriptor instead.
func (*VehicleConfig) Descriptor() ([]byte, []int) {
	return file_d_vehicle_v1_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleConfig) GetPostPeriodMs() uint32 {
	if x != nil {
		return x.PostPeriodMs
	}
	return 0
}

func (x *VehicleConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VehicleConfig) GetFieldMask() uint32 {
	if x != nil {
		return x.FieldMask
	}
	return 0
}

var File_d_vehicle_v1_proto protoreflect.FileDescriptor

const file_d_vehicle_v1_proto_rawDesc = "" +
	"\n" +
	"\x12d_vehicle_v1.proto\x12\x06device\"\xf6\x02\n" +
	"\rVehicleStatus\x12\"\n" +
	"\n" +
	"acc_active\x18\x01 \x01(\bH\x00R\taccActive\x88\x01\x01\x12$\n" +
	"\vdoor_active\x18\x02 \x01(\bH\x01R\n" +
	"doorActive\x88\x01\x01\x12$\n" +
	"\vshock_level\x18\x03 \x01(\bH\x02R\n" +
	"shockLevel\x88\x01\x01\x12 \n" +
	"\tengine_on\x18\x04 \x01(\bH\x03R\bengineOn\x88\x01\x01\x12\x1a\n" +
	"\x06bat_mv\x18\x05 \x01(\rH\x04R\x05batMv\x88\x01\x01\x12'\n" +
	"\rlast_shock_at\x18\x06 \x01(\rH\x05R\vlastShockAt\x88\x01\x01\x12$\n" +
	"\vreported_at\x18\a \x01(\rH\x06R\n" +
	"reportedAt\x88\x01\x01B\r\n" +
	"\v_acc_activeB\x0e\n" +
	"\f_door_activeB\x0e\n" +
	"\f_shock_levelB\f\n" +
	"\n" +
	"_engine_onB\t\n" +
	"\a_bat_mvB\x10\n" +
	"\x0e_last_shock_atB\x0e\n" +
	"\f_reported_at\"h\n" +
	"\rVehicleConfig\x12$\n" +
	"\x0epost_period_ms\x18\x01 \x01(\rR\fpostPeriodMs\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x03 \x01(\rR\tfieldMaskBBZ@github.com/sepehrshrz/vehicle_common.grpc/genproto/device;deviceb\x06proto3"

var (
	file_d_vehicle_v1_proto_rawDescOnce sync.Once
	file_d_vehicle_v1_proto_rawDescData []byte
)

func file_d_vehicle_v1_proto_rawDescGZIP() []byte {
	file_d_vehicle_v1_proto_rawDescOnce.Do(func() {
		file_d_vehicle_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_d_vehicle_v1_proto_rawDesc), len(file_d_vehicle_v1_proto_rawDesc)))
	})
	return file_d_vehicle_v1_proto_rawDescData
}

var file_d_vehicle_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_d_vehicle_v1_proto_goTypes = []any{
	(*VehicleStatus)(nil), // 0: device.VehicleStatus
	(*VehicleConfig)(nil), // 1: device.VehicleConfig
}
var file_d_vehicle_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_d_vehicle_v1_proto_init() }
func file_d_vehicle_v1_proto_init() {
	if File_d_vehicle_v1_proto != nil {
		return
	}
	file_d_vehicle_v1_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_d_vehicle_v1_proto_rawDesc), len(file_d_vehicle_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_d_vehicle_v1_proto_goTypes,
		DependencyIndexes: file_d_vehicle_v1_proto_depIdxs,
		MessageInfos:      file_d_vehicle_v1_proto_msgTypes,
	}.Build()
	File_d_vehicle_v1_proto = out.File
	file_d_vehicle_v1_proto_goTypes = nil
	file_d_vehicle_v1_proto_depIdxs = nil
}
