<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_common_const.proto

namespace Shared_common_const;

use UnexpectedValueException;

/**
 * Protobuf type <code>shared_common_const.CommandStatus</code>
 */
class CommandStatus
{
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_UNSPECIFIED = 0;</code>
     */
    const COMMAND_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_PENDING = 1;</code>
     */
    const COMMAND_STATUS_PENDING = 1;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_IN_PROGRESS = 5;</code>
     */
    const COMMAND_STATUS_IN_PROGRESS = 5;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_DOWN = 6;</code>
     */
    const COMMAND_STATUS_DOWN = 6;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_FAILED = 7;</code>
     */
    const COMMAND_STATUS_FAILED = 7;

    private static $valueToName = [
        self::COMMAND_STATUS_UNSPECIFIED => 'COMMAND_STATUS_UNSPECIFIED',
        self::COMMAND_STATUS_PENDING => 'COMMAND_STATUS_PENDING',
        self::COMMAND_STATUS_IN_PROGRESS => 'COMMAND_STATUS_IN_PROGRESS',
        self::COMMAND_STATUS_DOWN => 'COMMAND_STATUS_DOWN',
        self::COMMAND_STATUS_FAILED => 'COMMAND_STATUS_FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

