<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_common_const.proto

namespace Shared_common_const;

use UnexpectedValueException;

/**
 * Protobuf type <code>shared_common_const.ForceStopStatus</code>
 */
class ForceStopStatus
{
    /**
     * Generated from protobuf enum <code>FORCE_STOP_STATUS_UNSPECIFIED = 0;</code>
     */
    const FORCE_STOP_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>FORCE_STOP_STATUS_DE_ACTIVE = 1;</code>
     */
    const FORCE_STOP_STATUS_DE_ACTIVE = 1;
    /**
     * Generated from protobuf enum <code>FORCE_STOP_STATUS_ACTIVE = 2;</code>
     */
    const FORCE_STOP_STATUS_ACTIVE = 2;
    /**
     * Generated from protobuf enum <code>FORCE_STOP_STATUS_PENDING = 3;</code>
     */
    const FORCE_STOP_STATUS_PENDING = 3;
    /**
     * Generated from protobuf enum <code>FORCE_STOP_STATUS_IN_PROGRESS = 4;</code>
     */
    const FORCE_STOP_STATUS_IN_PROGRESS = 4;

    private static $valueToName = [
        self::FORCE_STOP_STATUS_UNSPECIFIED => 'FORCE_STOP_STATUS_UNSPECIFIED',
        self::FORCE_STOP_STATUS_DE_ACTIVE => 'FORCE_STOP_STATUS_DE_ACTIVE',
        self::FORCE_STOP_STATUS_ACTIVE => 'FORCE_STOP_STATUS_ACTIVE',
        self::FORCE_STOP_STATUS_PENDING => 'FORCE_STOP_STATUS_PENDING',
        self::FORCE_STOP_STATUS_IN_PROGRESS => 'FORCE_STOP_STATUS_IN_PROGRESS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

