<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use UnexpectedValueException;

/**
 * Protobuf type <code>device.CommandStatus</code>
 */
class CommandStatus
{
    /**
     * Generated from protobuf enum <code>CMD_UNSPECIFIED = 0;</code>
     */
    const CMD_UNSPECIFIED = 0;
    /**
     * long job queued (FOTA)
     *
     * Generated from protobuf enum <code>CMD_ACCEPTED = 1;</code>
     */
    const CMD_ACCEPTED = 1;
    /**
     * Generated from protobuf enum <code>CMD_OK = 2;</code>
     */
    const CMD_OK = 2;
    /**
     * Generated from protobuf enum <code>CMD_FAILED = 3;</code>
     */
    const CMD_FAILED = 3;
    /**
     * Generated from protobuf enum <code>CMD_UNSUPPORTED = 4;</code>
     */
    const CMD_UNSUPPORTED = 4;
    /**
     * Generated from protobuf enum <code>CMD_EXPIRED = 5;</code>
     */
    const CMD_EXPIRED = 5;
    /**
     * Generated from protobuf enum <code>CMD_BUSY = 6;</code>
     */
    const CMD_BUSY = 6;

    private static $valueToName = [
        self::CMD_UNSPECIFIED => 'CMD_UNSPECIFIED',
        self::CMD_ACCEPTED => 'CMD_ACCEPTED',
        self::CMD_OK => 'CMD_OK',
        self::CMD_FAILED => 'CMD_FAILED',
        self::CMD_UNSUPPORTED => 'CMD_UNSUPPORTED',
        self::CMD_EXPIRED => 'CMD_EXPIRED',
        self::CMD_BUSY => 'CMD_BUSY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

