<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use UnexpectedValueException;

/**
 * Protobuf type <code>device.CommandType</code>
 */
class CommandType
{
    /**
     * Generated from protobuf enum <code>CMD_TYPE_UNSPECIFIED = 0;</code>
     */
    const CMD_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>CMD_ECHO = 1;</code>
     */
    const CMD_ECHO = 1;
    /**
     * Generated from protobuf enum <code>CMD_REBOOT = 2;</code>
     */
    const CMD_REBOOT = 2;
    /**
     * Generated from protobuf enum <code>CMD_FOTA = 3;</code>
     */
    const CMD_FOTA = 3;
    /**
     * Generated from protobuf enum <code>CMD_GET_CONFIG = 4;</code>
     */
    const CMD_GET_CONFIG = 4;
    /**
     * EngineParams.on: true=engine on, false=engine off
     *
     * Generated from protobuf enum <code>CMD_ENGINE = 5;</code>
     */
    const CMD_ENGINE = 5;
    /**
     * SetConfigParams: patch blocks; omit = unchanged
     *
     * Generated from protobuf enum <code>CMD_SET_CONFIG = 6;</code>
     */
    const CMD_SET_CONFIG = 6;

    private static $valueToName = [
        self::CMD_TYPE_UNSPECIFIED => 'CMD_TYPE_UNSPECIFIED',
        self::CMD_ECHO => 'CMD_ECHO',
        self::CMD_REBOOT => 'CMD_REBOOT',
        self::CMD_FOTA => 'CMD_FOTA',
        self::CMD_GET_CONFIG => 'CMD_GET_CONFIG',
        self::CMD_ENGINE => 'CMD_ENGINE',
        self::CMD_SET_CONFIG => 'CMD_SET_CONFIG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

