<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.CommandResponse</code>
 */
class CommandResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device.CommandHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.device.CommandStatus status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint32 error_code = 3;</code>
     */
    protected $error_code = 0;
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>optional .device.CommandState previous = 11;</code>
     */
    protected $previous = null;
    /**
     * Generated from protobuf field <code>optional .device.CommandState applied = 12;</code>
     */
    protected $applied = null;
    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 100;</code>
     */
    protected $proto_version = 0;
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device\CommandHeader $header
     *     @type int $status
     *     @type int $error_code
     *     @type string $message
     *     @type \Device\DeviceConfiguration $config
     *           GET_CONFIG (kept for compatibility)
     *     @type \Device\CommandState $previous
     *     @type \Device\CommandState $applied
     *     @type int $proto_version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDCommandV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device.CommandHeader header = 1;</code>
     * @return \Device\CommandHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.device.CommandHeader header = 1;</code>
     * @param \Device\CommandHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Device\CommandHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.CommandStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.device.CommandStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Device\CommandStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 error_code = 3;</code>
     * @return int
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>uint32 error_code = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * GET_CONFIG (kept for compatibility)
     *
     * Generated from protobuf field <code>.device.DeviceConfiguration config = 10;</code>
     * @return \Device\DeviceConfiguration|null
     */
    public function getConfig()
    {
        return $this->readOneof(10);
    }

    public function hasConfig()
    {
        return $this->hasOneof(10);
    }

    /**
     * GET_CONFIG (kept for compatibility)
     *
     * Generated from protobuf field <code>.device.DeviceConfiguration config = 10;</code>
     * @param \Device\DeviceConfiguration $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Device\DeviceConfiguration::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .device.CommandState previous = 11;</code>
     * @return \Device\CommandState|null
     */
    public function getPrevious()
    {
        return $this->previous;
    }

    public function hasPrevious()
    {
        return isset($this->previous);
    }

    public function clearPrevious()
    {
        unset($this->previous);
    }

    /**
     * Generated from protobuf field <code>optional .device.CommandState previous = 11;</code>
     * @param \Device\CommandState $var
     * @return $this
     */
    public function setPrevious($var)
    {
        GPBUtil::checkMessage($var, \Device\CommandState::class);
        $this->previous = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .device.CommandState applied = 12;</code>
     * @return \Device\CommandState|null
     */
    public function getApplied()
    {
        return $this->applied;
    }

    public function hasApplied()
    {
        return isset($this->applied);
    }

    public function clearApplied()
    {
        unset($this->applied);
    }

    /**
     * Generated from protobuf field <code>optional .device.CommandState applied = 12;</code>
     * @param \Device\CommandState $var
     * @return $this
     */
    public function setApplied($var)
    {
        GPBUtil::checkMessage($var, \Device\CommandState::class);
        $this->applied = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 100;</code>
     * @return int
     */
    public function getProtoVersion()
    {
        return $this->proto_version;
    }

    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 100;</code>
     * @param int $var
     * @return $this
     */
    public function setProtoVersion($var)
    {
        GPBUtil::checkEnum($var, \Device\ProtoVersion::class);
        $this->proto_version = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

