<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Per-command snapshot carried in CommandResponse.previous / .applied.
 *
 * Generated from protobuf message <code>device.CommandState</code>
 */
class CommandState extends \Google\Protobuf\Internal\Message
{
    /**
     * SET_CONFIG / GET_CONFIG
     *
     * Generated from protobuf field <code>optional .device.DeviceConfiguration config = 1;</code>
     */
    protected $config = null;
    /**
     * CMD_ENGINE
     *
     * Generated from protobuf field <code>optional .device.EngineParams engine = 2;</code>
     */
    protected $engine = null;
    /**
     * CMD_ECHO
     *
     * Generated from protobuf field <code>optional string echo = 3;</code>
     */
    protected $echo = null;
    /**
     * CMD_FOTA
     *
     * Generated from protobuf field <code>optional .device.FotaAckState fota = 4;</code>
     */
    protected $fota = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device\DeviceConfiguration $config
     *           SET_CONFIG / GET_CONFIG
     *     @type \Device\EngineParams $engine
     *           CMD_ENGINE
     *     @type string $echo
     *           CMD_ECHO
     *     @type \Device\FotaAckState $fota
     *           CMD_FOTA
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDCommandV1::initOnce();
        parent::__construct($data);
    }

    /**
     * SET_CONFIG / GET_CONFIG
     *
     * Generated from protobuf field <code>optional .device.DeviceConfiguration config = 1;</code>
     * @return \Device\DeviceConfiguration|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * SET_CONFIG / GET_CONFIG
     *
     * Generated from protobuf field <code>optional .device.DeviceConfiguration config = 1;</code>
     * @param \Device\DeviceConfiguration $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Device\DeviceConfiguration::class);
        $this->config = $var;

        return $this;
    }

    /**
     * CMD_ENGINE
     *
     * Generated from protobuf field <code>optional .device.EngineParams engine = 2;</code>
     * @return \Device\EngineParams|null
     */
    public function getEngine()
    {
        return $this->engine;
    }

    public function hasEngine()
    {
        return isset($this->engine);
    }

    public function clearEngine()
    {
        unset($this->engine);
    }

    /**
     * CMD_ENGINE
     *
     * Generated from protobuf field <code>optional .device.EngineParams engine = 2;</code>
     * @param \Device\EngineParams $var
     * @return $this
     */
    public function setEngine($var)
    {
        GPBUtil::checkMessage($var, \Device\EngineParams::class);
        $this->engine = $var;

        return $this;
    }

    /**
     * CMD_ECHO
     *
     * Generated from protobuf field <code>optional string echo = 3;</code>
     * @return string
     */
    public function getEcho()
    {
        return isset($this->echo) ? $this->echo : '';
    }

    public function hasEcho()
    {
        return isset($this->echo);
    }

    public function clearEcho()
    {
        unset($this->echo);
    }

    /**
     * CMD_ECHO
     *
     * Generated from protobuf field <code>optional string echo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEcho($var)
    {
        GPBUtil::checkString($var, True);
        $this->echo = $var;

        return $this;
    }

    /**
     * CMD_FOTA
     *
     * Generated from protobuf field <code>optional .device.FotaAckState fota = 4;</code>
     * @return \Device\FotaAckState|null
     */
    public function getFota()
    {
        return $this->fota;
    }

    public function hasFota()
    {
        return isset($this->fota);
    }

    public function clearFota()
    {
        unset($this->fota);
    }

    /**
     * CMD_FOTA
     *
     * Generated from protobuf field <code>optional .device.FotaAckState fota = 4;</code>
     * @param \Device\FotaAckState $var
     * @return $this
     */
    public function setFota($var)
    {
        GPBUtil::checkMessage($var, \Device\FotaAckState::class);
        $this->fota = $var;

        return $this;
    }

}

