<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_telemetry_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MQTT root for ingest/telemetry/state (no Envelope).
 *
 * Generated from protobuf message <code>device.DeviceTelemetry</code>
 */
class DeviceTelemetry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 1;</code>
     */
    protected $proto_version = 0;
    /**
     * Generated from protobuf field <code>optional .device.DeviceIdentity identity = 2;</code>
     */
    protected $identity = null;
    /**
     * Generated from protobuf field <code>optional .device.GpsTelemetry gps = 3;</code>
     */
    protected $gps = null;
    /**
     * Generated from protobuf field <code>optional .device.VehicleStatus vehicle = 4;</code>
     */
    protected $vehicle = null;
    /**
     * Generated from protobuf field <code>uint32 timestamp = 5;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>uint32 seq = 6;</code>
     */
    protected $seq = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $proto_version
     *     @type \Device\DeviceIdentity $identity
     *     @type \Device\GpsTelemetry $gps
     *     @type \Device\VehicleStatus $vehicle
     *     @type int $timestamp
     *     @type int $seq
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDTelemetryV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 1;</code>
     * @return int
     */
    public function getProtoVersion()
    {
        return $this->proto_version;
    }

    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProtoVersion($var)
    {
        GPBUtil::checkEnum($var, \Device\ProtoVersion::class);
        $this->proto_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .device.DeviceIdentity identity = 2;</code>
     * @return \Device\DeviceIdentity|null
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    public function hasIdentity()
    {
        return isset($this->identity);
    }

    public function clearIdentity()
    {
        unset($this->identity);
    }

    /**
     * Generated from protobuf field <code>optional .device.DeviceIdentity identity = 2;</code>
     * @param \Device\DeviceIdentity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Device\DeviceIdentity::class);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .device.GpsTelemetry gps = 3;</code>
     * @return \Device\GpsTelemetry|null
     */
    public function getGps()
    {
        return $this->gps;
    }

    public function hasGps()
    {
        return isset($this->gps);
    }

    public function clearGps()
    {
        unset($this->gps);
    }

    /**
     * Generated from protobuf field <code>optional .device.GpsTelemetry gps = 3;</code>
     * @param \Device\GpsTelemetry $var
     * @return $this
     */
    public function setGps($var)
    {
        GPBUtil::checkMessage($var, \Device\GpsTelemetry::class);
        $this->gps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .device.VehicleStatus vehicle = 4;</code>
     * @return \Device\VehicleStatus|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>optional .device.VehicleStatus vehicle = 4;</code>
     * @param \Device\VehicleStatus $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \Device\VehicleStatus::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timestamp = 5;</code>
     * @return int
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint32 timestamp = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 seq = 6;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Generated from protobuf field <code>uint32 seq = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint32($var);
        $this->seq = $var;

        return $this;
    }

}

