<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MQTT root for device/{id}/command
 *
 * Generated from protobuf message <code>device.DeviceCommand</code>
 */
class DeviceCommand extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device.CommandHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.device.CommandType type = 2;</code>
     */
    protected $type = 0;
    /**
     * Serialized EchoParams | RebootParams | FotaParams | GetConfigParams |
     * EngineParams | SetConfigParams
     *
     * Generated from protobuf field <code>bytes params = 3;</code>
     */
    protected $params = '';
    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 100;</code>
     */
    protected $proto_version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device\CommandHeader $header
     *     @type int $type
     *     @type string $params
     *           Serialized EchoParams | RebootParams | FotaParams | GetConfigParams |
     *           EngineParams | SetConfigParams
     *     @type int $proto_version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDCommandV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device.CommandHeader header = 1;</code>
     * @return \Device\CommandHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.device.CommandHeader header = 1;</code>
     * @param \Device\CommandHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Device\CommandHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.CommandType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.device.CommandType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Device\CommandType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Serialized EchoParams | RebootParams | FotaParams | GetConfigParams |
     * EngineParams | SetConfigParams
     *
     * Generated from protobuf field <code>bytes params = 3;</code>
     * @return string
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Serialized EchoParams | RebootParams | FotaParams | GetConfigParams |
     * EngineParams | SetConfigParams
     *
     * Generated from protobuf field <code>bytes params = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, False);
        $this->params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 100;</code>
     * @return int
     */
    public function getProtoVersion()
    {
        return $this->proto_version;
    }

    /**
     * Generated from protobuf field <code>.device.ProtoVersion proto_version = 100;</code>
     * @param int $var
     * @return $this
     */
    public function setProtoVersion($var)
    {
        GPBUtil::checkEnum($var, \Device\ProtoVersion::class);
        $this->proto_version = $var;

        return $this;
    }

}

