<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_config_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Full/partial snapshot of current settings (read path).
 *
 * Generated from protobuf message <code>device.DeviceConfiguration</code>
 */
class DeviceConfiguration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device.NetworkConfig network = 1;</code>
     */
    protected $network = null;
    /**
     * Generated from protobuf field <code>.device.SmsNotificationConfig sms = 2;</code>
     */
    protected $sms = null;
    /**
     * Generated from protobuf field <code>.device.GpsConfig gps = 3;</code>
     */
    protected $gps = null;
    /**
     * Generated from protobuf field <code>.device.LoggingConfig logging = 4;</code>
     */
    protected $logging = null;
    /**
     * Generated from protobuf field <code>.device.TelemetryConfig telemetry = 5;</code>
     */
    protected $telemetry = null;
    /**
     * Generated from protobuf field <code>.device.VehicleConfig vehicle = 6;</code>
     */
    protected $vehicle = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Device\NetworkConfig $network
     *     @type \Device\SmsNotificationConfig $sms
     *     @type \Device\GpsConfig $gps
     *     @type \Device\LoggingConfig $logging
     *     @type \Device\TelemetryConfig $telemetry
     *     @type \Device\VehicleConfig $vehicle
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDConfigV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device.NetworkConfig network = 1;</code>
     * @return \Device\NetworkConfig|null
     */
    public function getNetwork()
    {
        return $this->network;
    }

    public function hasNetwork()
    {
        return isset($this->network);
    }

    public function clearNetwork()
    {
        unset($this->network);
    }

    /**
     * Generated from protobuf field <code>.device.NetworkConfig network = 1;</code>
     * @param \Device\NetworkConfig $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkMessage($var, \Device\NetworkConfig::class);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.SmsNotificationConfig sms = 2;</code>
     * @return \Device\SmsNotificationConfig|null
     */
    public function getSms()
    {
        return $this->sms;
    }

    public function hasSms()
    {
        return isset($this->sms);
    }

    public function clearSms()
    {
        unset($this->sms);
    }

    /**
     * Generated from protobuf field <code>.device.SmsNotificationConfig sms = 2;</code>
     * @param \Device\SmsNotificationConfig $var
     * @return $this
     */
    public function setSms($var)
    {
        GPBUtil::checkMessage($var, \Device\SmsNotificationConfig::class);
        $this->sms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.GpsConfig gps = 3;</code>
     * @return \Device\GpsConfig|null
     */
    public function getGps()
    {
        return $this->gps;
    }

    public function hasGps()
    {
        return isset($this->gps);
    }

    public function clearGps()
    {
        unset($this->gps);
    }

    /**
     * Generated from protobuf field <code>.device.GpsConfig gps = 3;</code>
     * @param \Device\GpsConfig $var
     * @return $this
     */
    public function setGps($var)
    {
        GPBUtil::checkMessage($var, \Device\GpsConfig::class);
        $this->gps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.LoggingConfig logging = 4;</code>
     * @return \Device\LoggingConfig|null
     */
    public function getLogging()
    {
        return $this->logging;
    }

    public function hasLogging()
    {
        return isset($this->logging);
    }

    public function clearLogging()
    {
        unset($this->logging);
    }

    /**
     * Generated from protobuf field <code>.device.LoggingConfig logging = 4;</code>
     * @param \Device\LoggingConfig $var
     * @return $this
     */
    public function setLogging($var)
    {
        GPBUtil::checkMessage($var, \Device\LoggingConfig::class);
        $this->logging = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.TelemetryConfig telemetry = 5;</code>
     * @return \Device\TelemetryConfig|null
     */
    public function getTelemetry()
    {
        return $this->telemetry;
    }

    public function hasTelemetry()
    {
        return isset($this->telemetry);
    }

    public function clearTelemetry()
    {
        unset($this->telemetry);
    }

    /**
     * Generated from protobuf field <code>.device.TelemetryConfig telemetry = 5;</code>
     * @param \Device\TelemetryConfig $var
     * @return $this
     */
    public function setTelemetry($var)
    {
        GPBUtil::checkMessage($var, \Device\TelemetryConfig::class);
        $this->telemetry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.device.VehicleConfig vehicle = 6;</code>
     * @return \Device\VehicleConfig|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>.device.VehicleConfig vehicle = 6;</code>
     * @param \Device\VehicleConfig $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \Device\VehicleConfig::class);
        $this->vehicle = $var;

        return $this;
    }

}

