<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_fota_v1.proto

namespace Device;

if (false) {
    /**
     * This class is deprecated. Use Device\FotaStatus\State instead.
     * @deprecated
     */
    class FotaStatus_State {}
}
class_exists(FotaStatus\State::class);
@trigger_error('Device\FotaStatus_State is deprecated and will be removed in the next major release. Use Device\FotaStatus\State instead', E_USER_DEPRECATED);

