<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MQTT root for ingest/telemetry/ack
 *
 * Generated from protobuf message <code>device.FotaAckState</code>
 */
class FotaAckState extends \Google\Protobuf\Internal\Message
{
    /**
     * Running (or about-to-run) firmware identity string, same shape as DeviceIdentity.fw_version.
     *
     * Generated from protobuf field <code>string fw_version = 1;</code>
     */
    protected $fw_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fw_version
     *           Running (or about-to-run) firmware identity string, same shape as DeviceIdentity.fw_version.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDCommandV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Running (or about-to-run) firmware identity string, same shape as DeviceIdentity.fw_version.
     *
     * Generated from protobuf field <code>string fw_version = 1;</code>
     * @return string
     */
    public function getFwVersion()
    {
        return $this->fw_version;
    }

    /**
     * Running (or about-to-run) firmware identity string, same shape as DeviceIdentity.fw_version.
     *
     * Generated from protobuf field <code>string fw_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFwVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->fw_version = $var;

        return $this;
    }

}

