<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.FotaParams</code>
 */
class FotaParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string package_url = 1;</code>
     */
    protected $package_url = '';
    /**
     * Generated from protobuf field <code>string target_version = 2;</code>
     */
    protected $target_version = '';
    /**
     * Generated from protobuf field <code>bool force = 3;</code>
     */
    protected $force = false;
    /**
     * exactly 32 bytes; required
     *
     * Generated from protobuf field <code>bytes sha256 = 4;</code>
     */
    protected $sha256 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $package_url
     *     @type string $target_version
     *     @type bool $force
     *     @type string $sha256
     *           exactly 32 bytes; required
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDCommandV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string package_url = 1;</code>
     * @return string
     */
    public function getPackageUrl()
    {
        return $this->package_url;
    }

    /**
     * Generated from protobuf field <code>string package_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPackageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->package_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_version = 2;</code>
     * @return string
     */
    public function getTargetVersion()
    {
        return $this->target_version;
    }

    /**
     * Generated from protobuf field <code>string target_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool force = 3;</code>
     * @return bool
     */
    public function getForce()
    {
        return $this->force;
    }

    /**
     * Generated from protobuf field <code>bool force = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setForce($var)
    {
        GPBUtil::checkBool($var);
        $this->force = $var;

        return $this;
    }

    /**
     * exactly 32 bytes; required
     *
     * Generated from protobuf field <code>bytes sha256 = 4;</code>
     * @return string
     */
    public function getSha256()
    {
        return $this->sha256;
    }

    /**
     * exactly 32 bytes; required
     *
     * Generated from protobuf field <code>bytes sha256 = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSha256($var)
    {
        GPBUtil::checkString($var, False);
        $this->sha256 = $var;

        return $this;
    }

}

