<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use UnexpectedValueException;

/**
 * Protobuf type <code>device.GpsRecoverAction</code>
 */
class GpsRecoverAction
{
    /**
     * Generated from protobuf enum <code>GPS_RECOVER_UNSPECIFIED = 0;</code>
     */
    const GPS_RECOVER_UNSPECIFIED = 0;
    /**
     * $PAIR006
     *
     * Generated from protobuf enum <code>GPS_RECOVER_COLD_START = 1;</code>
     */
    const GPS_RECOVER_COLD_START = 1;
    /**
     * RESET_N pulse
     *
     * Generated from protobuf enum <code>GPS_RECOVER_HW_RESET = 2;</code>
     */
    const GPS_RECOVER_HW_RESET = 2;
    /**
     * $PAIR007 — clears config; rare
     *
     * Generated from protobuf enum <code>GPS_RECOVER_FULL_COLD = 3;</code>
     */
    const GPS_RECOVER_FULL_COLD = 3;

    private static $valueToName = [
        self::GPS_RECOVER_UNSPECIFIED => 'GPS_RECOVER_UNSPECIFIED',
        self::GPS_RECOVER_COLD_START => 'GPS_RECOVER_COLD_START',
        self::GPS_RECOVER_HW_RESET => 'GPS_RECOVER_HW_RESET',
        self::GPS_RECOVER_FULL_COLD => 'GPS_RECOVER_FULL_COLD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

