<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.GpsRecoverParams</code>
 */
class GpsRecoverParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.device.GpsRecoverAction action = 1;</code>
     */
    protected $action = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDCommandV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.device.GpsRecoverAction action = 1;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>.device.GpsRecoverAction action = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Device\GpsRecoverAction::class);
        $this->action = $var;

        return $this;
    }

}

