<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_gps_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.GpsSatInfo</code>
 */
class GpsSatInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 prn = 1;</code>
     */
    protected $prn = 0;
    /**
     * Generated from protobuf field <code>sint32 elev = 2;</code>
     */
    protected $elev = 0;
    /**
     * Generated from protobuf field <code>uint32 azim = 3;</code>
     */
    protected $azim = 0;
    /**
     * Generated from protobuf field <code>uint32 snr = 4;</code>
     */
    protected $snr = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $prn
     *     @type int $elev
     *     @type int $azim
     *     @type int $snr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDGpsV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 prn = 1;</code>
     * @return int
     */
    public function getPrn()
    {
        return $this->prn;
    }

    /**
     * Generated from protobuf field <code>uint32 prn = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrn($var)
    {
        GPBUtil::checkUint32($var);
        $this->prn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 elev = 2;</code>
     * @return int
     */
    public function getElev()
    {
        return $this->elev;
    }

    /**
     * Generated from protobuf field <code>sint32 elev = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setElev($var)
    {
        GPBUtil::checkInt32($var);
        $this->elev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 azim = 3;</code>
     * @return int
     */
    public function getAzim()
    {
        return $this->azim;
    }

    /**
     * Generated from protobuf field <code>uint32 azim = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAzim($var)
    {
        GPBUtil::checkUint32($var);
        $this->azim = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 snr = 4;</code>
     * @return int
     */
    public function getSnr()
    {
        return $this->snr;
    }

    /**
     * Generated from protobuf field <code>uint32 snr = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSnr($var)
    {
        GPBUtil::checkUint32($var);
        $this->snr = $var;

        return $this;
    }

}

