<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_config_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.NetworkConfig</code>
 */
class NetworkConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string apn = 1;</code>
     */
    protected $apn = '';
    /**
     * Generated from protobuf field <code>string user = 2;</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>string pass = 3;</code>
     */
    protected $pass = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $apn
     *     @type string $user
     *     @type string $pass
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDConfigV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string apn = 1;</code>
     * @return string
     */
    public function getApn()
    {
        return $this->apn;
    }

    /**
     * Generated from protobuf field <code>string apn = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApn($var)
    {
        GPBUtil::checkString($var, True);
        $this->apn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 2;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pass = 3;</code>
     * @return string
     */
    public function getPass()
    {
        return $this->pass;
    }

    /**
     * Generated from protobuf field <code>string pass = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPass($var)
    {
        GPBUtil::checkString($var, True);
        $this->pass = $var;

        return $this;
    }

}

