<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_common_v1.proto

namespace Device;

use UnexpectedValueException;

/**
 * Bump ProtoVersion when the on-wire contract for a root changes in a way
 * consumers must notice (removed/renumbered fields, Envelope removed, etc.).
 * Additive optional fields may keep the same version if backends are
 * forward-compatible. Firmware always sets the current value on encode.
 *
 * Protobuf type <code>device.ProtoVersion</code>
 */
class ProtoVersion
{
    /**
     * Generated from protobuf enum <code>PROTO_VERSION_UNSPECIFIED = 0;</code>
     */
    const PROTO_VERSION_UNSPECIFIED = 0;
    /**
     * DeviceTelemetry roots, no Envelope
     *
     * Generated from protobuf enum <code>PROTO_VERSION_1 = 1;</code>
     */
    const PROTO_VERSION_1 = 1;

    private static $valueToName = [
        self::PROTO_VERSION_UNSPECIFIED => 'PROTO_VERSION_UNSPECIFIED',
        self::PROTO_VERSION_1 => 'PROTO_VERSION_1',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

