<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_command_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.RebootParams</code>
 */
class RebootParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 delay_ms = 1;</code>
     */
    protected $delay_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $delay_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDCommandV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 delay_ms = 1;</code>
     * @return int
     */
    public function getDelayMs()
    {
        return $this->delay_ms;
    }

    /**
     * Generated from protobuf field <code>uint32 delay_ms = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDelayMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->delay_ms = $var;

        return $this;
    }

}

