<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_config_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.SmsNotificationConfig</code>
 */
class SmsNotificationConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * max 5 (nanopb STATIC)
     *
     * Generated from protobuf field <code>repeated .device.SmsRecipient recipients = 1;</code>
     */
    private $recipients;
    /**
     * master switch
     *
     * Generated from protobuf field <code>bool enabled = 2;</code>
     */
    protected $enabled = false;
    /**
     * Generated from protobuf field <code>bool enable_shock = 3;</code>
     */
    protected $enable_shock = false;
    /**
     * Generated from protobuf field <code>bool enable_acc_on = 4;</code>
     */
    protected $enable_acc_on = false;
    /**
     * Generated from protobuf field <code>bool enable_acc_off = 5;</code>
     */
    protected $enable_acc_off = false;
    /**
     * Generated from protobuf field <code>bool enable_door_open = 6;</code>
     */
    protected $enable_door_open = false;
    /**
     * Generated from protobuf field <code>bool enable_door_close = 7;</code>
     */
    protected $enable_door_close = false;
    /**
     * Generated from protobuf field <code>string msg_shock = 8;</code>
     */
    protected $msg_shock = '';
    /**
     * Generated from protobuf field <code>string msg_acc_on = 9;</code>
     */
    protected $msg_acc_on = '';
    /**
     * Generated from protobuf field <code>string msg_acc_off = 10;</code>
     */
    protected $msg_acc_off = '';
    /**
     * Generated from protobuf field <code>string msg_door_open = 11;</code>
     */
    protected $msg_door_open = '';
    /**
     * Generated from protobuf field <code>string msg_door_close = 12;</code>
     */
    protected $msg_door_close = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Device\SmsRecipient>|\Google\Protobuf\Internal\RepeatedField $recipients
     *           max 5 (nanopb STATIC)
     *     @type bool $enabled
     *           master switch
     *     @type bool $enable_shock
     *     @type bool $enable_acc_on
     *     @type bool $enable_acc_off
     *     @type bool $enable_door_open
     *     @type bool $enable_door_close
     *     @type string $msg_shock
     *     @type string $msg_acc_on
     *     @type string $msg_acc_off
     *     @type string $msg_door_open
     *     @type string $msg_door_close
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDConfigV1::initOnce();
        parent::__construct($data);
    }

    /**
     * max 5 (nanopb STATIC)
     *
     * Generated from protobuf field <code>repeated .device.SmsRecipient recipients = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecipients()
    {
        return $this->recipients;
    }

    /**
     * max 5 (nanopb STATIC)
     *
     * Generated from protobuf field <code>repeated .device.SmsRecipient recipients = 1;</code>
     * @param array<\Device\SmsRecipient>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecipients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Device\SmsRecipient::class);
        $this->recipients = $arr;

        return $this;
    }

    /**
     * master switch
     *
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * master switch
     *
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_shock = 3;</code>
     * @return bool
     */
    public function getEnableShock()
    {
        return $this->enable_shock;
    }

    /**
     * Generated from protobuf field <code>bool enable_shock = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableShock($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_shock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_acc_on = 4;</code>
     * @return bool
     */
    public function getEnableAccOn()
    {
        return $this->enable_acc_on;
    }

    /**
     * Generated from protobuf field <code>bool enable_acc_on = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableAccOn($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_acc_on = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_acc_off = 5;</code>
     * @return bool
     */
    public function getEnableAccOff()
    {
        return $this->enable_acc_off;
    }

    /**
     * Generated from protobuf field <code>bool enable_acc_off = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableAccOff($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_acc_off = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_door_open = 6;</code>
     * @return bool
     */
    public function getEnableDoorOpen()
    {
        return $this->enable_door_open;
    }

    /**
     * Generated from protobuf field <code>bool enable_door_open = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableDoorOpen($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_door_open = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_door_close = 7;</code>
     * @return bool
     */
    public function getEnableDoorClose()
    {
        return $this->enable_door_close;
    }

    /**
     * Generated from protobuf field <code>bool enable_door_close = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableDoorClose($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_door_close = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_shock = 8;</code>
     * @return string
     */
    public function getMsgShock()
    {
        return $this->msg_shock;
    }

    /**
     * Generated from protobuf field <code>string msg_shock = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgShock($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_shock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_acc_on = 9;</code>
     * @return string
     */
    public function getMsgAccOn()
    {
        return $this->msg_acc_on;
    }

    /**
     * Generated from protobuf field <code>string msg_acc_on = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgAccOn($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_acc_on = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_acc_off = 10;</code>
     * @return string
     */
    public function getMsgAccOff()
    {
        return $this->msg_acc_off;
    }

    /**
     * Generated from protobuf field <code>string msg_acc_off = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgAccOff($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_acc_off = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_door_open = 11;</code>
     * @return string
     */
    public function getMsgDoorOpen()
    {
        return $this->msg_door_open;
    }

    /**
     * Generated from protobuf field <code>string msg_door_open = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgDoorOpen($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_door_open = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_door_close = 12;</code>
     * @return string
     */
    public function getMsgDoorClose()
    {
        return $this->msg_door_close;
    }

    /**
     * Generated from protobuf field <code>string msg_door_close = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgDoorClose($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_door_close = $var;

        return $this;
    }

}

