<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_telemetry_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.TelemetryConfig</code>
 */
class TelemetryConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Ignored by firmware: DeviceTelemetry.identity is always sent.
     * Kept for config wire compatibility (do not renumber).
     *
     * Generated from protobuf field <code>bool include_identity = 1;</code>
     */
    protected $include_identity = false;
    /**
     * default true
     *
     * Generated from protobuf field <code>bool include_gps = 2;</code>
     */
    protected $include_gps = false;
    /**
     * default true
     *
     * Generated from protobuf field <code>bool include_vehicle = 3;</code>
     */
    protected $include_vehicle = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $include_identity
     *           Ignored by firmware: DeviceTelemetry.identity is always sent.
     *           Kept for config wire compatibility (do not renumber).
     *     @type bool $include_gps
     *           default true
     *     @type bool $include_vehicle
     *           default true
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDTelemetryV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Ignored by firmware: DeviceTelemetry.identity is always sent.
     * Kept for config wire compatibility (do not renumber).
     *
     * Generated from protobuf field <code>bool include_identity = 1;</code>
     * @return bool
     */
    public function getIncludeIdentity()
    {
        return $this->include_identity;
    }

    /**
     * Ignored by firmware: DeviceTelemetry.identity is always sent.
     * Kept for config wire compatibility (do not renumber).
     *
     * Generated from protobuf field <code>bool include_identity = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeIdentity($var)
    {
        GPBUtil::checkBool($var);
        $this->include_identity = $var;

        return $this;
    }

    /**
     * default true
     *
     * Generated from protobuf field <code>bool include_gps = 2;</code>
     * @return bool
     */
    public function getIncludeGps()
    {
        return $this->include_gps;
    }

    /**
     * default true
     *
     * Generated from protobuf field <code>bool include_gps = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeGps($var)
    {
        GPBUtil::checkBool($var);
        $this->include_gps = $var;

        return $this;
    }

    /**
     * default true
     *
     * Generated from protobuf field <code>bool include_vehicle = 3;</code>
     * @return bool
     */
    public function getIncludeVehicle()
    {
        return $this->include_vehicle;
    }

    /**
     * default true
     *
     * Generated from protobuf field <code>bool include_vehicle = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeVehicle($var)
    {
        GPBUtil::checkBool($var);
        $this->include_vehicle = $var;

        return $this;
    }

}

