<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared_d_vehicle_v1.proto

namespace Device;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>device.VehicleConfig</code>
 */
class VehicleConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * state uplink interval when vehicle-driven (default 1000)
     *
     * Generated from protobuf field <code>uint32 post_period_ms = 1;</code>
     */
    protected $post_period_ms = 0;
    /**
     * human-readable label, e.g. "Truck-12"
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Ignored by firmware: all VehicleStatus fields are always sent.
     * Kept for config wire compatibility (do not renumber).
     *
     * Generated from protobuf field <code>uint32 field_mask = 3;</code>
     */
    protected $field_mask = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $post_period_ms
     *           state uplink interval when vehicle-driven (default 1000)
     *     @type string $name
     *           human-readable label, e.g. "Truck-12"
     *     @type int $field_mask
     *           Ignored by firmware: all VehicleStatus fields are always sent.
     *           Kept for config wire compatibility (do not renumber).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SharedDVehicleV1::initOnce();
        parent::__construct($data);
    }

    /**
     * state uplink interval when vehicle-driven (default 1000)
     *
     * Generated from protobuf field <code>uint32 post_period_ms = 1;</code>
     * @return int
     */
    public function getPostPeriodMs()
    {
        return $this->post_period_ms;
    }

    /**
     * state uplink interval when vehicle-driven (default 1000)
     *
     * Generated from protobuf field <code>uint32 post_period_ms = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPostPeriodMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->post_period_ms = $var;

        return $this;
    }

    /**
     * human-readable label, e.g. "Truck-12"
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * human-readable label, e.g. "Truck-12"
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Ignored by firmware: all VehicleStatus fields are always sent.
     * Kept for config wire compatibility (do not renumber).
     *
     * Generated from protobuf field <code>uint32 field_mask = 3;</code>
     * @return int
     */
    public function getFieldMask()
    {
        return $this->field_mask;
    }

    /**
     * Ignored by firmware: all VehicleStatus fields are always sent.
     * Kept for config wire compatibility (do not renumber).
     *
     * Generated from protobuf field <code>uint32 field_mask = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldMask($var)
    {
        GPBUtil::checkUint32($var);
        $this->field_mask = $var;

        return $this;
    }

}

