// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shared_common_const.proto

package shared_common_const

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForceStopStatus int32

const (
	ForceStopStatus_FORCE_STOP_STATUS_UNSPECIFIED ForceStopStatus = 0
	ForceStopStatus_FORCE_STOP_STATUS_DE_ACTIVE   ForceStopStatus = 1
	ForceStopStatus_FORCE_STOP_STATUS_ACTIVE      ForceStopStatus = 2
	ForceStopStatus_FORCE_STOP_STATUS_PENDING     ForceStopStatus = 3
	ForceStopStatus_FORCE_STOP_STATUS_IN_PROGRESS ForceStopStatus = 4
)

// Enum value maps for ForceStopStatus.
var (
	ForceStopStatus_name = map[int32]string{
		0: "FORCE_STOP_STATUS_UNSPECIFIED",
		1: "FORCE_STOP_STATUS_DE_ACTIVE",
		2: "FORCE_STOP_STATUS_ACTIVE",
		3: "FORCE_STOP_STATUS_PENDING",
		4: "FORCE_STOP_STATUS_IN_PROGRESS",
	}
	ForceStopStatus_value = map[string]int32{
		"FORCE_STOP_STATUS_UNSPECIFIED": 0,
		"FORCE_STOP_STATUS_DE_ACTIVE":   1,
		"FORCE_STOP_STATUS_ACTIVE":      2,
		"FORCE_STOP_STATUS_PENDING":     3,
		"FORCE_STOP_STATUS_IN_PROGRESS": 4,
	}
)

func (x ForceStopStatus) Enum() *ForceStopStatus {
	p := new(ForceStopStatus)
	*p = x
	return p
}

func (x ForceStopStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForceStopStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_common_const_proto_enumTypes[0].Descriptor()
}

func (ForceStopStatus) Type() protoreflect.EnumType {
	return &file_shared_common_const_proto_enumTypes[0]
}

func (x ForceStopStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForceStopStatus.Descriptor instead.
func (ForceStopStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_common_const_proto_rawDescGZIP(), []int{0}
}

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_PENDING     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_IN_PROGRESS CommandStatus = 5
	CommandStatus_COMMAND_STATUS_DOWN        CommandStatus = 6
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 7
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_PENDING",
		5: "COMMAND_STATUS_IN_PROGRESS",
		6: "COMMAND_STATUS_DOWN",
		7: "COMMAND_STATUS_FAILED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_PENDING":     1,
		"COMMAND_STATUS_IN_PROGRESS": 5,
		"COMMAND_STATUS_DOWN":        6,
		"COMMAND_STATUS_FAILED":      7,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_common_const_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_shared_common_const_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_common_const_proto_rawDescGZIP(), []int{1}
}

var File_shared_common_const_proto protoreflect.FileDescriptor

const file_shared_common_const_proto_rawDesc = "" +
	"\n" +
	"\x19shared_common_const.proto\x12\x13shared_common_const*\xb5\x01\n" +
	"\x0fForceStopStatus\x12!\n" +
	"\x1dFORCE_STOP_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bFORCE_STOP_STATUS_DE_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18FORCE_STOP_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19FORCE_STOP_STATUS_PENDING\x10\x03\x12!\n" +
	"\x1dFORCE_STOP_STATUS_IN_PROGRESS\x10\x04*\x9f\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_IN_PROGRESS\x10\x05\x12\x17\n" +
	"\x13COMMAND_STATUS_DOWN\x10\x06\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\aB\\ZZgithub.com/sepehrshrz/vehicle_common.grpc/genproto/shared_common_const;shared_common_constb\x06proto3"

var (
	file_shared_common_const_proto_rawDescOnce sync.Once
	file_shared_common_const_proto_rawDescData []byte
)

func file_shared_common_const_proto_rawDescGZIP() []byte {
	file_shared_common_const_proto_rawDescOnce.Do(func() {
		file_shared_common_const_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_common_const_proto_rawDesc), len(file_shared_common_const_proto_rawDesc)))
	})
	return file_shared_common_const_proto_rawDescData
}

var file_shared_common_const_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shared_common_const_proto_goTypes = []any{
	(ForceStopStatus)(0), // 0: shared_common_const.ForceStopStatus
	(CommandStatus)(0),   // 1: shared_common_const.CommandStatus
}
var file_shared_common_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_common_const_proto_init() }
func file_shared_common_const_proto_init() {
	if File_shared_common_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_common_const_proto_rawDesc), len(file_shared_common_const_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_common_const_proto_goTypes,
		DependencyIndexes: file_shared_common_const_proto_depIdxs,
		EnumInfos:         file_shared_common_const_proto_enumTypes,
	}.Build()
	File_shared_common_const_proto = out.File
	file_shared_common_const_proto_goTypes = nil
	file_shared_common_const_proto_depIdxs = nil
}
